export interface IScaleMchat{
  patient: string,
  dateOfApplication: string,
  doctor: string,
  childLikesToSwing: boolean,
  hasInterestInOtherChildren: boolean,
  likesToClimbOnThings: boolean,
  likesToPlayHideAndSeek: boolean,
  hasPlayedPretend: boolean,
  hasUsedIndexFingerToPointToAskForSomething: boolean,
  hasUsedIndexFingerToPointToIndicateInterest: boolean,
  canPlayCorrectlyWithSmallToys: boolean,
  hasBroughtObjectsToYouToShowThem: boolean,
  looksAtYouInTheEyesForMoreThanASecondOrTwo: boolean,
  hasSeemedVerySensitiveToNoise: boolean,
  smilesInResponseToYourFacialExpressionsOrSmile: boolean,
  imitatesYou: boolean,
  respondsOrLooksWhenYouCallHerByName: boolean,
  doesChildFollowYourGazeWhenYouPoint: boolean,
  canWalk: boolean,
  looksAtThingsYouAreLookingAt: boolean,
  makesStrangeMovementsNearHisFace: boolean,
  triesToAttractYourAttentionToHisActivity: boolean,
  haveYouEverWonderedIfYourChildIsDeaf: boolean,
  understandsWhatPeopleSay: boolean,
  sometimesGetsSpaceyOrWalksWithoutDirection: boolean,
  looksAtYourFaceToCheckYourReactionWhenSeeingSomethingStrange: boolean
}