
import { IObservedAspectsPshyco } from "./incomeAssessment";
import { IEvaluationofPerformanceBody2At4YearsPshyco } from "./incomeAssessment";
import { IEvaluationOfPerformanceBody5At6YearsPshyco } from "./incomeAssessment";
import { IEvaluationOfPerformanceTrailsAndOthers2At4YearsPshyco } from "./incomeAssessment";
import { IEvaluationOfPerformanceTrailsAndOthers5At6YearsPshyco } from "./incomeAssessment";
import { IEvaluationOfPerformanceListeningSpeechAndOthers2At4YearsPshyco } from "./incomeAssessment";
import { IEvaluationOfPerformanceListeningSpeechAndOthers5At6YearsPshyco } from "./incomeAssessment";
import { IEvaluationOfPerformanceSpacesAndOthers2At4YearsPshyco } from "./incomeAssessment";
import { IEvaluationOfPerformanceSpacesAndOthers5At6YearsPshyco } from "./incomeAssessment";
import { IEvaluationOfPerformanceTheSelfAndOthers2At4YearsPshyco } from "./incomeAssessment";
import { IEvaluationOfPerformanceTheSelfAndOthers5At6YearsPshyco } from "./incomeAssessment";
import { ITheSelfAndOthersPshyco } from "./incomeAssessment";
import { IBodyAndOthersPshyco } from "./incomeAssessment";
import { ITrailsAndOthersPshyco } from "./incomeAssessment";
import { IListeningAndOthersPshyco } from "./incomeAssessment";
import { ISpacesAndOthersPshyco } from "./incomeAssessment";
import { IPortugueseLanguage1GradePshyco } from "./incomeAssessment";
import { IMathematics1GradePshyco } from "./incomeAssessment";
import { IPortugueseLanguage2GradePshyco } from "./incomeAssessment";
import { IMathematics2GradePshyco } from "./incomeAssessment";
import { IPortugueseLanguage3GradePshyco } from "./incomeAssessment";
import { IMathematics3GradePshyco } from "./incomeAssessment";
import { IPortugueseLanguage4GradePshyco } from "./incomeAssessment";
import { IMathematics4GradePshyco } from "./incomeAssessment";
import { IPortugueseLanguage5GradePshyco } from "./incomeAssessment";
import { IMathematics5GradePshyco } from "./incomeAssessment";


export interface IIaPsychoPedagogical {
    doctor: string;
    dateOfApplication: string;
    patient: string;
    dateOfBirth: string;
    familyOurSchoolComplaint: string;
    observation: string;
    observedAspectsPshyco: IObservedAspectsPshyco;
    evaluationofPerformanceBody2At4YearsPshyco: IEvaluationofPerformanceBody2At4YearsPshyco;
    evaluationOfPerformanceBody5At6YearsPshyco: IEvaluationOfPerformanceBody5At6YearsPshyco;
    evaluationOfPerformanceTrailsAndOthers2At4YearsPshyco: IEvaluationOfPerformanceTrailsAndOthers2At4YearsPshyco;
    evaluationOfPerformanceTrailsAndOthers5At6YearsPshyco: IEvaluationOfPerformanceTrailsAndOthers5At6YearsPshyco;
    evaluationOfPerformanceListeningSpeechAndOthers2At4YearsPshyco: IEvaluationOfPerformanceListeningSpeechAndOthers2At4YearsPshyco;
    evaluationOfPerformanceListeningSpeechAndOthers5At6YearsPshyco: IEvaluationOfPerformanceListeningSpeechAndOthers5At6YearsPshyco;
    evaluationOfPerformanceSpacesAndOthers2At4YearsPshyco: IEvaluationOfPerformanceSpacesAndOthers2At4YearsPshyco;
    evaluationOfPerformanceSpacesAndOthers5At6YearsPshyco: IEvaluationOfPerformanceSpacesAndOthers5At6YearsPshyco;
    evaluationOfPerformanceTheSelfAndOthers2At4YearsPshyco: IEvaluationOfPerformanceTheSelfAndOthers2At4YearsPshyco;
    evaluationOfPerformanceTheSelfAndOthers5At6YearsPshyco: IEvaluationOfPerformanceTheSelfAndOthers5At6YearsPshyco;
    theSelfAndOthersPshyco: ITheSelfAndOthersPshyco;
    bodyAndOthersPshyco: IBodyAndOthersPshyco;
    trailsAndOthersPshyco: ITrailsAndOthersPshyco;
    listeningAndOthersPshyco: IListeningAndOthersPshyco;
    spacesAndOthersPshyco: ISpacesAndOthersPshyco;
    portugueseLanguage1GradePshyco: IPortugueseLanguage1GradePshyco;
    mathematics1GradePshyco: IMathematics1GradePshyco;
    portugueseLanguage2GradePshyco: IPortugueseLanguage2GradePshyco;
    mathematics2GradePshyco: IMathematics2GradePshyco;
    portugueseLanguage3GradePshyco: IPortugueseLanguage3GradePshyco;
    mathematics3GradePshyco: IMathematics3GradePshyco;
    portugueseLanguage4GradePshyco: IPortugueseLanguage4GradePshyco;
    mathematics4GradePshyco: IMathematics4GradePshyco;
    portugueseLanguage5GradePshyco: IPortugueseLanguage5GradePshyco;
    mathematics5GradePshyco: IMathematics5GradePshyco;
    observationIaPshyco: string;
    evaluatorsSignaturePshyco: string;
};