export interface IBehaviorQuestionnaireAndSocialCommunicationYesOrNo{
    yes: number;
    no: number;
}

export interface IBehaviorQuestionnaireAndSocialCommunication{
      
    isAbleToConverseUsingShortPhrasesOrSentences: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
ifNotProceedToQuestion9: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
doesHeTalkToYouJustToBeFriendly: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
canYouHaveADialogue: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
doesHeUseStrangePhrasesOrSayThingsRepeatedly: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
doesHeOftenUseSociallyInappropriateQuestionsOrStatements: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
doesHeOftenUsePronounsInverted: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
doesHeOftenUseWordsThatHeSeemsToHaveInvented: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
doesHeOftenSayTheSameThingRepeatedly: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
areThereThingsThatAreDoneByHimInAParticularWay: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
doesHisFacialExpressionGenerallySeemAppropriate: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
hasHeEverUsedYourHandAsATool: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
doesHeOftenHaveSpecialInterestsThatSeemWeirdToOthers: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
doesHeOftenGetMoreInterestedInPartsOfAnObject: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
doesHeOftenHaveSpecificInterests: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
doesHeOftenInAWierdWayLookFeelListenTasteOrSmellThingsOrPeople: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
doesHeOftenHaveMannerismsOrStrangeWaysOfMovingHisHandsOrFingers: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
doesHeOftenMakeComplexMovementsWithHisWholeBody: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
doesHeOftenHurtHimselfOnPurpose: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
doesHeHaveAnObjectThatHeCarriesAround: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
doesHeHaveAParticularFriendOrABestFriend: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
whenHeWas4To5YearsOldDidHeRepeatedOrImitateWhatYouDid: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
whenHeWas4To5YearsOldDidHePointAtThings: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
whenHeWas4To5YearsOldDidHeUseGesturesToSHowWhatHeWanted: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
whenHeWas4To5YearsOldDidHeUseHisHeadToSayYes: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
whenHeWas4To5YearsOldDidHeShakeHisHeadToSayNo: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
whenHeWas4To5YearsOldDidHeUsuallyLookYouDirectlyInTheFace: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
whenHeWas4To5YearsOldDidHeSmileBackIfSomeoneSmiledAtHim: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
whenHeWas4To5YearsOldDidHeShowThingsOfHisInterestToGetYourAttention: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
whenHeWas4To5YearsOldDidHeShareThingsWithYouBesidesFood: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
whenHeWas4To5YearsOldDidHeWantYouToParticipateInSomethingThatWasEntertainingHim: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
whenHeWas4To5YearsOldDidHeTryToComfortYouIfYouWereSadOrHurt: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
betweenTheAgesOf4To5YearsWhenHeWantedSomethingOrSomeHelpDidHeLookAtYou: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
betweenTheAgesOf4To5YearsDidHeHaveNormalFacialExpressions: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
whenHeWas4Or5YearsOldDidHeParticipateSpontaneouslyInSocialGames: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
whenHeWas4Or5YearsOldDidHePlayImaginaryGames: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
whenHeWas4Or5YearsOldDidHeSeemInterestedInOtherChildren: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
whenHeWas4Or5YearsOldDidHeReactPositivelyWhenAnotherChildApproachedHim: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
whenHeWas4Or5YearsOldIfYouEnteredTheRoomAndStartedACConversationWithHim: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
whenHeWas4Or5YearsOldDidHePlayMakeBelieveWithAnotherChild: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
whenHeWas4Or5YearsOldDidHePlayCooperativelyInGroupGames: IBehaviorQuestionnaireAndSocialCommunicationYesOrNo,
totalPoints: number
    scoreAsq: {
        yesScore: number;
        noScore: number;
        };
    
        totalResultAsq: {
            resultTotal: number;
        }
}


