

export interface IBehaviorQuestionnaireAndSocialCommunication{
    
    isAbleToConverseUsingShortPhrasesOrSentences: Boolean,
    ifNotProceedToQuestion9: Boolean,
    doesHeTalkToYouJustToBeFriendly: Boolean,
    canYouHaveADialogue: Boolean,
    doesHeUseStrangePhrasesOrSayThingsRepeatedly: Boolean,
    doesHeOftenUseSociallyInappropriateQuestionsOrStatements: Boolean,
    doesHeOftenUsePronounsInverted: Boolean,
    doesHeOftenUseWordsThatHeSeemsToHaveInvented: Boolean,
    doesHeOftenSayTheSameThingRepeatedly: Boolean,
    areThereThingsThatAreDoneByHimInAParticularWay: Boolean,
    doesHisFacialExpressionGenerallySeemAppropriate: Boolean,
    hasHeEverUsedYourHandAsATool: Boolean,
    doesHeOftenHaveSpecialInterestsThatSeemWeirdToOthers: Boolean,
    doesHeOftenGetMoreInterestedInPartsOfAnObject: Boolean,
    doesHeOftenHaveSpecificInterests: Boolean,
    doesHeOftenInAWierdWayLookFeelListenTasteOrSmellThingsOrPeople: Boolean,
    doesHeOftenHaveMannerismsOrStrangeWaysOfMovingHisHandsOrFingers: Boolean,
    doesHeOftenMakeComplexMovementsWithHisWholeBody: Boolean,
    doesHeOftenHurtHimselfOnPurpose: Boolean,
    doesHeHaveAnObjectThatHeCarriesAround: Boolean,
    doesHeHaveAParticularFriendOrABestFriend: Boolean,
    whenHeWas4To5YearsOldDidHeRepeatedOrImitateWhatYouDid: Boolean,
    whenHeWas4To5YearsOldDidHePointAtThings: Boolean,
    whenHeWas4To5YearsOldDidHeUseGesturesToSHowWhatHeWanted: Boolean,
    whenHeWas4To5YearsOldDidHeUseHisHeadToSayYes: Boolean,
    whenHeWas4To5YearsOldDidHeShakeHisHeadToSayNo: Boolean,
    whenHeWas4To5YearsOldDidHeUsuallyLookYouDirectlyInTheFace: Boolean,
    whenHeWas4To5YearsOldDidHeSmileBackIfSomeoneSmiledAtHim: Boolean,
    whenHeWas4To5YearsOldDidHeShowThingsOfHisInterestToGetYourAttention: Boolean,
    whenHeWas4To5YearsOldDidHeShareThingsWithYouBesidesFood: Boolean,
    whenHeWas4To5YearsOldDidHeWantYouToParticipateInSomethingThatWasEntertainingHim: Boolean,
    whenHeWas4To5YearsOldDidHeTryToComfortYouIfYouWereSadOrHurt: Boolean,
    betweenTheAgesOf4To5YearsWhenHeWantedSomethingOrSomeHelpDidHeLookAtYou: Boolean,
    betweenTheAgesOf4To5YearsDidHeHaveNormalFacialExpressions: Boolean,
    whenHeWas4Or5YearsOldDidHeParticipateSpontaneouslyInSocialGames: Boolean,
    whenHeWas4Or5YearsOldDidHePlayImaginaryGames: Boolean,
    whenHeWas4Or5YearsOldDidHeSeemInterestedInOtherChildren: Boolean,
    whenHeWas4Or5YearsOldDidHeReactPositivelyWhenAnotherChildApproachedHim: Boolean,
    whenHeWas4Or5YearsOldIfYouEnteredTheRoomAndStartedACConversationWithHim: Boolean,
    whenHeWas4Or5YearsOldDidHePlayMakeBelieveWithAnotherChild: Boolean,
    whenHeWas4Or5YearsOldDidHePlayCooperativelyInGroupGames: Boolean,
}


