version: "3"

services: 
  app:
    image: codeinnove/api-inspiratio-codeinnove:1.0-amd64
    build: .
    container_name: API-inspiratio-codeinnove
    restart: always
    tty: true
    networks: 
      - API-inspiratio-codeinnove_bridge
    ports: 
      - 9000:3000
      - 9229:9229
    volumes: 
      - .:/usr/src/app
      # - /usr/src/app/node_modules
    command: yarn start:dev
    environment:
      NODE_ENV: development
    depends_on: 
      - db

  db:
    image: mongo:latest
    container_name: deploy-vercel-inspiratio_db
    networks:
      - API-inspiratio-codeinnove_bridge
    volumes:
      - ./db-mongo:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: deploy-vercel-inspiratio_db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

networks: 
  API-inspiratio-codeinnove_bridge:
    driver: bridge
