//export interface IPortageGuidetoPreschoolEducation {
    export interface ISocialization0To1Year {
        observesAPersonMovingInTheirVisualField: number,
        smilesInResponseToAdultAttention: number,
        vocalizesInResponseToAttention: number,
        looksAtOwnHandSmilingOrVocalizing: number,
        respondsToFamilyCircleSmilingVocalizingOrStoppingCrying: number,
        smilesInResponseToOthersFacialExpressions: number,
         smilesAndVocalizesWhenSeeingImageInMirror: number,
        caressesOrTouchesAdultsFacesPullsHairNoseGlassesEtc: number,
        reachesTowardsAnOfferedObject: number,
         reachesArmsTowardsFamilyMembers: number,
        extendsHandAndTouchesOwnReflectedImageInMirror: number,
         holdsAndExaminesGivenObjectFor1Minute: number,
        shakesOrSqueezesAnObjectPlacedInHandProducingInvoluntarySounds: number,
          playsAloneFor10Minutes: number,
        seeksEyeContactWhenSomeonePaysAttentionFor2To3Minutes: number,
         playsAloneWithoutComplainingFor15To20MinutesNearAnAdult: number,
        vocalizesToGetAttention: number,
        imitatesAdultInPeekABooGames: number,
        clapsHandsImitatingAnAdult: number,
        wavesHandImitatingAnAdult: number,
       raisesArmsToExpressBigImitatingAnAdult: number,
       offersSomethingButDoesNotAlwaysDeliver: number,
        hugsCaressesAndKissesFamilyMembers: number,
        respondsToOwnNameLookingOrExtendingArmToBePickedUp: number,
        squeezesOrShakesToyToProduceSoundsInImitation: number,
       manipulatesToyOrObject: number,
         extendsAToyOrObjectToAnAdultAndDeliversIt: number,
       imitatesMovementsOfOtherChildrenWhilePlaying: number
    }
     
   export interface ISocialization1To2Years {
      imitatesAnAdultInASimpleTask: number,
     playsNextToAnotherChildEachPerformingDifferentTasks: number,
      takesPartInAPlayWithAnotherChildFor2To5Minutes: number,
      acceptsParentsAbsenceAlthoughMayComplain: number,
      activelyExploresItsEnvironment: number,
       performsManipulativeActivityWithAnotherPerson: number,
     hugsAndCarriesADollOrSoftToy: number,
      repeatsActionsThatProduceLaughterAndAttention: number,
      givesABookForAnAdultToReadOrForBothToShare: number,
      pullsAPersonToShowThemSomething: number,
      withdrawsHandOrSaysNoWhenNearForbiddenObjectAndSomeoneRemindsIt: number,
     whenPlacedInChairOrChangingTableWaitsToBeAttended: number,
      playsWith2Or3ChildrenOfSameAge: number,
     sharesAnObjectOrFoodWithAnotherChild: number,
     greetsPeersOrAdultsWhenReminded: number
   }
    export interface ISocialization2To3Years {
      obeysParentsOrdersAtLeastHalfTheTime: number,
      seeksOrTakesAnObjectOrPersonWhenAsked: number,
      paysAttentionToStoryOrMusicFor5To10Minutes: number,
       saysPleaseOrThankYouWhenReminded: number,
       triesToHelpParentsPerformTasksByDoingPartOfIt: number,
        playsAtWearingAdultsClothes: number,
     makesAChoiceWhenAsked: number,
       demonstratesUnderstandingOfFeelingsExpressingThem: number
    }
    export interface ISocialization3To4Years {
      singsAndDancesWhenHearingMusic: number,
     followsRulesOfAGameImitatingActionsOfOtherChildren: number,
     greetsFamilyMembersWithoutBeingReminded: number,
       followsRulesInGroupGamesDirectedByAdults: number,
     asksPermissionToPlayWithAToyBeingUsedByAnotherChild: number,
     saysPleaseAndThankYouWithoutBeingRemindedHalfTheTime: number,
      answersThePhoneCallingAnAdultAndSpeakingWithFamilyMembers: number,
     waitsItsTurn: number,
     followsRulesInGamesDirectedByAnOlderChild: number,
     obeysAdultsOrders75PercentOfTheTime: number,
       staysInItsOwnYardOrGarden: number,
      playsNearOtherChildrenTalkingToThemWhileWorkingOnOwnProject30Minutes: number
    }
    export interface ISocialization4To5Years {
      asksForHelpWhenHavingDifficulties: number,
      contributesToAdultConversation: number,
      repeatsRhymesSongsOrDancesForOthers: number,
       doesATaskAloneFor20To30Minutes: number,
      apologizesWithoutBeingReminded75PercentOfTheTime: number,
      waitsItsTurnInPlayInvolving8To9Children: number,
     playsWith2To3ChildrenFor20MinutesInAnActivityInvolvingCooperation: number,
     whenInPublicPresentsASociallyAcceptableBehavior: number,
    asksPermissionToUseOthersObjects75PercentOfTheTime: number
    }
    export interface ISocialization5To6Years {
      expressesItsFeelings: number,
      playsWith4To5ChildrenInCooperativeActivityFor20MinutesWithoutSupervision: number,
     explainsToOthersTheRulesOfTheGameOrActivity: number,
      imitatesAdultRoles: number,
      collaboratesInConversationDuringMeals: number,
     followsRulesOfAGameInvolvingVerbalReasoning: number,
     comfortsPeersWhenTheyAreSad: number,
     choosesItsOwnFriends: number,
     plansAndBuildsUsingSimpleTools: number,
     setsGoalsForItselfAndPerformsActivityToAchieveThem: number,
      dramatizesExcerptsFromStoriesPlayingARoleOrUsingPuppets: number
    }
    export interface ILanguage0To1Years {
       repeatsSoundsMadeByOtherPeople: number,
       repeatsSameSyllable2To3Times: number,
       respondsToGesturesWithGestures: number,
     obeysASimpleOrderWhenAccompaniedByIndicativeGestures: number,
       interruptsActivityWhenToldNo75PercentOfTheTime: number,
      respondsToSimpleQuestionsWithNonVerbalAnswers: number,
     combines2DifferentSyllablesWhenTryingToVerbalize: number,
     imitatesIntonationPatternsOfOthersVoice: number,
    usesAWordFunctionallyToIndicateObjectsOrPeople: number,
     vocalizesInResponseToOtherPeoplesSpeech: number
    }
    export interface ILanguage1To2Years {
       says5DifferentWords: number,
     asksForMore: number,
      saysDone: number,
      obeys3DifferentOrdersThatAreNotAccompaniedByIndicativeGestures: number,
     managesToGiveOrShowWhenAsked: number,
     pointsTo12ObjectsWhenNamed: number,
      pointsTo3To5FiguresInABook: number,
      pointsTo3PartsOfOwnBody: number,
      saysOwnNameOrNicknameWhenAsked: number,
       respondsToTheQuestionWhatIsThis: number,
      combinesWordsAndGesturesToExpressWishes: number,
       names5FamilyMembersIncludingAnimals: number,
     names4Toys: number,
       producesAnimalSoundsOrNamesThemByTheSound: number,
      asksForKnownFoodsByNameWhenShown: number,
      asksQuestionsVaryingIntonationOfVoice: number,
     names3BodyPartsOnADollOrAnotherPerson: number,
     respondsToYesNoQuestions: number
    }
    export interface ILanguage2To3Years {
     combinesNounsOrAdjectivesAndNounsIn2WordSentences: number,
      combinesNounAndVerbIn2WordSentences: number,
     usesAWordToIndicateThatWantsToGoToTheBathroom: number,
      combinesVerbOrNounWithThereAndHereIn2WordSentences: number,
    combines2WordsToExpressPossession: number,
     usesNoInSpeech: number,
      respondsToTheQuestionWhatIsDoingForHabitualActivity: number,
     respondsToQuestionsLikeWhereIsObject: number,
       namesFamiliarEnvironmentalSounds: number,
     givesMoreThanOneObjectWhenUsingThePluralFormInTheRequest: number,
      whenSpeakingRefersToItselfByName: number,
     pointsToFiguresOfCommonObjectsDescribedByUseUpTo10WhatIsUsedToEatSpoon: number,
     showsAgeByFingers: number,
      saysSexWhenAsked: number,
       obeysTheSequenceOfTwoRelatedOrders: number,
       usesTheVerbFormInTheGerund: number,
       employsRegularPluralForms: number,
      employsSomeIrregularFormsOfVerbsInThePastSystematically: number,
       asksQuestionsLikeWhatIsThis: number,
      controlsVolumeOfVoice90PercentOfTheTime: number,
       usesThisAndThatInSpeech: number,
     employsIsAndIsLocatedInSimpleSentences: number,
       saysIMeMineInsteadOfOwnName: number,
      pointsToObjectsAndSaysTheyAreNotOtherThings: number,
       respondsToTheQuestionWhoGivingAName: number,
      employsPossessiveFormsOfNouns: number,
      usesArticlesWhenSpeaking: number,
       usesNounsThatIndicateAGroupOrCategory: number,
      usesTheVerbsToBeToExistAndToHaveInThePresentWithFewErrors: number,
      saysIfObjectsAreOpenOrClosed: number
    }
    export interface ILanguage3To4Years {
     expressesDiminutivesAndAugmentativesWhenSpeaking: number,
      paysAttentionFor5MinutesToAReadStory: number,
     obeysSequenceOf2UnrelatedOrders: number,
     saysFullNameWhenAsked: number,
     respondsSimpleQuestionsInvolvingHow: number,
      employsRegularVerbsInThePast: number,
       reportsImmediateExperiences: number,
      saysHowCommonObjectsAreUsed: number,
      expressesFutureActionsUsingVerbsToGoToHaveAndToWant: number,
       usesMasculineAndFeminineAppropriatelyInSpeech: number,
      usesImperativeFormsOfVerbsWhenAskingForFavors: number,
       tells2FactsInOrderOfOccurrence: number
      }
      export interface ILanguage4To5Years {
      obeysASequenceInvolving3Orders: number,
     demonstratesUnderstandingOfReflexiveVerbsUsingThemOccasionallyExHeGotHurt: number,
      managesToIdentifyObjectsFiguresThatFormAPairUponRequest: number,
       employsFutureWhenSpeaking: number,
      usesSentencesComposedByCoordination: number,
      managesToIdentifyTheTopAndBottomPartOfObjectsWhenRequested: number,
      employsOccasionallyTheConditionalWhenSpeakingCouldWouldCouldWouldMake: number,
     managesToIdentifyAbsurditiesInFigures: number,
      employsTheFollowingWordsBrotherSisterGrandmotherGrandfather: number,
       completesSentencesWithAntonyms: number,
       tellsAKnownStoryWithoutHelpOfFigures: number,
     inAFigureNamesTheObjectThatDoesNotBelongToACertainCategory: number,
     saysIfTwoWordsRhymeOrNot: number,
      usesComplexSentencesComposedBySubordination: number,
       saysIfASoundIsLoudOrSoft: number
      }
      export interface ILanguage5To6Years {
      managesToIndicateSomeManyAndSeveralElements: number,
       saysOwnAddress: number,
       saysOwnPhoneNumber: number,
     pointsToTheSetThatHasMoreLessOrFewElements: number,
     tellsSimpleJokes: number,
       reportsDailyExperiences: number,
      describesALocationOrMovementThroughOrBetweenAwayFromFromSinceToOverUpTo: number,
    answersTheQuestionWhyWithAnExplanation: number,
     ordersAndTellsAStoryOf2To5EpisodesInTheCorrectSequence: number,
     definesWords: number,
       respondsAppropriatelyToTheQuestionWhatIsTheOppositeOf: number,
      respondsToTheQuestionWhatHappensIf: number,
     usesYesterdayAndTomorrowCorrectly: number,
      asksTheMeaningOfNewOrKnownQuestions: number
    }
    export interface ICognition0To1Year {
      removesAClothFromFaceThatObscuresVision: number,
       looksForObjectThatHasBeenRemovedFromItsVisualField: number,
      removesAnObjectFromAReceptacleByPuttingHandInsideIt: number,
     placesAnObjectInAReceptacleImitatingAnAdult: number,
     placesAnObjectInAReceptacleWhenGivenInstructions: number,
      shakesAToyThatProducesSoundHangingFromAString: number,
       placesThreeObjectsInAReceptacleAndEmptiesIt: number,
     transfersAnObjectFromOneHandToAnotherToPickUpAnotherObject: number,
    dropsAndPicksUpAToy: number,
      discoversAnObjectHiddenUnderAReceptacle: number,
      pushes3BlocksAsIfItWereATrain: number,
      removesACircleFromABoardByImitation: number,
      placesARoundPinInAPinBoardWhenRequested: number,
     performsSimpleGesturesWhenRequested: number
    }
    export interface ICognition1To2Years {
      removes6ObjectsFromAReceptacleOneAtATime: number,
    pointsToAPartOfTheBody: number,
    stacks3BlocksGivenTheOrder: number,
       matchesSimilarObjects: number,
      scribblesOnPaper: number,
       pointsToItselfWhenAskedWhereIsName: number,
      places5RoundPinsGivenTheOrder: number,
      matchesObjectsWithTheFigureOfTheSameName: number,
     pointsToTheNamedFigure: number,
     turnsThePagesOfABook23AtATimeToFindTheNamedFigure: number
    }
    export interface ICognition2To3Years {
      findsACertainBookWhenRequested: number,
     completesA3PieceJigsawPuzzle: number,
     names4CommonObjectsInFigures: number,
       drawsAVerticalLineImitatingAnAdult: number,
      drawsAHorizontalLineImitatingAnAdult: number,
    copiesACircle: number,
      matchesObjectsWithTheSameTexture: number,
    pointsToSmallAndBigWhenRequested: number,
    drawsAPlusSignImitatingAnAdult: number,
      matches3Colors: number,
    placesObjectsInsideOnTopAndUnderAReceptacleGivenTheOrder: number,
      namesObjectsWhenHearsTheNoiseTheyMake: number,
       mountsA4PieceFittingToy: number,
     namesActionsInFiguresWhatIsDoing: number,
       matchesGeometricShapeWithTheFigureOfTheSame: number,
      stacks5OrMoreRingsOnARodInOrder: number
    }
    export interface ICognition3To4Years {
      namesObjectsAsBeingBigOrSmall: number,
     pointsTo10PartsOfTheBodyWhenRequested: number,
    pointsToBoyAndGirlGivenTheOrder: number,
    saysIfAnObjectIsHeavyOrLight: number,
     unites2PartsOfAFigureToFormTheWhole: number,
      describes2EventsOrCharactersFromAFamiliarStoryOrTvProgram: number,
       repeatsGamesRhymesOrSongsThatInvolveCoordinatedMovements: number,
       matches3OrMoreObjects: number,
      pointsToLongOrShortObjects: number,
      associatesCorrespondingObjectsExSockShoe: number,
      countsUpTo3ImitatingAnAdult: number,
       groupsObjectsIntoCategories: number,
     tracesAVInImitation: number,
      tracesADiagonalLineGivenTheExample: number,
     countsUpTo10ObjectsImitatingAnAdult: number,
      buildsABridgeWith3BlocksByImitation: number,
      matchesASequenceOrPatternSizeColorOfBlocksOrBeads: number,
     copiesASeriesOfInterconnectedV: number,
       addsALegOrArmToAnIncompleteDrawingOfTheHumanFigure: number,
       completesA6PiecePuzzle: number,
      indicatesIfObjectsAreEqualOrDifferent: number,
     drawsASquareImitatingAnAdult: number,
     names3ColorsBeingRequested: number,
      names3GeometricShapesSquareTriangleAndCircle: number
    }
    export interface ICognition4To5Years {
      picksUpFrom1To5ObjectsWhenRequested: number,
    names5DifferentTextures: number,
    copiesATriangleWhenRequested: number,
    remembers4ObjectsThatHadBeenSeenInAFigure: number,
       saysTheTimeOfTheDayAssociatedWithEachActivity: number,
     repeatsFamiliarRhymes: number,
     saysIfAnObjectIsHeavierOrLighterObjectsWithADifferenceOf05Kilo: number,
       saysWhatIsMissingWhenAnObjectIsRemovedFromAGroupOf3Objects: number,
    names8Colors: number,
    identifiesTheValueOf3Coins: number,
      matchesSymbolsLettersAndNumbers: number,
       saysTheColorOfNamedObjects: number,
       reports5MainFactsOfAStoryTold3Times: number,
      drawsHumanFigureHeadTorsoAnd4Limbs: number,
       sings5VersesOfASong: number,
       buildsAPyramidOf10BlocksByImitation: number,
       namesObjectsAsBeingLongOrShort: number,
      placesObjectsBehindBesideOrNextToOthers: number,
     makesEqualSetsOf10ObjectsAccordingToModel: number,
       namesOrPointsToTheMissingPartOfTheFigure: number,
     countsFrom1To20: number,
    identifiesTheObjectThatIsPlacedInTheMiddleInFirstAndLastPlace: number
    }
    export interface ICognition5To6Years {
     countsUpTo20ObjectsAndAnswersAppropriatelyToTheQuestionHowManyDidYouCount: number,
     names10Numerals: number,
      identifiesWhichIsItsLeftAndWhichIsItsRight: number,
       saysTheVowelsInOrder: number,
    writesOwnNameWithBlockLetters: number,
     names5LettersOfTheAlphabet: number,
      ordersObjectsInSequenceOfLengthAndWidth: number,
      namesTheUppercaseLettersOfTheAlphabet: number,
      placesNumeralsFrom1To10InTheCorrectSequence: number,
       identifiesThePositionOfObjectsInFirstSecondAndThirdPlace: number,
     namesTheLowercaseLettersOfTheAlphabet: number,
      matchesUppercaseLettersWithLowercaseOnes: number,
       pointsToNumeralsFrom1To25: number,
      copiesARhombus: number,
       completesASimpleLabyrinth: number,
     saysTheDaysOfTheWeekInOrder: number,
      addsAndSubtractsCombinationsOfUpTo3Elements: number,
     saysTheMonthAndDayOfOwnBirthday: number,
       reads10PrintedWords: number,
       predictsWhatWillOccur: number,
      pointsToWholeAndHalfObjects: number,
      countsFromMemoryFrom1To100AskToStopAt40AndContinueAt80IfNoErrorsUntil40: number
    }
    export interface ISelfCare0To1Year {
    sucksAndSwallowsLiquids: number,
    eatsPorridgeOrSoup: number,
       extendsHandsTowardsBabyBottleTryingToGrabIt: number,
     eatsPureedFoodsGivenByParents: number,
      holdsBabyBottleWithoutHelpWhileDrinking: number,
    bringsBottleToMouthOrRefusesItPushingItAway: number,
    eatsMashedFoodsGivenByParents: number,
     drinksFromAMugHeldByParents: number,
     eatsSemisolidFoodsGivenByParents: number,
     feedsItselfUsingFingers: number,
    holdsTheMugWithBothHandsAndDrinks: number,
     bringsASpoonFullOfFoodToMouthWithHelp: number,
       stretchesArmsAndLegsWhenBeingDressed: number
   }
   export interface ISelfCare1To2Years {
      eatsWithSpoonIndependently: number,
       holdsMugWithOneHandAndDrinks: number,
       putsHandInWaterAndPatsFaceWithWetHandsImitatingSomeone: number,
       sitsOnAPottyOrChildsToiletFor5Minutes: number,
       putsAHatOnHeadAndRemovesIt: number,
      takesOffSocks: number,
      pushesArmsThroughSleevesAndFeetThroughTrouserLegs: number,
      takesOffShoesWhenLacesAreUntied: number,
      takesOffCoatWhenUnbuttoned: number,
      takesOffTrousersWhenUnbuttoned: number,
     pullsALargeZipperUpAndDown: number,
      usesWordsOrGesturesIndicatingNeedToGoToTheBathroom: number
   }
   export interface ISelfCare2To3Years {
    eatsAloneUsingSpoonOrMugSpillingALittleFoodOrLiquid: number,
     whenGivenATowelDriesHandsAndFaceWithHelp: number,
       sucksLiquidFromTheGlassOrMugUsingAStraw: number,
      takesForkfuls: number,
       chewsAndSwallowsOnlyEdibleSubstances: number,
      driesHandsWithoutHelpWhenGivenATowel: number,
     warnsThatWantsToGoToTheBathroomEvenIfItIsTooLate: number,
      controlsOwnDrool: number,
       urinatesOrDefecatesWhenPlacedInPottyAtLeast3TimesAWeek: number,
     putsOnShoes: number,
     brushesTeethImitatingAnAdult: number,
    removesSimpleClothesThatHaveBeenUnbuttoned: number,
    usesTheBathroomToDefecateFailsOnlyOnceAWeek: number,
      obtainsWaterFromAFaucetWithoutHelp: number,
     washesHandsAndFaceWithSoap: number,
      warnsThatWantsToGoToTheBathroomDuringTheDayInTime: number,
    hangsCoatOnAHookAtItsOwnHeight: number,
      staysDryWhenSleepingDuringTheDay: number,
       avoidsRisksExSharpEdgesOnFurnitureAndStairsWithoutHandrail: number,
     usesANapkinWhenRecommended: number,
       piercesTheForkInTheFoodTakingItToTheMouth: number,
     poursLiquidFromASmallPitcherIntoAGlassWithoutHelp: number,
       unfastensClothesFastenedWithASnapFastener: number,
       washesArmsAndLegsWhenGivenABath: number,
      putsOnSocks: number,
       wearsCoatJacketOrShirt: number,
      identifiesTheFrontPartOfClothes: number
    }
    export interface ISelfCare3To4Years {
     feedsItselfAloneForEntireMeal: number,
    dressesItselfAloneNeedingHelpOnlyWhenThereAreJacketsOrTShirtsWithClosedCollarsOrButtonsAndFasteners: number,
      wipesNoseWhenReminded: number,
      wakesUpDry2MorningsAWeek: number,
     ifBoyUrinatesInTheToiletWhileStanding: number,
      dressesAndUndressesItselfAloneExceptForButtonsAndFasteners75PercentOfTheTime: number,
    fastensClothesWithSnapsOrHooks: number,
     blowsNoseWhenReminded: number,
      avoidsCommonDangersExBrokenGlass: number,
     hangsClothesOnAHangerAndPutsInClosetWhenAsked: number,
     brushesTeethWhenReceivesInstruction: number,
    putsOnGloves: number,
    putsOnBoots: number,
      unbuttonsLargeButtons: number,
    buttonsLargeButtons: number
    }
    export interface ISelfCare4To5Years {
     cleansWhatItSpilledOnOwn: number,
     avoidsPoisonAndAllHarmfulSubstances: number,
    unbuttonsOwnClothes: number,
     buttonsOwnClothes: number,
    removesPlateAndCutleryFromTheTable: number,
     fitsZipperIntoItsTermination: number,
    washesHandsAndFace: number,
      usesAppropriateCutleryToEat: number,
     wakesUpAtNightToGoToTheBathroomOrWakesUpDry: number,
      cleansAndBlowsItsNose75PercentOfTheTimeWithoutBeingReminded: number,
     bathesAloneNeedingHelpOnlyToWashBackNeckAndEars: number,
      usesAKnifeToSpreadButterOnBread: number,
     tightensAndLoosensBeltsOrBuckles: number,
      dressesItselfAloneButDoesNotTieLaces: number,
     servesItselfAtTheTableWhileHoldingTheFoodPlatter: number,
      helpsSetTheTableCorrectlyWhenReceivesInstructions: number,
      brushesTeeth: number,
     goesToTheBathroomInTimeRemovesClothesUsesToiletPaperFlushesAndDressesWithoutHelp: number,
     combsOrBrushesHair: number,
      hangsClothesOnHangers: number,
       walksAroundTheNeighborhoodWithoutConstantSupervision: number,
      threadsLacesIntoShoes: number,
     tiesOrLacesShoelaces: number
      }
      export interface ISelfCare5To6Years {
     isResponsibleForAWeeklyTaskAndPerformsItWhenReminded: number,
      selectsAppropriateClothingForClimateAndOccasion: number,
     stopsOnTheSidewalkLooksBothWaysAndCrossesTheStreetWithoutNeedingToBeReminded: number,
      servesItselfAtTheTableAndPassesThePotOfFoodToOthers: number,
     preparesOwnCupOfCoffeeWithMilk: number,
     isResponsibleForADailyTaskAtHome: number,
      adjustsTheTemperatureOfWaterForBathing: number,
       preparesOwnSnack: number,
     walksAloneUpToADistanceOf2BlocksFromHome: number,
       cutsTenderFoodsWithAKnife: number,
     findsTheBathroomInAPublicPlaceCorrectly: number,
     opensTheMilkPackage: number,
      picksUpATrayWithFoodCarryingItAndPlacingItOnTheTable: number,
     tiesTheLacesOnJacketsWithHood: number,
    fastensTheCarSeatBelt: number
    }
    export interface IMotorDevelopment0To1Year {
      reachesForAnObjectPlacedInFrontOfIt15To20Cm: number,
      grabsAnObjectPlacedInFrontOfIt8Cm: number,
       extendsArmsTowardAnObjectInFrontOfItAndGrabsIt: number,
      reachesForAPreferredObject: number,
      putsObjectsInMouth: number,
     raisesHeadAndTorsoSupportingSelfOnArmsWhenLyingOnStomach: number,
    raisesHeadAndTorsoSupportingSelfOnOneArm: number,
     touchesAndExploresObjectsWithMouth: number,
    inPronePositionTurnsToTheSideAndMaintainsThisPositionHalfTheTime: number,
     inPronePositionTurnsOnBack: number,
     inPronePositionMovesForwardTheEquivalentOfItsHeight: number,
       inSupinePositionRollsToTheSide: number,
     inSupinePositionTurnsFromStomachToBack: number,
      makesEffortToSitHoldingOntoAdultsFingers: number,
       turnsHeadEasilyWhenTheBodyIsSupported: number,
      sitsFor2Minutes: number,
      releasesAnObjectToGrabAnother: number,
      grabsAndDropsAnObjectPurposefully: number,
       standsWithMaximumSupport: number,
     whileStandingWithSupportJumpsUpAndDown: number,
       crawlsToGrabAnObjectDistantItsHeight: number,
     sitsSupportingSelfAlone: number,
      whileSittingTurnsToCrawling: number,
     whileInPronePositionManagesToSit: number,
    sitsWithoutHandSupport: number,
    throwsObjectsAtRandom: number,
       swaysBackAndForthWhenCrawling: number,
      transfersObjectsFromOneHandToAnotherWhenSitting: number,
       retains2CubesOf25CmInOneHand: number,
     getsOnKnees: number,
     standsSupportingSelfOnSomething: number,
      usesPincerGripToPickUpObjects: number,
       crawls: number,
      whileCrawlingExtendsOneHandUpwards: number,
       standsWithMinimumSupport: number,
     licksFoodAroundMouth: number,
      maintainsSelfStandingAloneFor1Minute: number,
      knocksDownAnObjectThatIsInsideAReceptacle: number,
      turnsSeveralPagesOfABookAtTheSameTime: number,
       scoopsWithASpoonOrSpade: number,
      placesSmallObjectsInsideAReceptacle: number,
     whileStandingLowersItselfAndSits: number,
    clapsHands: number,
       walksWithMinimumSupport: number,
     takesAFewStepsWithoutSupport: number
      }
      export interface IMotorDevelopment1To2Years {
      climbsStairsCrawling: number,
     placesItselfStandingWhileSitting: number,
     rollsABallImitatingAnAdult: number,
    climbsOntoAnAdultChairTurnsAndSits: number,
     puts4RingsOnASmallStake: number,
    removes25CmPinsFromABoardOrTray: number,
      fits25CmPinsIntoAFittingBoard: number,
       buildsATowerOf3Blocks: number,
      makesTracesOnPaperWithPencilOrCrayon: number,
       walksAlone: number,
     goesDownStairsSittingPuttingFeetFirst: number,
     sitsInASmallChair: number,
    crouchesAndReturnsToStand: number,
       pushesAndPullsToysWhenWalking: number,
    usesAChairOrRockingHorse: number,
     climbsStairsWithHelp: number,
      bendsTheBodyWithoutFallingToPickUpObjectsOnTheFloor: number,
    imitatesACircularMovement: number
      }
      export interface IMotorDevelopment2To3Years {
        threads4LargeBeadsOnACordIn2Minutes: number,
    turnsLatchesOrDoorknobsOnDoors: number,
      jumpsInTheSamePlaceWithBothFeet: number,
      walksBackwards: number,
    goesDownStairsWithoutHelp: number,
       throwsABallToAnAdultAtA1HalfDistance: number,
    buildsATowerOf5To6Blocks:number,
   turnsPagesOfABookOneAtATime:number,
    unwrapsASmallObject:number,
    foldsAPaperInHalfImitatingAnAdult:number,
     dismantlesAndRebuildsPressureFitToys:number,
     unscrewsToysThatFitWithThreads:number,
      kicksALargeBallThatIsStill:number,
     makesBallsOfClayMudOrPlasticine:number,
    holdsThePencilBetweenTheThumbAndIndexFingerRestingItOnTheMiddleFinger:number,
      doesForwardTumbleWithHelp:number,
   hammersToFit5PinsInTheirHoles:number
    }
    export interface IMotorDevelopment3To4Years {
       makesAPuzzleOf3Pieces:number,
      cutsSomethingIntoPiecesWithScissors:number,
       jumpsFromAHeightOf20Cm:number,
      kicksALargeBallWhenSentToYou:number,
      walksOnTiptoes:number,
    runs10StepsCoordinatingAndAlternatingTheMovementOfArmsAndFeet:number,
    pedalsWithTricycleTheDistanceOf1AndAHalfMeters:number,
     swingsOnASwingWhenItIsInMotion:number,
      climbsOnASlideOf120MTo180MAndSlidesDown:number,
    doesForwardTumbles:number,
     climbsStairsAlternatingFeet:number,
    marchesWalksInARhythmicalWay:number,
    parriesTheBallWithBothHands:number,
    drawsFiguresFollowingOutlinesOrDottedLines:number,
     cutsAlongAStraightLine20CmMovingSlightlyAwayFromTheLine:number

    }
    export interface IMotorDevelopment4To5Years {
    standsOnOneFootWithoutSupportFor4To8Seconds:number,
    changesDirectionWhenRunning:number,
      walksOnABeamOrBoardMaintainingBalance:number,
   jumpsForward10TimesWithoutFalling:number,
     jumpsOverARopeSuspended5CmFromTheGround:number,
   jumpsBackwards6Times:number,
  reboundsAndCatchesALargeBall:number,
    joins2To3PiecesOfPlasticine:number,
    cutsAroundCurvedLines:number,
    fitsScrewObjects:number,
     goesDownStairsAlternatingFeet:number,
   pedalsATricycleMakingTurns:number,
   jumpsOnOneFoot5ConsecutiveTimes:number,
    cutsACircleIn5Cm:number,
  drawsSimpleEasilyIdentifiableFiguresExHouse:number,
   cutsAndPastesSimpleShapes:number
    }
    export interface IMotorDevelopment5To6Years {
      writesUppercaseLettersIsolatedAndLargeAnywhereOnThePaper:number,
      walksOnABoardBackwardsForwardsAndSidewaysMaintainingBalance:number,
   walksWhileHopping:number,
   swingsOnASwingStartingAndMaintainingTheMovement:number,
   stretchesFingersTouchingThumbToEachOfThem:number,
   copiesCapitalLetters:number,
   climbsOnLaddersOrASlideOf3M:number,
  hammersANailWithAHammer:number,
      reboundsTheBallAsItWalksWithDirection:number,
    managesToColorWithoutGoingOutOfTheMargin95PercentOfTheTime:number,
     cutsOutFiguresWithoutLeavingMoreThan6MmFromTheMargin:number,
    usesPencilSharpener:number,
   copiesComplexDrawingsSchoolShip:number,
     tearsSimpleFiguresFromThePaper:number,
      foldsASquarePaper2XDiagonallyByImitation:number,
  catchesALightBallWithOneHand:number,
     jumpsRopeAlone:number,
   strikesABallWithAStickOrPieceOfWood:number,
  catchesAnObjectOnTheFloorWhileRunning:number,
     skatesADistanceOf3MOrUsesASkateboard:number,
   ridesABicycle:number,
    slidesDownAHillOfSandOrEarth:number,
     walksOrPlaysInASwimmingPoolHavingWaterUpToItsWaist:number,
   drivesAScooterGivingImpulseWithOneFootOnly:number,
   jumpsAndTurnsOnOneFoot:number,
  writesOwnNameWithBlockLettersInLinedNotebook:number,
      jumpsFromAHeightOf30CmAndFallsOnTiptoes:number,
     stopsOnOneFootWithoutSupportWithEyesClosedFor10Seconds:number,
  hangsFor10SecondsOnAHorizontalBar:number
    }

export interface IPgpse {
  socialization0To1Year: ISocialization0To1Year,
  socialization1To2Years: ISocialization1To2Years,
  socialization2To3Years: ISocialization2To3Years,
  socialization3To4Years: ISocialization3To4Years,
  socialization4To5Years: ISocialization4To5Years,
  socialization5To6Years: ISocialization5To6Years,
  language0To1Years: ILanguage0To1Years,
  language1To2Years: ILanguage1To2Years,
  language2To3Years: ILanguage2To3Years,
  language3To4Years: ILanguage3To4Years,
  language4To5Years: ILanguage4To5Years,
  language5To6Years: ILanguage5To6Years,
  cognition0To1Year: ICognition0To1Year,
  cognition1To2Years: ICognition1To2Years,
  cognition2To3Years: ICognition2To3Years,
  cognition3To4Years: ICognition3To4Years,
  cognition4To5Years: ICognition4To5Years,
  cognition5To6Years: ICognition5To6Years,
  selfCare0To1Year: ISelfCare0To1Year,
  selfCare1To2Years: ISelfCare1To2Years,
  selfCare2To3Years: ISelfCare2To3Years,
  selfCare3To4Years: ISelfCare3To4Years,
  selfCare4To5Years: ISelfCare4To5Years,
  selfCare5To6Years: ISelfCare5To6Years,
  motorDevelopment0To1Year: IMotorDevelopment0To1Year,
  motorDevelopment1To2Years: IMotorDevelopment1To2Years,
  motorDevelopment2To3Years: IMotorDevelopment2To3Years,
  motorDevelopment3To4Years: IMotorDevelopment3To4Years,
  motorDevelopment4To5Years: IMotorDevelopment4To5Years,
}
