export interface ISocialization0To1Year {
  observesAPersonMovingInTheirVisualField: boolean,
  smilesInResponseToAdultAttention: boolean,
  vocalizesInResponseToAttention: boolean,
  looksAtOwnHandSmilingOrVocalizing: boolean,
  respondsToFamilyCircleSmilingVocalizingOrStoppingCrying: boolean,
  smilesInResponseToOthersFacialExpressions: boolean,
  smilesAndVocalizesWhenSeeingImageInMirror: boolean,
  caressesOrTouchesAdultsFacesPullsHairNoseGlassesEtc: boolean,
  reachesTowardsAnOfferedObject: boolean,
  reachesArmsTowardsFamilyMembers: boolean,
  extendsHandAndTouchesOwnReflectedImageInMirror: boolean,
  holdsAndExaminesGivenObjectFor1Minute: boolean,
  shakesOrSqueezesAnObjectPlacedInHandProducingInvoluntarySounds: boolean,
  playsAloneFor10Minutes: boolean,
  seeksEyeContactWhenSomeonePaysAttentionFor2To3Minutes: boolean,
  playsAloneWithoutComplainingFor15To20MinutesNearAnAdult: boolean,
  vocalizesToGetAttention: boolean,
  imitatesAdultInPeekABooGames: boolean,
  clapsHandsImitatingAnAdult: boolean,
  wavesHandImitatingAnAdult: boolean,
  raisesArmsToExpressBigImitatingAnAdult: boolean,
  offersSomethingButDoesNotAlwaysDeliver: boolean,
  hugsCaressesAndKissesFamilyMembers: boolean,
  respondsToOwnNameLookingOrExtendingArmToBePickedUp: boolean,
  squeezesOrShakesToyToProduceSoundsInImitation: boolean,
  manipulatesToyOrObject: boolean,
  extendsAToyOrObjectToAnAdultAndDeliversIt: boolean,
  imitatesMovementsOfOtherChildrenWhilePlaying: boolean
}

export interface ISocialization1To2Years {
  imitatesAnAdultInASimpleTask: boolean,
  playsNextToAnotherChildEachPerformingDifferentTasks: boolean,
  takesPartInAPlayWithAnotherChildFor2To5Minutes: boolean,
  acceptsParentsAbsenceAlthoughMayComplain: boolean,
  activelyExploresItsEnvironment: boolean,
  performsManipulativeActivityWithAnotherPerson: boolean,
  hugsAndCarriesADollOrSoftToy: boolean,
  repeatsActionsThatProduceLaughterAndAttention: boolean,
  givesABookForAnAdultToReadOrForBothToShare: boolean,
  pullsAPersonToShowThemSomething: boolean,
  withdrawsHandOrSaysNoWhenNearForbiddenObjectAndSomeoneRemindsIt: boolean,
  whenPlacedInChairOrChangingTableWaitsToBeAttended: boolean,
  playsWith2Or3ChildrenOfSameAge: boolean,
  sharesAnObjectOrFoodWithAnotherChild: boolean,
  greetsPeersOrAdultsWhenReminded: boolean
}

export interface ISocialization2To3Years {
  obeysParentsOrdersAtLeastHalfTheTime: boolean,
  seeksOrTakesAnObjectOrPersonWhenAsked: boolean,
  paysAttentionToStoryOrMusicFor5To10Minutes: boolean,
  saysPleaseOrThankYouWhenReminded: boolean,
  triesToHelpParentsPerformTasksByDoingPartOfIt: boolean,
  playsAtWearingAdultsClothes: boolean,
  makesAChoiceWhenAsked: boolean,
  demonstratesUnderstandingOfFeelingsExpressingThem: boolean
}

export interface ISocialization3To4Years {
  singsAndDancesWhenHearingMusic: boolean,
  followsRulesOfAGameImitatingActionsOfOtherChildren: boolean,
  greetsFamilyMembersWithoutBeingReminded: boolean,
  followsRulesInGroupGamesDirectedByAdults: boolean,
  asksPermissionToPlayWithAToyBeingUsedByAnotherChild: boolean,
  saysPleaseAndThankYouWithoutBeingRemindedHalfTheTime: boolean,
  answersThePhoneCallingAnAdultAndSpeakingWithFamilyMembers: boolean,
  waitsItsTurn: boolean,
  followsRulesInGamesDirectedByAnOlderChild: boolean,
  obeysAdultsOrders75PercentOfTheTime: boolean,
  staysInItsOwnYardOrGarden: boolean,
  playsNearOtherChildrenTalkingToThemWhileWorkingOnOwnProject30Minutes: boolean
}

export interface ISocialization4To5Years {
  asksForHelpWhenHavingDifficulties: boolean,
  contributesToAdultConversation: boolean,
  repeatsRhymesSongsOrDancesForOthers: boolean,
  doesATaskAloneFor20To30Minutes: boolean,
  apologizesWithoutBeingReminded75PercentOfTheTime: boolean,
  waitsItsTurnInPlayInvolving8To9children: boolean,
  playsWith2To3ChildrenFor20MinutesInAnActivityInvolvingCooperation: boolean,
  whenInPublicPresentsASociallyAcceptableBehavior: boolean,
  asksPermissionToUseOthersObjects75PercentOfTheTime: boolean
}

export interface ISocialization5To6Years {
  expressesItsFeelings: boolean,
  playsWith4To5ChildrenInCooperativeActivityFor20MinutesWithoutSupervision: boolean,
  explainsToOthersTheRulesOfTheGameOrActivity: boolean,
  imitatesAdultRoles: boolean,
  collaboratesInConversationDuringMeals: boolean,
  followsRulesOfAGameInvolvingVerbalReasoning: boolean,
  comfortsPeersWhenTheyAreSad: boolean,
  choosesItsOwnFriends: boolean,
  plansAndBuildsUsingSimpleTools: boolean,
  setsGoalsForItselfAndPerformsActivityToAchieveThem: boolean,
  dramatizesExcerptsFromStoriesPlayingARoleOrUsingPuppets: boolean
}

export interface ILanguage0To1Years {
  repeatsSoundsMadeByOtherPeople: boolean,
  repeatsSameSyllable2To3Times: boolean,
  respondsToGesturesWithGestures: boolean,
  obeysASimpleOrderWhenAccompaniedByIndicativeGestures: boolean,
  interruptsActivityWhenToldNo75PercentOfTheTime: boolean,
  respondsToSimpleQuestionsWithNonVerbalAnswers: boolean,
  combines2DifferentSyllablesWhenTryingToVerbalize: boolean,
  imitatesIntonationPatternsOfOthersVoice: boolean,
  usesAWordFunctionallyToIndicateObjectsOrPeople: boolean,
  vocalizesInResponseToOtherPeoplesSpeech: boolean
}

export interface ILanguage1To2Years {
  says5DifferentWords: boolean,
  asksForMore: boolean,
  saysDone: boolean,
  obeys3DifferentOrdersThatAreNotAccompaniedByIndicativeGestures: boolean,
  managesToGiveOrShowWhenAsked: boolean,
  pointsTo12ObjectsWhenNamed: boolean,
  pointsTo3To5FiguresInABook: boolean,
  pointsTo3PartsOfOwnBody: boolean,
  saysOwnNameOrNicknameWhenAsked: boolean,
  respondsToTheQuestionWhatIsThis: boolean,
  combinesWordsAndGesturesToExpressWishes: boolean,
  names5FamilyMembersIncludingAnimals: boolean,
  names4Toys: boolean,
  producesAnimalSoundsOrNamesThemByTheSound: boolean,
  asksForKnownFoodsByNameWhenShown: boolean,
  asksQuestionsVaryingIntonationOfVoice: boolean,
  names3BodyPartsOnADollOrAnotherPerson: boolean,
  respondsToYesNoQuestions: boolean
}

export interface ILanguage2To3Years {
  combinesNounsOrAdjectivesAndNounsIn2WordSentences: boolean,
  combinesNounAndVerbIn2WordSentences: boolean,
  usesAWordToIndicateThatWantsToGoToTheBathroom: boolean,
  combinesVerbOrNounWithThereAndHereIn2WordSentences: boolean,
  combines2WordsToExpressPossession: boolean,
  usesNoInSpeech: boolean,
  respondsToTheQuestionWhatIsDoingForHabitualActivity: boolean,
  respondsToQuestionsLikeWhereIsObject: boolean,
  namesFamiliarEnvironmentalSounds: boolean,
  givesMoreThanOneObjectWhenUsingThePluralFormInTheRequest: boolean,
  whenSpeakingRefersToItselfByName: boolean,
  pointsToFiguresOfCommonObjectsDescribedByUseUpTo10WhatIsUsedToEatSpoon: boolean,
  showsAgeByFingers: boolean,
  saysSexWhenAsked: boolean,
  obeysTheSequenceOfTwoRelatedOrders: boolean,
  usesTheVerbFormInTheGerund: boolean,
  employsRegularPluralForms: boolean,
  employsSomeIrregularFormsOfVerbsInThePastSystematically: boolean,
  asksQuestionsLikeWhatIsThis: boolean,
  controlsVolumeOfVoice90PercentOfTheTime: boolean,
  usesThisAndThatInSpeech: boolean,
  employsIsAndIsLocatedInSimpleSentences: boolean,
  saysIMeMineInsteadOfOwnName: boolean,
  pointsToObjectsAndSaysTheyAreNotOtherThings: boolean,
  respondsToTheQuestionWhoGivingAName: boolean,
  employsPossessiveFormsOfNouns: boolean,
  usesArticlesWhenSpeaking: boolean,
  usesNounsThatIndicateAGroupOrCategory: boolean,
  usesTheVerbsToBeToExistAndToHaveInThePresentWithFewErrors: boolean,
  saysIfObjectsAreOpenOrClosed: boolean
}

export interface ILanguage3To4Years {
  expressesDiminutivesAndAugmentativesWhenSpeaking: boolean,
  paysAttentionFor5MinutesToAReadStory: boolean,
  obeysSequenceOf2UnrelatedOrders: boolean,
  saysFullNameWhenAsked: boolean,
  respondsSimpleQuestionsInvolvingHow: boolean,
  employsRegularVerbsInThePast: boolean,
  reportsImmediateExperiences: boolean,
  saysHowCommonObjectsAreUsed: boolean,
  expressesFutureActionsUsingVerbsToGoToHaveAndToWant: boolean,
  usesMasculineAndFeminineAppropriatelyInSpeech: boolean,
  usesImperativeFormsOfVerbsWhenAskingForFavors: boolean,
  tells2FactsInOrderOfOccurrence: boolean
}

export interface ILanguage4To5Years {
  obeysASequenceInvolving3Orders: boolean,
  demonstratesUnderstandingOfReflexiveVerbsUsingThemOccasionallyExHeGotHurt: boolean,
  managesToIdentifyObjectsFiguresThatFormAPairUponRequest: boolean,
  employsFutureWhenSpeaking: boolean,
  usesSentencesComposedByCoordination: boolean,
  managesToIdentifyTheTopAndBottomPartOfObjectsWhenRequested: boolean,
  employsOccasionallyTheConditionalWhenSpeakingCouldWouldCouldWouldMake: boolean,
  managesToIdentifyAbsurditiesInFigures: boolean,
  employsTheFollowingWordsBrotherSisterGrandmotherGrandfather: boolean,
  completesSentencesWithAntonyms: boolean,
  tellsAKnownStoryWithoutHelpOfFigures: boolean,
  inAFigureNamesTheObjectThatDoesNotBelongToACertainCategory: boolean,
  saysIfTwoWordsRhymeOrNot: boolean,
  usesComplexSentencesComposedBySubordination: boolean,
  saysIfASoundIsLoudOrSoft: boolean
}

export interface ILanguage5To6Years {
  managesToIndicateSomeManyAndSeveralElements: boolean,
  saysOwnAddress: boolean,
  saysOwnPhoneNumber: boolean,
  pointsToTheSetThatHasMoreLessOrFewElements: boolean,
  tellsSimpleJokes: boolean,
  reportsDailyExperiences: boolean,
  describesALocationOrMovementThroughOrBetweenAwayFromFromSinceToOverUpTo: boolean,
  answersTheQuestionWhyWithAnExplanation: boolean,
  ordersAndTellsAStoryOf2To5EpisodesInTheCorrectSequence: boolean,
  definesWords: boolean,
  respondsAppropriatelyToTheQuestionWhatIsTheOppositeOf: boolean,
  respondsToTheQuestionWhatHappensIf: boolean,
  usesYesterdayAndTomorrowCorrectly: boolean,
  asksTheMeaningOfNewOrKnownQuestions: boolean
}

export interface ICognition0To1Year {
  removesAClothFromFaceThatObscuresVision: boolean,
  looksForObjectThatHasBeenRemovedFromItsVisualField: boolean,
  removesAnObjectFromAReceptacleByPuttingHandInsideIt: boolean,
  placesAnObjectInAReceptacleImitatingAnAdult: boolean,
  placesAnObjectInAReceptacleWhenGivenInstructions: boolean,
  shakesAToyThatProducesSoundHangingFromAString: boolean,
  placesThreeObjectsInAReceptacleAndEmptiesIt: boolean,
  transfersAnObjectFromOneHandToAnotherToPickUpAnotherObject: boolean,
  dropsAndPicksUpAToy: boolean,
  discoversAnObjectHiddenUnderAReceptacle: boolean,
  pushes3BlocksAsIfItWereATrain: boolean,
  removesACircleFromABoardByImitation: boolean,
  placesARoundPinInAPinBoardWhenRequested: boolean,
  performsSimpleGesturesWhenRequested: boolean
}

export interface ICognition1To2Years {
  removes6ObjectsFromAReceptacleOneAtATime: boolean,
  pointsToAPartOfTheBody: boolean,
  stacks3BlocksGivenTheOrder: boolean,
  matchesSimilarObjects: boolean,
  scribblesOnPaper: boolean,
  pointsToItselfWhenAskedWhereIsName: boolean,
  places5RoundPinsGivenTheOrder: boolean,
  matchesObjectsWithTheFigureOfTheSameName: boolean,
  pointsToTheNamedFigure: boolean,
  turnsThePagesOfABook23AtATimeToFindTheNamedFigure: boolean
}

export interface ICognition2To3Years {
  findsACertainBookWhenRequested: boolean,
  completesA3PieceJigsawPuzzle: boolean,
  names4CommonObjectsInFigures: boolean,
  drawsAVerticalLineImitatingAnAdult: boolean,
  drawsAHorizontalLineImitatingAnAdult: boolean,
  copiesACircle: boolean,
  matchesObjectsWithTheSameTexture: boolean,
  pointsToSmallAndBigWhenRequested: boolean,
  drawsAPlusSignImitatingAnAdult: boolean,
  matches3Colors: boolean,
  placesObjectsInsideOnTop 
  andUnderAReceptacleGivenTheOrder: boolean,
  namesObjectsWhenHearsTheNoiseTheyMake: boolean,
  mountsA4PieceFittingToy: boolean,
  namesActionsInFiguresWhatIsDoing: boolean,
  matchesGeometricShapeWithTheFigureOfTheSame: boolean,
  stacks5OrMoreRingsOnARodInOrder: boolean
}

export interface ICognition3To4Years {
  namesObjectsAsBeingBigOrSmall: boolean,
  pointsTo10PartsOfTheBodyWhenRequested: boolean,
  pointsToBoyAndGirlGivenTheOrder: boolean,
  saysIfAnObjectIsHeavyOrLight: boolean,
  unites2PartsOfAFigureToFormTheWhole: boolean,
  describes2EventsOrCharactersFromAFamiliarStoryOrTvProgram: boolean,
  repeatsGamesRhymesOrSongsThatInvolveCoordinatedMovements: boolean,
  matches3OrMoreObjects: boolean,
  pointsToLongOrShortObjects: boolean,
  associatesCorrespondingObjectsExSockShoe: boolean,
  countsUpTo3ImitatingAnAdult: boolean,
  groupsObjectsIntoCategories: boolean,
  tracesAVInImitation: boolean,
  tracesADiagonalLineGivenTheExample: boolean,
  countsUpTo10ObjectsImitatingAnAdult: boolean,
  buildsABridgeWith3BlocksByImitation: boolean,
  matchesASequenceOrPatternSizeColorOfBlocksOrBeads: boolean,
  copiesASeriesOfInterconnectedV: boolean,
  addsALegOrArmToAnIncompleteDrawingOfTheHumanFigure: boolean,
  completesA6PiecePuzzle: boolean,
  indicatesIfObjectsAreEqualOrDifferent: boolean,
  drawsASquareImitatingAnAdult: boolean,
  names3ColorsBeingRequested: boolean,
  names3GeometricShapesSquareTriangleAndCircle: boolean
}

export interface ICognition4To5Years {
  picksUpFrom1To5ObjectsWhenRequested: boolean,
  names5DifferentTextures: boolean,
  copiesATriangleWhenRequested: boolean,
  remembers4ObjectsThatHadBeenSeenInAFigure: boolean,
  saysTheTimeOfTheDayAssociatedWithEachActivity: boolean,
  repeatsFamiliarRhymes: boolean,
  saysIfAnObjectIsHeavierOrLighterObjectsWithADifferenceOf05Kilo: boolean,
  saysWhatIsMissingWhenAnObjectIsRemovedFromAGroupOf3Objects: boolean,
  names8Colors: boolean,
  identifiesTheValueOf3Coins: boolean,
  matchesSymbolsLettersAndNumbers: boolean,
  saysTheColorOfNamedObjects: boolean,
  reports5MainFactsOfAStoryTold3Times: boolean,
  drawsHumanFigureHeadTorsoAnd4Limbs: boolean,
  sings5VersesOfASong: boolean,
  buildsAPyramidOf10BlocksByImitation: boolean,
  namesObjectsAsBeingLongOrShort: boolean,
  placesObjectsBehindBesideOrNextToOthers: boolean,
  makesEqualSetsOf10ObjectsAccordingToModel: boolean,
  namesOrPointsToTheMissingPartOfTheFigure: boolean,
  countsFrom1To20: boolean,
  identifiesTheObjectThatIsPlacedInTheMiddleInFirstAndLastPlace: boolean
}

export interface ICognition5To6Years {
  countsUpTo20ObjectsAndAnswersAppropriatelyToTheQuestionHowManyDidYouCount: boolean,
  names10Numerals: boolean,
  identifiesWhichIsItsLeftAndWhichIsItsRight: boolean,
  saysTheVowelsInOrder: boolean,
  writesOwnNameWithBlockLetters: boolean,
  names5LettersOfTheAlphabet: boolean,
  ordersObjectsInSequenceOfLengthAndWidth: boolean,
  namesTheUppercaseLettersOfTheAlphabet: boolean,
  placesNumeralsFrom1To10InTheCorrectSequence: boolean,
  identifiesThePositionOfObjectsInFirstSecondAndThirdPlace: boolean,
  namesTheLowercaseLettersOfTheAlphabet: boolean,
  matchesUppercaseLettersWithLowercaseOnes: boolean,
  pointsToNumeralsFrom1To25: boolean,
  copiesARhombus: boolean,
  completesASimpleLabyrinth: boolean,
  saysTheDaysOfTheWeekInOrder: boolean,
  addsAndSubtractsCombinationsOfUpTo3Elements: boolean,
  saysTheMonthAndDayOfOwnBirthday: boolean,
  reads10PrintedWords: boolean,
  predictsWhatWillOccur: boolean,
  pointsToWholeAndHalfObjects: boolean,
  countsFromMemoryFrom1To100AskToStopAt40AndContinueAt80IfNoErrorsUntil40: boolean
}

export interface ISelfCare0To1Year {
  sucksAndSwallowsLiquids: boolean,
  eatsPorridgeOrSoup: boolean,
  extendsHandsTowardsBabyBottleTryingToGrabIt : boolean,
  eatsPureedFoodsGivenByParents: boolean,
  holdsBabyBottleWithoutHelpWhileDrinking: boolean,
  bringsBottleToMouthOrRefusesItPushingItAway: boolean,
  eatsMashedFoodsGivenByParents: boolean,
  drinksFromAMugHeldByParents: boolean,
  eatsSemisolidFoodsGivenByParents: boolean,
  feedsItselfUsingFingers: boolean,
  holdsTheMugWithBothHandsAndDrinks: boolean,
  bringsASpoonFullOfFoodToMouthWithHelp: boolean,
  stretchesArmsAndLegsWhenBeingDressed: boolean
}

export interface ISelfCare1To2Years {
  eatsWithSpoonIndependently: boolean,
  holdsMugWithOneHandAndDrinks: boolean,
  putsHandInWaterAndPatsFaceWithWetHandsImitatingSomeone: boolean,
  sitsOnAPottyOrChildsToiletFor5Minutes: boolean,
  putsAHatOnHeadAndRemovesIt: boolean,
  takesOffSocks: boolean,
  pushesArmsThroughSleevesAndFeetThroughTrouserLegs: boolean,
  takesOffShoesWhenLacesAreUntied: boolean,
  takesOffCoatWhenUnbuttoned: boolean,
  takesOffTrousersWhenUnbuttoned: boolean,
  pullsALargeZipperUpAndDown: boolean,
  usesWordsOrGesturesIndicatingNeedToGoToTheBathroom: boolean
}

export interface ISelfCare2To3Years {
  eatsAloneUsingSpoonOrMugSpillingALittleFoodOrLiquid: boolean,
  whenGivenATowelDriesHandsAndFaceWithHelp: boolean,
  sucksLiquidFromTheGlassOrMugUsingAStraw: boolean,
  takesForkfuls: boolean,
  chewsAndSwallowsOnlyEdibleSubstances: boolean,
  driesHandsWithoutHelpWhenGivenATowel: boolean,
  warnsThatWantsToGoToTheBathroomEvenIfItIsTooLate: boolean,
  controlsOwnDrool: boolean,
  urinatesOrDefecatesWhenPlacedInPottyAtLeast3TimesAWeek: boolean,
  putsOnShoes: boolean,
  brushesTeethImitatingAnAdult: boolean,
  removesSimpleClothesThatHaveBeenUnbuttoned: boolean,
  usesTheBathroomToDefecateFailsOnlyOnceAWeek: boolean,
  obtainsWaterFromAFaucetWithoutHelp: boolean,
  washesHandsAndFaceWithSoap: boolean,
  warnsThatWantsToGoToTheBathroomDuringTheDayInTime: boolean,
  hangsCoatOnAHookAtItsOwnHeight: boolean,
  staysDryWhenSleepingDuringTheDay: boolean,
  avoidsRisksExSharpEdgesOnFurnitureAndStairsWithoutHandrail: boolean,
  usesANapkinWhenRecommended: boolean,
  piercesTheForkInTheFoodTakingItToTheMouth: boolean,
  poursLiquidFromASmallPitcherIntoAGlassWithoutHelp: boolean,
  unfastensClothesFastenedWithASnapFastener: boolean,
  washesArmsAndLegsWhenGivenABath: boolean,
  putsOnSocks: boolean,
  wearsCoatJacketOrShirt: boolean,
  identifiesTheFrontPartOfClothes: boolean
}

export interface ISelfCare3To4Years {
  feedsItselfAloneForEntireMeal: boolean,
  dressesItselfAloneNeedingHelpOnlyWhenThereAreJacketsOrTShirtsWithClosedCollarsOrButtonsAndFasteners: boolean,
  wipesNoseWhenReminded: boolean,
  wakesUpDry2MorningsAWeek: boolean,
  ifBoyUrinatesInTheToiletWhileStanding: boolean,
  dressesAndUndressesItselfAloneExceptForButtonsAndFasteners75PercentOfTheTime: boolean,
  fastensClothesWithSnapsOrHooks: boolean,
  blowsNoseWhenReminded: boolean,
  avoidsCommonDangersExBrokenGlass: boolean,
  hangsClothesOnAHangerAndPutsInClosetWhenAsked: boolean,
  brushesTeethWhenReceivesInstruction: boolean,
  putsOnGloves: boolean,
  putsOnBoots: boolean,
  unbuttonsLargeButtons: boolean,
  buttonsLargeButtons: boolean
}

export interface ISelfCare4To5Years {
  cleansWhatItSpilledOnOwn: boolean,
  avoidsPoisonAndAllHarmfulSubstances: boolean,
  unbuttonsOwnClothes: boolean,
  buttonsOwnClothes: boolean,
  removesPlateAndCutleryFromTheTable: boolean,
  fitsZipperIntoItsTermination: boolean,
  washesHandsAndFace: boolean,
  usesAppropriateCutleryToEat: boolean,
  wakesUpAtnighttogotothebathroomorwakesupdry: boolean,
  cleansAndBlowsItsNose75PercentOfTheTimeWithoutBeingReminded: boolean,
  bathesAloneNeedingHelpOnlyToWashBackNeckAndEars: boolean,
  usesAKnifeToSpreadButterOnBread: boolean,
  tightensAndLoosensBeltsOrBuckles: boolean,
  dressesItselfAloneButDoesNotTieLaces: boolean,
  servesItselfAtTheTableWhileHoldingTheFoodPlatter: boolean,
  helpsSetTheTableCorrectlyWhenReceivesInstructions: boolean,
  brushesTeeth: boolean,
  goesToTheBathroomInTimeRemovesClothesUsesToiletPaperFlushesAndDressesWithoutHelp: boolean,
  combsOrBrushesHair: boolean,
  hangsClothesOnHangers: boolean,
  walksAroundTheNeighborhoodWithoutConstantSupervision: boolean,
  threadsLacesIntoShoes: boolean,
  tiesOrLacesShoelaces: boolean
}

export interface ISelfCare5To6Years {
  isResponsibleForAWeeklyTaskAndPerformsItWhenReminded: boolean,
  selectsAppropriateClothingForClimateAndOccasion: boolean,
  stopsOnTheSidewalkLooksBothWaysAndCrossesTheStreetWithoutNeedingToBeReminded: boolean,
  servesItselfAtTheTableAndPassesThePotOfFoodToOthers: boolean,
  preparesOwnCupOfCoffeeWithMilk: boolean,
  isResponsibleForADailyTaskAtHome: boolean,
  adjustsTheTemperatureOfWaterForBathing: boolean,
  preparesOwnSnack: boolean,
  walksAloneUpToADistanceOf2BlocksFromHome: boolean,
  cutsTenderFoodsWithAKnife: boolean,
  findsTheBathroomInAPublicPlaceCorrectly: boolean,
  opensTheMilkPackage: boolean,
  picksUpATrayWithFoodCarryingItAndPlacingItOnTheTable: boolean,
  tiesTheLacesOnJacketsWithHood: boolean,
  fastensTheCarSeatBelt: boolean
}

export interface IMotorDevelopment0To1Year {
  reachesForAnObjectPlacedInFrontOfIt15To20Cm: boolean,
  grabsAnObjectPlacedInFrontOfIt8Cm: boolean,
  extendsArmsTowardAnObjectInFrontOfItAndGrabsIt: boolean,
  reachesForAPreferredObject: boolean,
  putsObjectsInMouth: boolean,
  raisesHeadAndTorsoSupportingSelfOnArmsWhenLyingOnStomach: boolean,
  raisesHeadAndTorsoSupportingSelfOnOneArm: boolean,
  touchesAndExploresObjectsWithMouth: boolean,
  inPronePositionTurnsToTheSideAndMaintainsThisPositionHalfTheTime: boolean,
  inPronePositionTurnsOnBack: boolean,
  inPronePositionMovesForwardTheEquivalentOfItsHeight: boolean,
  inSupinePositionRollsToTheSide: boolean,
  inSupinePositionTurnsFromStomachToBack: boolean,
  makesEffortToSitHoldingOntoAdultsFingers: boolean,
  turnsHeadEasilyWhenTheBodyIsSupported: boolean,
  sitsFor2Minutes: boolean,
  releasesAnObjectToGrabAnother: boolean,
  grabsAndDropsAnObjectPurposefully: boolean,
  standsWithMaximumSupport: boolean,
  whileStandingWithSupportJumpsUpAndDown: boolean,
  crawlsToGrabAnObjectDistantItsHeight: boolean,
  sitsSupportingSelfAlone: boolean,
  whileSittingTurnsToCrawling: boolean,
  whileInPronePositionManagesToSit: boolean,
  sitsWithoutHandSupport: boolean,
  throwsObjectsAtRandom: boolean,
  swaysBackAndForthWhenCrawling: boolean,
  transfersObjectsFromOneHandToAnotherWhenSitting: boolean,
  retains2CubesOf25CmInOneHand: boolean,
  getsOnKnees: boolean,
  standsSupportingSelfOnSomething: boolean,
  usesPincerGripToPickUpObjects: boolean,
  crawls: boolean,
  whileCrawlingExtendsOneHandUpwards: boolean,
  standsWithMinimumSupport: boolean,
  licksFoodAroundMouth: boolean,
  maintainsSelfStandingAloneFor1Minute: boolean,
  knocksDownAnObjectThatIsInsideAReceptacle: boolean,
  turnsSeveralPagesOfABookAtTheSameTime: boolean,
  scoopsWithASpoonOrSpade: boolean,
  placesSmallObjectsInsideAReceptacle: boolean,
  whileStandingLowersItselfAndSits: boolean,
  clapsHands: boolean,
  walksWithMinimumSupport: boolean,
  takesAFewStepsWithoutSupport: boolean
}


export interface IMotorDevelopment1To2Years {
  climbsStairsCrawling: boolean,
  placesItselfStandingWhileSitting: boolean,
  rollsABallImitatingAnAdult: boolean,
  climbsOntoAnAdultChairTurnsAndSits: boolean,
  puts4RingsOnASmallStake: boolean,
  removes25CmPinsFromABoardOrTray: boolean,
  fits25CmPinsIntoAFittingBoard: boolean,
  buildsATowerOf3Blocks: boolean,
  makesTracesOnPaperWithPencilOrCrayon: boolean,
  walksAlone: boolean,
  goesDownStairsSittingPuttingFeetFirst: boolean,
  sitsInASmallChair: boolean,
  crouchesAndReturnsToStand: boolean,
  pushesAndPullsToysWhenWalking: boolean,
  usesAChairOrRockingHorse: boolean,
  climbsStairsWithHelp: boolean,
  bendsTheBodyWithoutFallingToPickUpObjectsOnTheFloor: boolean,
  imitatesACircularMovement: boolean
}

export interface IMotorDevelopment2To3Years {
  threads4LargeBeadsOnACordIn2Minutes: boolean,
  turnsLatchesOrDoorknobsOnDoors: boolean,
  jumpsInTheSamePlaceWithBothFeet: boolean,
  walksBackwards: boolean,
  goesDownStairsWithoutHelp: boolean,
  throwsABallToAnAdultAtA1HalfDistance: boolean,
  buildsATowerOf5To6Blocks: boolean,
  turnsPagesOfABookOneAtATime: boolean,
  unwrapsASmallObject: boolean,
  foldsAPaperInHalfImitatingAnAdult: boolean,
  dismantlesAndRebuildsPressureFitToys: boolean,
  unscrewsToysThatFitWithThreads: boolean,
  kicksALargeBallThatIsStill: boolean,
  makesBallsOfClayMudOrPlasticine: boolean,
  holdsThePencilBetweenTheThumbAndIndexFingerRestingItOnTheMiddleFinger: boolean,
  doesForwardTumbleWithHelp: boolean,
  hammersToFit5PinsInTheirHoles: boolean
}

export interface IMotorDevelopment3To4Years {
  makesAPuzzleOf3Pieces: boolean,
  cutsSomethingIntoPiecesWithScissors: boolean,
  jumpsFromAHeightOf20Cm: boolean,
  kicksALargeBallWhenSentToYou: boolean,
  walksOnTiptoes: boolean,
  runs10StepsCoordinatingAndAlternatingTheMovementOfArmsAndFeet: boolean,
  pedalsWithTricycleTheDistanceOf1AndAHalfMeters: boolean,
  swingsOnASwingWhenItIsInMotion: boolean,
  climbsOnASlideOf120MTo180MAndSlidesDown: boolean,
  doesForwardTumbles: boolean,
  climbsStairsAlternatingFeet: boolean,
  marchesWalksInARhythmicalWay: boolean,
  parriesTheBallWithBothHands: boolean,
  drawsFiguresFollowingOutlinesOrDottedLines: boolean,
  cutsAlongAStraightLine20CmMovingSlightlyAwayFromTheLine: boolean
}




export interface IMotorDevelopment4To5Years {
  standsOnOneFootWithoutSupportFor4To8Seconds: boolean,
  changesDirectionWhenRunning: boolean,
  walksOnABeamOrBoardMaintainingBalance: boolean,
  jumpsForward10TimesWithoutFalling: boolean,
  jumpsOverARopeSuspended5CmFromTheGround: boolean,
  jumpsBackwards6Times: boolean,
  reboundsAndCatchesALargeBall: boolean,
  joins2To3PiecesOfPlasticine: boolean,
  cutsAroundCurvedLines: boolean,
  fitsScrewObjects: boolean,
  goesDownStairsAlternatingFeet: boolean,
  pedalsATricycleMakingTurns: boolean,
  jumpsOnOneFoot5ConsecutiveTimes: boolean,
  cutsACircleIn5Cm: boolean,
  drawsSimpleEasilyIdentifiableFiguresExHouse: boolean,
  cutsAndPastesSimpleShapes: boolean
}

export interface IMotorDevelopment5To6Years {
  writesUppercaseLettersIsolatedAndLargeAnywhereOnThePaper: boolean,
  walksOnABoardBackwardsForwardsAndSidewaysMaintainingBalance: boolean,
  walksWhileHopping: boolean,
  swingsOnASwingStartingAndMaintainingTheMovement: boolean,
  stretchesFingersTouchingThumbToEachOfThem: boolean,
  copiesCapitalLetters: boolean,
  climbsOnLaddersOrASlideOf3M: boolean,
  hammersANailWithAHammer: boolean,
  reboundsTheBallAsItWalksWithDirection: boolean,
  managesToColorWithoutGoingOutOfTheMargin95PercentOfTheTime: boolean,
  cutsOutFiguresWithoutLeavingMoreThan6Mmfromthemargin: boolean,
  usesPencilSharpener: boolean,
  copiesComplexDrawingsSchoolShip: boolean,
  tearsSimpleFiguresFromThePaper: boolean,
  foldsASquarePaper2XDiagonallyByImitation: boolean,
  catchesALightBallWithOneHand: boolean,
  jumpsRopeAlone: boolean,
  strikesABallWithAStickOrPieceOfWood: boolean,
  catchesAnObjectOnTheFloorWhileRunning: boolean,
  skatesADistanceOf3MOrUsesASkateboard: boolean,
  ridesABicycle: boolean,
  slidesDownAHillOfSandOrEarth: boolean,
  walksOrPlaysInASwimmingPoolHavingWaterUpToItsWaist: boolean,
  drivesAScooterGivingImpulseWithOneFootOnly: boolean,
  jumpsAndTurnsOnOneFoot: boolean,
  writesOwnNameWithBlockLettersInLinedNotebook: boolean,
  jumpsFromAHeightOf30CmAndFallsOnTiptoes: boolean,
  stopsOnOneFootWithoutSupportWithEyesClosedFor10Seconds: boolean,
  hangsFor10SecondsOnAHorizontalBar: boolean
}


export interface IPgpse {
socialization0To1Year: ISocialization0To1Year,
socialization1To2Years: ISocialization1To2Years,
socialization2To3Years: ISocialization2To3Years,
socialization3To4Years: ISocialization3To4Years,
socialization4To5Years: ISocialization4To5Years,
socialization5To6Years: ISocialization5To6Years,
language0To1Years: ILanguage0To1Years,
language1To2Years: ILanguage1To2Years,
language2To3Years: ILanguage2To3Years,
language3To4Years: ILanguage3To4Years,
language4To5Years: ILanguage4To5Years,
language5To6Years: ILanguage5To6Years,
cognition0To1Year: ICognition0To1Year,
cognition1To2Years: ICognition1To2Years,
cognition2To3Years: ICognition2To3Years,
cognition3To4Years: ICognition3To4Years,
cognition4To5Years: ICognition4To5Years,
cognition5To6Years: ICognition5To6Years,
selfCare0To1Year: ISelfCare0To1Year,
selfCare1To2Years: ISelfCare1To2Years,
selfCare2To3Years: ISelfCare2To3Years,
selfCare3To4Years: ISelfCare3To4Years,
selfCare4To5Years: ISelfCare4To5Years,
selfCare5To6Years: ISelfCare5To6Years,
motorDevelopment0To1Year: IMotorDevelopment0To1Year,
motorDevelopment1To2Years: IMotorDevelopment1To2Years,
motorDevelopment2To3Years: IMotorDevelopment2To3Years,
motorDevelopment3To4Years: IMotorDevelopment3To4Years,
motorDevelopment4To5Years: IMotorDevelopment4To5Years,
motorDevelopment5To6Years: IMotorDevelopment5To6Years,
}