import { Schema, Document } from 'mongoose';
import { IAnamnesisForCerebralPalsy } from 'src/features/anamnesis-for-cerebral-palsy/types/anamneseForCerebralPalsy';

export const AnamneseCerebralSchema = new Schema({
  _id: { type: Schema.Types.ObjectId, required: true, auto: true },
  patient: { type: Schema.Types.ObjectId, required: true, ref: 'patient' },
  doctor: { type: Schema.Types.ObjectId, required: true, ref: 'doctor' },
  age: { type: Schema.Types.ObjectId, required: true, ref: 'patient' },
  bitrhDate: { type: Schema.Types.ObjectId, required: true, ref: 'patient' },
  date: { type: Date, required: true },

  gestationalHistory: {
    planning2WasDesiredOrNot: { type: String },
    howDidItTranspire: { type: String },
    relevantEvents: { type: String },
    useOfMedications: { type: String },
    generalPsychologicalState: { type: String },
    generalHealth: { type: String },
    childbirth: { type: String },
    birthGeneralConditions: { type: String },
    birthConditionsOfChild: { type: String },
    didTheBabyCryRightAway: { type: String },
    criedSoon: { type: String },
    coloration: { type: String },
    wasTheBabyInTheIncubator: { type: String },
    howLongAndWhyInIncubator: { type: String },
    didTheBabyHaveFeedingProblemsInitially: { type: String },
    whichFeedingProblems: { type: String },
    specialMedicalObservationsAndRecommendations: { type: String },
    childsReleaseTimeAfterBirth: { type: String },
    obsGestationalHistory: { type: String },
  },

  developmentMotor: {
    headControlPrevious: { type: String },
    headControlCurrent: { type: String },
    sittingPreviously: { type: String },
    sittingCurrently: { type: String },
    crawlingPrevious: { type: String },
    crawlingCurrently: { type: String },
    gettingOnAllFoursAndCrawlingPrevious: { type: String },
    gettingOnAllFoursAndCrawlingCurrently: { type: String },
    standingBalancePrevious: { type: String },
    standingBalanceCurrent: { type: String },
    walkingPrevious: { type: String },
    walkingCurrently: { type: String },
    coordinationOfMovementsInGrossAndFineMotorActivities: { type: String },
    conditionsOfSelfStimulationAndExplorationOfTheEnvironmentAndObjects: {
      type: String,
    },
  },
  foods: {
    feedingADevelopmentPrevious: { type: String },
    suckingHowDidTheFirstFeedingOccur: { type: String },
    explainHowTheLiquidFeedingWasGiven: { type: String },
    typeOfLiquidFeeding: { type: String },
    untilWhatTimeLiquidFeeding: { type: String },
    gagging: { type: String },
    nasalEscape: { type: String },
    vomiting: { type: String },
    coughing: { type: String },
    inWhatConditionsWasTheFeedingGiven: { type: String },
    howWasTheAcceptanceOfTheBottle: { type: String },
    typeOfNipple: { type: String },
    orifice: { type: String },
    doesItUseAStraw: { type: String },
    howWasTheUseOfCupsDone: { type: String },
    whenDidItStartEatingPastrySubstance: { type: String },
    whatWasUsedToGiveItsFood: { type: String },
    inWhatPositionWasTheChild: { type: String },
    whatWasThePassageFromThePastyToTheSolid: { type: String },
    blender: { type: String },
    sieve: { type: String },
    pastyFoodWithSemiSolidPieces: { type: String },
    whenDidItSwitchToSolidFoods: { type: String },
    howWasTheAcceptanceOfSolids: { type: String },
    howWasTheAcceptanceOfTheSalty: { type: String },
    howWasTheChewing: { type: String },
    andTheSwallowing: { type: String },
    difficultyInChewingSomeFoodWhich: { type: String },
    dentition: { type: String },
    useOfCup: { type: String },
    useOfStraw: { type: String },
    morning: { type: String },
    afternoon: { type: String },
    dinner: { type: String },
    whatDoYouLikeToEatTheMost: { type: String },
    whatDoYouNotLikeToEat: { type: String },
    doPiecesOfFoodAppearInTheFeces: { type: String },
    pacifierUseUntilWhen: { type: String },
    whatKindPacifier: { type: String },
    suckedFinger: { type: String },
    bitNails: { type: String },
    grittedTeeth: { type: String },
    drooling: { type: String },
    untilWhenDrooling: { type: String },
    staysWithTheMouthOpen: { type: String },
    sleepsWithTheMouthOpen: { type: String },
    hasRespiratoryProblems: { type: String },
    acceptedKissOnTheFace: { type: String },
    alwaysAccepted: { type: String },
    acceptedCaressesOnTheFace: { type: String },
    presentedThePhaseOfPuttingObjectsInTheMouth: { type: String },
    acceptedTeetherOrCheekToys: { type: String },
    getsIrritatedWithTheBeardOrFabricOnTheFace: { type: String },
    whatDoYouEatWith: { type: String },
    doesItEatAlone: { type: String },
    inWhatPositionIsSolidFoodGiven: { type: String },
    whenLikeToSuckOrChewFood: { type: String },
    doesTheTongueProjectWhileSwallowing: { type: String },
    hasDifficultyInChewingOrSwallowingAnything: { type: String },
    whatDifficultInChewingOrSwallowing: { type: String },
    takesTimeToChew: { type: String },
    leavesPiecesInTheMouthWithoutSwallowing: { type: String },
    whyLeavesPiecesInTheMouthWithoutSwallowing: { type: String },
    isThereFoodEscape: { type: String },
    isThereGagging: { type: String },
    isThereVomiting: { type: String },
    isThereNasalEscape: { type: String },
    chewsWithMouthOpen: { type: String },
    drinksTooMuchLiquidDuringMeals: { type: String },
    drinksTooMuchLiquidAfterHavingBittenSolid: { type: String },
    putsALargeAmountOfFoodInTheMouth: { type: String },
    doesTheChildEatTooFastOrSlow: { type: String },
    chewsWithCorrectJawMovement: { type: String },
    getsIrritatedWithGaseousLiquids: { type: String },
    vomitsEasily: { type: String },
    letsYouBrushYourTeeth: { type: String },
    withOrWithoutPaste: { type: String },
    otherObservations: { type: String },
  },
});

export interface IAnamneseCerebralEntity
  extends Omit<IAnamnesisForCerebralPalsy, '_id'>,
    Document {}
