import { Schema, Document } from 'mongoose';
import { IAnamnesisSpeechTherapy } from 'src/features/anamnesis-speech-therapy/types/anamnesisSpeechTherapy';

export const AnamnesisSpeechTherapySchema = new Schema({
  _id: { type: Schema.Types.ObjectId, required: true, auto: true },
  doctor: { type: Schema.Types.ObjectId, required: true, ref: 'User' },
  patient: { type: Schema.Types.ObjectId, required: true, ref: 'User' },
  date: { type: Date, default: Date.now },
  /*maritalStatus: { type: String },
  placeOfBirth: { type: String },
  age: { type: Number },
  sex: { type: String, enum: ['M', 'F'] },
  nationality: { type: Schema.Types.ObjectId, required: true, ref: 'User' },
  schoolName: { type: String },
  studyPeriod: { type: String },
  fatherName: { type: String },
  fatherAge: { type: Number },
  fatherProfession: { type: String },
  fatherEducation: { type: String },
  motherName: { type: String },
  motherAge: { type: Number },
  motherProfession: { type: String },
  motherEducation: { type: String },
  siblingsNamesOne: { type: String },
  ageSiblingsNamesOne: { type: Number },
  siblingsNamesTwo: { type: String },
  ageSiblingsNamesTwo: { type: Number },*/
  complaintAndDurations: {
    complaintAndDuration: { type: String },
  },
  backgorund: {
    gestation: { type: String },
    typeOfDelivery: { type: String },
    complications: { type: String },
    usedMedication: { type: String },
    medicalGuidance: { type: String },
    whichMedication: { type: String },
    prenatalCare: { type: String },
    prenatalCareWhy: { type: String },
    childProblem: { type: String },
    whichProblem: { type: String },
    parentsWorkHours: { type: String },
    childCaregiver: { type: String },
    weeklyRoutine: { type: String },
  },

  development: {
    sleep: { type: String },
    disease: { type: String },
    hearingEarInfection: { type: String },
    vision: { type: String },
    allergies: { type: String },
    surgeriesAndDates: { type: String },
    hospitalizations: { type: String },
    medication: { type: String },
    breastfed: { type: String },
    untilWhen: { type: String },
    lookedAtMotherBreastfeeding: { type: String },
    whatEatsNow: { type: String },
    chokedEasily: { type: String },
    gastroesophagealReflux: { type: String },
    usedBottle: { type: String },
    whenStartedUsingBottle: { type: String },
    forHowLongUsedBottle: { type: String },
    whenChangedFromLiquidToPastyFoods: { type: String },
    pastyToSolidFoods: { type: String },
    fever: { type: String },
    fainting: { type: String },
    convulsions: { type: String },
    otherProblems: { type: String },
    heldHeadUp: { type: String },
    satWithSupport: { type: String },
    satWithoutSupport: { type: String },
    crawled: { type: String },
    walked: { type: String },
    diurnalSphincterControl: { type: String },
    nocturnalSphincterControl: { type: String },
    fellALot: { type: String },
    bumpedIntoThings: { type: String },
    speechBabblingWhen: { type: String },
    quietBaby: { type: String },
    suction: { type: String },
    chewing: { type: String },
    swallowing: { type: String },
    breathing: { type: String },
    presentsNoise: { type: String },
    effort: { type: String },
    leftOrRightHanded: { type: String },
    usedPacifierBottleFinger: { type: [String] },
    untilWhenUsedPacifierBottleFinger: { type: String },
    otherHabits: { type: String },
    bathesAlone: { type: String },
    eatsAlone: { type: String },
    sinceWhenEatsAlone: { type: String },
    whatDoesItUse: { type: String },
    whichHandEatsWith: { type: String },
    playsBall: { type: String },
    jumpsRope: { type: String },
    brushesTeethAlone: { type: String },
    dressesAlone: { type: String },
    putsOnShoes: { type: String },
    tiesShoes: { type: String },
    closesZipper: { type: String },
    hasOwnInitiative: { type: String },
    demonstratesWishes: { type: String },
    whatDoesWhenAlone: { type: String },
    howSolvesProblems: { type: String },
  },

  socioCultural: {
    relationshipWithParents: { type: String },
    relationshipWithAdults: { type: String },
    relationshipWithOtherChildren: { type: String },
    whoAreYourBestFriends: { type: String },
    whatLikes: { type: String },
    muchChargedToSpeakCorrectly: { type: String },
    familyWithSpeechDifficulty: { type: String },
    difficultyOfUnderstanding: { type: String },
    hasVisualContact: { type: String },
    bitesOtherChildrenAggressive: { type: String },
    communicationInitiative: { type: String },
    maintainsDialogue: { type: String },
    hasContactWithWhatLikes: { type: String },
    doesntLike: { type: String },
    hasGoodSchoolPerformance: { type: String },
    whenStartedSchool: { type: String },
    hadGoodAdaptation: { type: String },
    howIsTheirBehavior: { type: String },
    answersByName: { type: String },
  },

  importantObservations: {
    importantObservation: { type: String },
  },
});

export interface IAnamnesisSpeechTherapyEntity
  extends Omit<IAnamnesisSpeechTherapy, '_id'>,
    Document {}
