import { Schema } from 'mongoose';
import  { Document } from 'mongoose';
import { IAutismBehaviorChecklist } from 'src/features/autism-behavior-checklist/types/autismBehaviorChecklist';



export const AutismBehaviorChecklistEntitySchema = new Schema({
    spinsAroundForLongPeriods: {
        es: { type: Number, required: false},
        re: { type: Number, required: false},
        co: { type: Number, required: false},
        lg: { type: Number, required: false},
        ps: { type: Number, required: false},
    },
    learnsTaskButForgetsQuickly: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    rarelyRespondsNonverbalSocialStimuli: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    absenceOfResponseToVerbalRequests: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    usesToysInappropriately: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    poorUseOfVisualDiscrimination: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    absenceOfSocialSmile: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    inappropriateUseOfPronouns: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    insistsOnKeepingCertainObjects: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    seemsNotToListen: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    monotonousAndRythmLessSpeech: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    swaysForLongPeriods: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    doesNotReachToBickUp: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    strongReactionsToEnvironmentalChanges: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    lackOfAttentionToOwnName: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    runsInterruptingWithSpins: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    absenceOfResponseToFacialExpression: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    rarelyUsesYesOrI: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    possessesSkillInOneAreaOfDevelopment: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    absenceOfResponseToVerbalRequestsInvolvingSpaceReferences: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    startleReactionToLoudSound: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    wavesHands: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    intenseTantrums: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    activelyAvoidsEyeContact: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    resistsToTouchOrCarry: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    doesNotReactToPainfulStimuli: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    difficultAndRigidToCarry: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    flaccidWhenCarried: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    pointsToIndicateDesiredObject: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    walksOnTiptoes: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    hurtsOthersByBitingAndHitting: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    repeatsTheSamePhraseManyTimes: {
         es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    absenceOfImitationOfOtherChildrensPlay: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    absenceOfBlinkingReaction: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    hurtsSelfByBitingAndHittingHead: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    doesNotWaitToBeServed: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    doesNotPointToMoreThanFiveObjects: {
         es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    difficultyMakingFriends: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    coversEarsForSeveralSounds: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    spinsAndHitsObjectsManyTimes: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    difficultyToiletTraining: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    uses0To5WordsToIndicateNeeds: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    frequentlyAnxiousOrFearful: {
       es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    frownsCoversOrTurnsEyes: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    doesNotDressWithoutHelp: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    constantlyRepeatsSameWordsOrSounds: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    looksThroughPeople: {
         es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    repeatsQuestionsAndPhrasesSaidByOthers: {
       es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    frequentlyUnawareOfDangers: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    prefersToManipulateInanimateObjects: {
         es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    touchesSmellsOrLicksObjects: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    frequentlyDoesNotReactToNewPeople: {
         es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    repeatsSequencesOfComplicatedBehaviors: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    destructiveWithToysAndFamilyStuff: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    delayIdentifiedBefore30Months: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    usesMoreThan15AndLessThan30PhrasesDaily: {
       es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
    staresAtTheEnvironmentForLongPeriods: {
        es: { type: Number, required: false },
        re: { type: Number, required: false },
        co: { type: Number, required: false },
        lg: { type: Number, required: false },
        ps: { type: Number, required: false },
    },
})


export interface IAutismBehaviorChecklistEntity extends Omit<IAutismBehaviorChecklist, '_id'>, Document { }