import { Schema, Document } from 'mongoose';
import { IAutismBehaviorChecklist } from 'src/features/autism-behavior-checklist/types/autismBehaviorChecklist';

export const autismBehaviorChecklistSchema = new Schema({
    identification: {
        patient: { type: Schema.Types.ObjectId, ref: "User" },
        dateBirth: { type: String, required: true },
        age: { type: Number, required: true },
        sex: { type: String, required: true },
        dateOfApplication: { type: String, required: true },
        evaluator: {type: Schema.Types.ObjectId, ref: "User"}
        },
        
        questionOne: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionTwo: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionThree: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionFour: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionFive: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionSix: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionSeven: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionEight: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionNine: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionTen: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionEleven: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionTwelve: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionThirteen: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionFourteen: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionFifteen: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionSixteen: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionSeventeen: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionEighteen: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionNineteen: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionTwenty: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionTwentyOne: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionTwentyTwo: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionTwentyThree: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionTwentyFour: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionTwentyFive: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionTwentySix: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionTwentySeven: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionTwentyEight: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionTwentyNine: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionThirty: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionThirtyOne: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionThirtyTwo: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionThirtyThree: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionThirtyFour: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionThirtyFive: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionThirtySix: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionThirtySeven: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionThirtyEight: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionThirtyNine: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionForty: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionFortyOne: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionFortyTwo: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionFortyThree: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionFortyFour: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionFortyFive: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionFortySix: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionFortySeven: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionFortyEight: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionFortyNine: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionFifty: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionFiftyOne: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionFiftyTwo: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionFiftyThree: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionFiftyFour: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionFiftyFive: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionFiftySix: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        questionFiftySeven: {
            es: { type: Number, default: 0 },
            re: { type: Number, default: 0 },
            co: { type: Number, default: 0 },
            lg: { type: Number, default: 0 },
            ps: { type: Number, default: 0 },
        },
        
        score: { 
        esScore:{ type: Number, default: 0 },
        reScore:{ type: Number, default: 0 },
        coScore:{ type: Number, default: 0 },
        lgScore:{ type: Number, default: 0 },
        psScore:{ type: Number, default: 0 },
        },

        totalResult: {
        resultTotal: { type: Number, default: 0 }
        }
    
    });
export interface IAutismBehaviorChecklistEntity extends Omit<IAutismBehaviorChecklist, '_id'>, Document { }