import { Document, Schema } from 'mongoose'
import { ICreateGmfm } from 'src/features/gmfm/types/gmfm';

export const GmfmSchema = new Schema ({
    _id: { type: Schema.Types.ObjectId, auto: true },
    patient: { type: Schema.Types.ObjectId, ref: 'User' },
    doctor: { type: Schema.Types.ObjectId, ref: 'User' },
    lieDownAndRollOver: { 
        supHeadInMidline: { type: Number },
        supHandsToMidline: { type: Number },
        supRaisesHead45: { type: Number },
        supFlexesRightHipAndKnee: { type: Number },
        supFlexesLeftHipAndKnee: { type: Number },
        supReachesRightHandAcrossMidline: { type: Number },
        supReachesLeftHandAcrossMidline: { type: Number },
        supRollsToProneRight: { type: Number },
        supRollsToProneLeft: { type: Number },
        proneRaisesHeadVertical: { type: Number },
        proneOnForearmsRaisesHead: { type: Number },
        proneOnForearmsRightExtendsLeftArm: { type: Number },
        proneOnForearmsLeftExtendsRightArm: { type: Number },
        proneRollsToSupineRight: { type: Number },
        proneRollsToSupineLeft: { type: Number },
        pronePivots90Right: { type: Number },
        pronePivots90Left: { type: Number },
    },
    toSit: {
        supPulledToSitWithHeadControl: { type: Number },
        supRollsRightToSit: { type: Number },
        supRollsLeftToSit: { type: Number },
        sittingSupportedHeadUp3Seconds: { type: Number },
        sittingSupportedHeadMidline10Seconds: { type: Number },
        sittingArmsSupported5Seconds: { type: Number },
        sittingArmsFree3Seconds: { type: Number },
        sittingReachesForToyForward: { type: Number },
        sittingReachesForToyRight45: { type: Number },
        sittingReachesForToyLeft45: { type: Number },
        sittingRightSideFreeArms5Seconds: { type: Number },
        sittingLeftSideFreeArms5Seconds: { type: Number },
        sittingLowersToProneControlled: { type: Number },
        sittingFeetForwardReaches4PointRight: { type: Number },
        sittingFeetForwardReaches4PointLeft: { type: Number },
        sittingPivots90NoArms: { type: Number },
        sittingOnBenchFreeArmsAndFeet10Seconds: { type: Number },
        standingReachesSittingOnSmallBench: { type: Number },
        floorReachesSittingOnSmallBench: { type: Number },
        floorReachesSittingOnLargeBench: { type: Number },
    },
    crawAndKneel:{
        proneDrags18MetersForward: { type: Number },
        fourPointsHoldsWeight10Seconds: { type: Number },
        fourPointsReachesSittingArmsFree: { type: Number },
        proneReachesFourPoints: { type: Number },
        fourPointsAdvancesRightArm: { type: Number },
        fourPointsAdvancesLeftArm: { type: Number },
        fourPointsCrawls18MetersForward: { type: Number },
        fourPointsCrawls18MetersAlternating: { type: Number },
        fourPointsClimbs4Steps: { type: Number },
        fourPointsDescends4StepsBackwards: { type: Number },
        sittingReachesKneelingArmsFree10Seconds: { type: Number },
        kneelingReachesSemiKneelingRightArmsFree10Seconds: { type: Number },
        kneelingReachesSemiKneelingLeftArmsFree10Seconds: { type: Number },
        kneelingWalks10StepsForward: { type: Number },
    },
    standing: {
        floorPullsToStandOnLargeBench: { type: Number },
        standingFreeArms3Seconds: { type: Number },
        standingHoldsLargeBenchRaisesRightFoot: { type: Number },
        standingHoldsLargeBenchRaisesLeftFoot: { type: Number },
        standingFreeArms20Seconds: { type: Number },
        standingRaisesLeftFootFreeArms10Seconds: { type: Number },
        standingRaisesRightFootFreeArms10Seconds: { type: Number },
        sittingSmallBenchReachesStandingNoArms: { type: Number },
        kneelingReachesStandingSemiKneelingRightNoArms: { type: Number },
        kneelingReachesStandingSemiKneelingLeftNoArms: { type: Number },
        standingLowersToSitFloorControlled: { type: Number },
        standingSquatsFreeArms: { type: Number },
        standingPicksUpObjectReturnsStanding: { type: Number },
    },
    walkRunJump: {
        standingHoldingLargeBenchSideStepsRight5Steps: { type: Number },
        standingHoldingLargeBenchSideStepsLeft5Steps: { type: Number },
        standingTwoHandsHeldWalks10Steps: { type: Number },
        standingOneHandHeldWalks10Steps: { type: Number },
        standingWalks10StepsForward: { type: Number },
        standingWalks10StepsTurnsAndReturns: { type: Number },
        standingWalks10StepsBackwards: { type: Number },
        standingWalks10StepsCarryingLargeObject: { type: Number },
        standingWalks10StepsBetweenParallelLines: { type: Number },
        standingWalks10StepsOn2cmLine: { type: Number },
        standingStepsOverStickRightFootFirst: { type: Number },
        standingStepsOverStickLeftFootFirst: { type: Number },
        standingRuns4Point5MetersReturns: { type: Number },
        standingKicksBallRightFoot: { type: Number },
        standingKicksBallLeftFoot: { type: Number },
        standingJumps30cmBothFeet: { type: Number },
        standingJumpsForward30cmBothFeet: { type: Number },
        standingHops10TimesRightFoot: { type: Number },
        standingHops10TimesLeftFoot: { type: Number },
        standingHoldingRailClimbs4StepsAlternating: { type: Number },
        standingHoldingRailDescends4StepsAlternating: { type: Number },
        standingClimbs4StepsAlternating: { type: Number },
        standingDescends4StepsAlternating: { type: Number },
        standingJumpsDownFromStepBothFeet: { type: Number },
    }
});

export interface IGmfmEntity extends Omit<ICreateGmfm, '_id'>, Document {}