import { Schema, Document } from 'mongoose';
import { IIaPsychoPedagogical } from 'src/features/income-assessment/types/iaPsychopedagogical';

export const IncomeAssessmentSchema = new Schema({
  _id: { type: Schema.Types.ObjectId, required: true, auto: true },
  doctor: { type: Schema.Types.ObjectId, required: true, ref: 'User' },
  dateOfApplication: { type: String, required: true },
  patient: { type: Schema.Types.ObjectId, required: true, ref: 'User'},
  familyOurSchoolComplaint: { type: String, required: true },
  observation: { type: String, required: true },
  observedAspectsPshyco: {
    pencilGrip: {type: String, enum: ['Preensão primitiva' , 'Preensão palmar supinada' , 'Preensão de transição' , 'Preensão madura']},
	  hypothesisWriting:{type: String, enum: ['Não se aplica a faixa etária' , 'Não realiza' , 'Pictográfica' , 'Pré silábica' , 'Silábica' , 'Alfabética']},
	  writingWordsAndPhrases: {type: String, enum: ['Não se aplica a faixa etária' , 'Não realiza' , 'Reconhece letras' , 'Preensão madura' , 'Autônomo em palavras' , 'Autônomo em palavras e frases']}, 
	  reading: {type: String, enum: ['Não se aplica a faixa etária' , 'Não realiza' , 'Rota lexical' , 'Rota fonológica']},
	  numbersAndQuantiity: {type: String, enum: ['Não se aplica a faixa etária' , 'Não realiza' , 'Reconhece' , 'Nomeia' , 'Quantifica']}, 
	  operationsMathematical:  {type: String, enum: ['Não se aplica a faixa etária' , 'Não realiza' , 'Fase sensório motor' , 'Fase pré-operatório' , 'Fase operatório concreto' , 'Fase operatório formal']},
	  functionsExecutive: {type: String, enum: ['Inibição' , 'Memória de trabalho' , 'Flexibilidade cognitiva' , 'Planejar' , 'Tomar decisões' , 'Estabelecer metas' , 'Antecipar' , 'Organizar' , 'Ter fluidez']}, 
  },
  evaluationofPerformanceBody2At4YearsPshyco: { 
    masterBodyGesturesInCulturalSelfcareAndPlay:{type: String, enum: ['Sim' , 'Não']},  
	  moveBodyUsingSpatialConceptsLikeInFrontBehindUpDown: {type: String, enum: ['Sim' , 'Não']}, 
	  exploreVariousBodyMovementsJumpDance: {type: String, enum: ['Sim' , 'Não']}, 
	  demonstrateIndependenceInSelfCare: {type: String, enum: ['Sim' , 'Não']}, 
	  developManualSkillsLikeDrawingAndCutting: {type: String, enum: ['Sim' , 'Não']}, 
   },
  evaluationOfPerformanceBody5At6YearsPshyco: {
    expressFeelingsAndEmotionsThroughBodyInDailyLifePlayDanceMusic: {type: String, enum: ['Sim' , 'Não']}, 
	  controlBodyForPlayListeningStorytellingAndArtActivities: {type: String, enum: ['Sim' , 'Não']}, 
	  createMovementsGesturesAndMimeInPlayAndArt:{type: String, enum: ['Sim' , 'Não']}, 
	  adoptSelfCareHabitsForHygieneEatingComfort: {type: String, enum: ['Sim' , 'Não']}, 
  },
  evaluationOfPerformanceTrailsAndOthers2At4YearsPshyco: {
    createSoundsWithObjectsAndInstruments: {type: String, enum: ['Sim' , 'Não']},
	  useMaterialsClayModelingMassExploringShapesTexturesAndVolumes: {type: String, enum: ['Sim' , 'Não']},
	  useEnvironmentalSoundSourcesInMusicActivities: {type: String, enum: ['Sim' , 'Não']},
  },
  evaluationOfPerformanceTrailsAndOthers5At6YearsPshyco: {
    createSoundBasedPerformancesWithObjectsAndInstruments: {type: String, enum: ['Sim' , 'Não']},
	  expressThroughDrawingPaintingAndSculpture: {type: String, enum: ['Sim' , 'Não']},
	  recognizeSoundQualitiesIntensityDurationPitchTimbreInProductions: {type: String, enum: ['Sim' , 'Não']},
  },
  evaluationOfPerformanceListeningSpeechAndOthers2At4YearsPshyco: {
    engageInDialogueExpressingDesiresNeedsFeelings: {type: String, enum: ['Sim' , 'Não']},
	  identifyAndCreateSoundsRecognizeRhymes: {type: String, enum: ['Sim' , 'Não']},
	  showInterestInStoriesAndDifferentiateWrittenFromIllustratedText: {type: String, enum: ['Sim' , 'Não']},
	  askAndAnswerQuestionsAboutStories: {type: String, enum: ['Sim' , 'Não']},
	  tellStoriesAboutPersonalExperiences: {type: String, enum: ['Sim' , 'Não']},
	  createAndTellStoriesOrally: {type: String, enum: ['Sim' , 'Não']},
	  handleVariousTextsRecognizingTheirSocialUse: {type: String, enum: ['Sim' , 'Não']},
	  participateInListeningToDifferentTextGenresNurseryRhymesStoriesMenus: {type: String, enum: ['Sim' , 'Não']},
	  useWritingToolsToTraceLettersAndSymbols: {type: String, enum: ['Sim' , 'Não']},
  },
  evaluationOfPerformanceListeningSpeechAndOthers5At6YearsPshyco: {
    expressIdeasWishesAndFeelingsOrallyAndThroughSpontaneousWriting: {type: String, enum: ['Sim' , 'Não']},
	  createSongsPoemsAndRhymes: {type: String, enum: ['Sim' , 'Não']},
	  selectAndBrowseBooksIdentifyThemesAndWords: {type: String, enum: ['Sim' , 'Não']},
	  retellStoriesAndPlanCollectivePerformances: {type: String, enum: ['Sim' , 'Não']},
	  writeRetellingsWithTeacherAsScribe: {type: String, enum: ['Sim' , 'Não']},
	  producePersonalOralAndWrittenStories: {type: String, enum: ['Sim' , 'Não']},
	  hypothesizeAboutKnownTextGenresUsingObservations: {type: String, enum: ['Sim' , 'Não']},
	  selectKnownBooksAndTextsForReadingAloud: {type: String, enum: ['Sim' , 'Não']},
	  recordWordsAndTextsUsingSpontaneousWriting: {type: String, enum: ['Sim' , 'Não']},
  },
  evaluationOfPerformanceSpacesAndOthers2At4YearsPshyco: {
    compareObjectPropertiesTextureSize: {type: String, enum: ['Sim' , 'Não']},
	  observeAndDescribeDailyAndNaturalPhenomena: {type: String, enum: ['Sim' , 'Não']},
	  sharePlantAndAnimalCare: {type: String, enum: ['Sim' , 'Não']},
	  identifySpatialInsideOutsideAndTemporalBeforeAfterRelations: {type: String, enum: ['Sim' , 'Não']},
	  classifyObjectsByAttributes: {type: String, enum: ['Sim' , 'Não']},
	  useBasicTimeConceptsNowBeforeAfter: {type: String, enum: ['Sim' , 'Não']},
	  countObjectsPeopleBooks: {type: String, enum: ['Sim' , 'Não']},
	  recordNumbersForQuantityOfChildrenAndObjects: {type: String, enum: ['Sim' , 'Não']},
  },
  evaluationOfPerformanceSpacesAndOthers5At6YearsPshyco: {
    compareObjectsByProperties: {type: String, enum: ['Sim' , 'Não']},
	  observeAndDescribeMaterialChangesInExperiments: {type: String, enum: ['Sim' , 'Não']},
	  identifySourcesOfInformationAboutNature: {type: String, enum: ['Sim' , 'Não']},
	  recordObservationsUsingDrawingsNumbersOrWriting: {type: String, enum: ['Sim' , 'Não']},
	  classifyObjectsBySimilaritiesAndDifferences: {type: String, enum: ['Sim' , 'Não']},
	  relateFactsAboutBirthAndFamilyHistory: {type: String, enum: ['Sim' , 'Não']},
	  relateNumbersToQuantities: {type: String, enum: ['Sim' , 'Não']},
	  expressMeasurementsWeightHeightThroughSimpleGraphs: {type: String, enum: ['Sim' , 'Não']},
  },
  evaluationOfPerformanceTheSelfAndOthers2At4YearsPshyco: {
    showCareAndSolidarityInInteractions: {type: String, enum: ['Sim' , 'Não']},
	  demonstrateSelfConfidenceAndResilience: {type: String, enum: ['Sim' , 'Não']},
	  shareObjectsAndSpacesWithPeersAndAdults: {type: String, enum: ['Sim' , 'Não']},
	  communicateWithPeersAndAdultsForUnderstanding: {type: String, enum: ['Sim' , 'Não']},
	  respectDifferencesInPhysicalTraits: {type: String, enum: ['Sim' , 'Não']},
	  followBasicSocialRules: {type: String, enum: ['Sim' , 'Não']},
	  resolveConflictsWithAdultGuidance: {type: String, enum: ['Sim' , 'Não']},
  },
  evaluationOfPerformanceTheSelfAndOthers5At6YearsPshyco: {
    showEmpathyForOthersFeelingsAndNeeds: {type: String, enum: ['Sim' , 'Não']},
	  actIndependentlyWithConfidence: {type: String, enum: ['Sim' , 'Não']},
	  developParticipationAndCooperationSkills: {type: String, enum: ['Sim' , 'Não']},
	  expressIdeasAndFeelingsToDiverseGroups: {type: String, enum: ['Sim' , 'Não']},
	  valueBodyCharacteristicsAndRespectOthers: {type: String, enum: ['Sim' , 'Não']},
	  showInterestAndRespectForDifferentCultures: {type: String, enum: ['Sim' , 'Não']},
	  useRespectfulStrategiesToHandleConflicts: {type: String, enum: ['Sim' , 'Não']},
  },
  theSelfAndOthersPshyco: {
    respectAndExpressFeelingsAndEmotions: {type: String, enum: ['Sim' , 'Não']},
	  actInGroupsAndBuildNewRelationshipsRespectingDiversityAndSolidarity: {type: String, enum: ['Sim' , 'Não']},
	  knowAndRespectSocialRulesShowingRespectForOthers: {type: String, enum: ['Sim' , 'Não']},
  },
  bodyAndOthersPshyco: {
    recognizeTheImportanceOfDailyActionsForSelfHealthAndEnvironmentMaintenance: {type: String, enum: ['Sim' , 'Não']},
	  showAutonomyInHygieneEatingDressingAndSelfCareValuingOnesBody: {type: String, enum: ['Sim' , 'Não']},
	  intentionallyUseTheBodyCreativityControlAppropriatenessForInteraction: {type: String, enum: ['Sim' , 'Não']},
	  coordinateManualSkills: {type: String, enum: ['Sim' , 'Não']},
  },
  trailsAndOthersPshyco: {
    differentiateSoundTypesAndRhythmsInteractingWithMusicAsIndividualAndCollectiveExpression: {type: String, enum: ['Sim' , 'Não']},
	  expressThroughVisualArtsUsingVariousMaterials: {type: String, enum: ['Sim' , 'Não']},
	  relateToOthersThroughGesturesWordsGamesImitationsObservationsAndBodyLanguage: {type: String, enum: ['Sim' , 'Não']},
  },
  listeningAndOthersPshyco: {
    expressIdeasAndFeelingsInDifferentInteractions: {type: String, enum: ['Sim' , 'Não']},
	  argueAndNarrateFactsOrallyInChronologicalOrder: {type: String, enum: ['Sim' , 'Não']},
	  listenComprehendTellRetellAndCreateNarratives: {type: String, enum: ['Sim' , 'Não']},
	  knowDifferentTextGenresShowingUnderstanding: {type: String, enum: ['Sim' , 'Não']},
  },
  spacesAndOthersPshyco: {
    identifyNameAndCompareObjectPropertiesEstablishingRelationships: {type: String, enum: ['Sim' , 'Não']},
    interactWithEnvironmentAndNaturalArtificialPhenomenaWithCareAndCuriosity: {type: String, enum: ['Sim' , 'Não']},
    useVocabularyRelatedToMagnitudeSpaceAndMeasurementsForCommunication: {type: String, enum: ['Sim' , 'Não']},
    useUnitsOfMeasurementAndTimeNotionsForEverydayNeeds: {type: String, enum: ['Sim' , 'Não']},
    identifyAndRecordQuantitiesThroughVariousRepresentations: {type: String, enum: ['Sim' , 'Não']},
  },
  portugueseLanguage1GradePshyco: {
    segregateLettersFromSymbols: {type: String, enum: ['Sim' , 'Não']},
    recognizeAlphabetAsSpeechSoundRepresentation: {type: String, enum: ['Sim' , 'Não']},
    differentiatePrintedAndCursiveLetters: {type: String, enum: ['Sim' , 'Não']},
    compareSyllablesAndIdentifySimilaritiesDifferences: {type: String, enum: ['Sim' , 'Não']},
    writeWordsSentencesSpontaneouslyOrByDictation: {type: String, enum: ['Sim' , 'Não']},
    recognizeReadingDirection: {type: String, enum: ['Sim' , 'Não']},
  },
  mathematics1GradePshyco: {
    useNumbersAsIndicatorsInEverydaySituations: {type: String, enum: ['Sim' , 'Não']},
    countObjectsUsingVariousStrategies: {type: String, enum: ['Sim' , 'Não']},
    countUpTo100ObjectsAndPresentResultsVerballyOrSymbolically: {type: String, enum: ['Sim' , 'Não']},
    constructAdditionSubtractionFacts: {type: String, enum: ['Sim' , 'Não']},
    compareLengthsCapacitiesMasses: {type: String, enum: ['Sim' , 'Não']},
    readDataFromTablesAndBarGraphs: {type: String, enum: ['Sim' , 'Não']},
  },
  portugueseLanguage2GradePshyco: {
    segmentWordsIntoSyllablesAndModifyThem: {type: String, enum: ['Sim' , 'Não']},
    readAndWriteWordsWithSyllablesCVVCVC: {type: String, enum: ['Sim' , 'Não']},
    writeWordsSentencesAndTextsInPrintedAndCursiveForms: {type: String, enum: ['Sim' , 'Não']},
    recognizeRhymesSoundsInTexts: {type: String, enum: ['Sim' , 'Não']},
    readNewWordsByDecodingAndMemorization: {type: String, enum: ['Sim' , 'Não']},
    readAndComprehendDailyLifeTexts: {type: String, enum: ['Sim' , 'Não']},
  },
  mathematics2GradePshyco: {
    compareAndOrderNumbersUpToHundredsPlace: {type: String, enum: ['Sim' , 'Não']},
    compareObjectQuantitiesInTwoSets:{type: String, enum: ['Sim' , 'Não']},
    composeDecomposeNumbersUpToThreeDigits: {type: String, enum: ['Sim' , 'Não']},
    constructAdditionSubtractionFactsForMentalOrWrittenCalculation: {type: String, enum: ['Sim' , 'Não']},
    solveAndCreateAdditionSubtractionProblems: {type: String, enum: ['Sim' , 'Não']},
    buildSequencesOfNaturalNumbersInOrder: {type: String, enum: ['Sim' , 'Não']},
  },
  portugueseLanguage3GradePshyco: {
    readAndWriteWordsWithVariousSyllablesCVVCVC: {type: String, enum: ['Sim' , 'Não']},
    classifyWordsBySyllableCount: {type: String, enum: ['Sim' , 'Não']},
    useGrammaticalKnowledgeInTextProduction: {type: String, enum: ['Sim' , 'Não']},
    useDictionaryToClarifyDoubtsAboutSpelling: {type: String, enum: ['Sim' , 'Não']},
    readAndComprehendPoeticTextsExploringRhymesSounds: {type: String, enum: ['Sim' , 'Não']},
  },
  mathematics3GradePshyco: {
    readWriteCompareNumbersUpToThousandsPlace: {type: String, enum: ['Sim' , 'Não']},
    useAdditionMultiplicationFactsForCalculation: {type: String, enum: ['Sim' , 'Não']},
    solveAndCreateAdditionSubtractionProblems: {type: String, enum: ['Sim' , 'Não']},
    solveAndCreateMultiplicationProblemsUpTo10: {type: String, enum: ['Sim' , 'Não']},
    associateGeometricFiguresWithPhysicalObjects: {type: String, enum: ['Sim' , 'Não']},
    readTimeOnDigitalAndAnalogClocks: {type: String, enum: ['Sim' , 'Não']},
  },
  portugueseLanguage4GradePshyco: {
    spellWordsUsingPhonemeGraphemeCorrespondenceRules: {type: String, enum: ['Sim' , 'Não']},
    identifyAndUsePunctuationMarksInWriting: {type: String, enum: ['Sim' , 'Não']},
    planAndProduceTextsBasedOnResearch: {type: String, enum: ['Sim' , 'Não']},
    useDictionaryToClarifySpellingDoubts: {type: String, enum: ['Sim' , 'Não']},
    identifyElementsInNarratives: {type: String, enum: ['Sim' , 'Não']},
  },
  mathematics4GradePshyco: {
    readWriteOrderNumbersUpToTenThousandPlace: {type: String, enum: ['Sim' , 'Não']},
    decomposeAndComposeNaturalNumbersForCalculation: {type: String, enum: ['Sim' , 'Não']},
    solveAndCreateProblemsWithNaturalNumbers: {type: String, enum: ['Sim' , 'Não']},
    useRelationshipsBetweenOperationsForStrategyExpansion: {type: String, enum: ['Sim' , 'Não']},
    determineUnknownNumberInEquality: {type: String, enum: ['Sim' , 'Não']},
    readAndRecordMeasuresAndTimeIntervals: {type: String, enum: ['Sim' , 'Não']},
  },
  portugueseLanguage5GradePshyco: {
    spellWordsUsingPhonemeGraphemeAndIrregularRules: {type: String, enum: ['Sim' , 'Não']},
    accuratelyAccentuateWords: {type: String, enum: ['Sim' , 'Não']},
    differentiateCommaSemicolonColonInTexts: {type: String, enum: ['Sim' , 'Não']},
    useLinguisticKnowledgeInTextProduction: {type: String, enum: ['Sim' , 'Não']},
    attributeMeaningToNonLinguisticAspectsInSpeech: {type: String, enum: ['Sim' , 'Não']},
    useDictionaryToClarifyDoubtsAboutSpelling: {type: String, enum: ['Sim' , 'Não']},
  },
  mathematics5GradePshyco: {
    readWriteOrderNumbersUpToHundredThousandPlace: {type: String, enum: ['Sim' , 'Não']},
    readWriteOrderRationalNumbersInDecimalForm: {type: String, enum: ['Sim' , 'Não']},
    solveAndCreateAdditionSubtractionProblemsWithRationalNumbers: {type: String, enum: ['Sim' , 'Não']},
    solveAndCreateMultiplicationDivisionProblemsWithRationalNumbers: {type: String, enum: ['Sim' , 'Não']},
    concludeInvestigationOnDifferentWaysOfPerformingOperations: {type: String, enum: ['Sim' , 'Não']},
  },
  obersaviotGeneral : { type: String},
  evaluatorSigned: { type: String},
});

export interface IIncomeAssessmentEntity extends Omit<IIaPsychoPedagogical, '_id'>, Document {}