import { Schema, Document } from 'mongoose';
import { IIntraverbalAssessment } from 'src/features/intraverbal-assessment/types/intraverbalAssessment';

export const IntraverbalAssessmentSchema = new Schema({
  _id: { type: Schema.Types.ObjectId, required: true, auto: true },
  patient: { type: Schema.Types.ObjectId, required: true, ref: 'patient' },
  doctor: { type: Schema.Types.ObjectId, required: true, ref: 'doctor' },
  //birthDate: { type: String, get: (data:Date) => data ? format(data,'dd/MM/yyyy') : undefined  },
  date: { type: Date, required: true },
  //diagonostic: { type: String, required: false },
  animalSounds: {
    theCatSays: { type: String, required: false },
    theCatSaysScore: { type: String, required: false },
    theFrogDoesntWashHisFeetHeDoesntWashBecauseHeDoesnt: { type: String, required: false },
    theFrogDoesntWashHisFeetHeDoesntWashBecauseHeDoesntScore: { type: String, required: false },
    readyAim: { type: String, required: false },
    readyAimScore: { type: String, required: false },
    myLittleChickYellowFitsHereInMy: { type: String, required: false },
    myLittleChickYellowFitsHereInMyScore: { type: String, required: false },
    cirandaCirandinhaLetUsAll: { type: String, required: false },
    cirandaCirandinhaLetUsAllScore: { type: String, required: false },
    theDogSays: { type: String, required: false },
    theDogSaysScore: { type: String, required: false },
    ithrewAStickAtThe: { type: String, required: false },
    ithrewAStickAtTheScore: { type: String, required: false },
    theSpiderClimbedUpThe: { type: String, required: false },
    theSpiderClimbedUpTheScore: { type: String, required: false },
    headShouldersKneesAnd: { type: String, required: false },
    headShouldersKneesAndScore: { type: String, required: false },
    happyBirthdayTo: { type: String, required: false },
    happyBirthdayToScore: { type: String, required: false },
    other1Group1: { type: String, required: false },
    other1Group1Score: { type: String, required: false },
    other2Group1: { type: String, required: false },
    other2Group1Score: { type: String, required: false },
    subtotalPointsGroup1: { type: String, required: false },
  },
  names: {
    whatIsYourName: { type: String, required: false },
    whatIsYourNameScore: { type: String, required: false },
    youBrushYour: { type: String, required: false },
    youBrushYourScore: { type: String, required: false },
    shoesAnd: { type: String, required: false },
    shoesAndScore: { type: String, required: false },
    youRide: { type: String, required: false },
    youRideScore: { type: String, required: false },
    afterUsingTheBathroomYouGive: { type: String, required: false },
    afterUsingTheBathroomYouGiveScore: { type: String, required: false },
    youSitOnA: { type: String, required: false },
    youSitOnAScore: { type: String, required: false },
    youEat: { type: String, required: false },
    youEatScore: { type: String, required: false },
    oneTwo: { type: String, required: false },
    oneTwoScore: { type: String, required: false },
    youWashYour: { type: String, required: false },
    youWashYourScore: { type: String, required: false },
    youSleepInA: { type: String, required: false },
    youSleepInAScore: { type: String, required: false },
    other1Group2: { type: String, required: false },
    other1Group2Score: { type: String, required: false },
    other2Group2: { type: String, required: false },
    other2Group2Score: { type: String, required: false },
    subtotalPointsGroup2: { type: String, required: false },
  },
  simpleQuestionsPartOne: {
    whatCanYouDrink: { type: String, required: false },
    whatCanYouDrinkScore: { type: String, required: false },
    whatCanFly: { type: String, required: false },
    whatCanFlyScore: { type: String, required: false },
    whatNumbersDoYouKnow: { type: String, required: false },
    whatNumbersDoYouKnowScore: { type: String, required: false },
    whatCanYouSing: { type: String, required: false },
    whatCanYouSingScore: { type: String, required: false },
    whatIsYourFavoriteMovie: { type: String, required: false },
    whatIsYourFavoriteMovieScore: { type: String, required: false },
    whatColorsDoYouKnow: { type: String, required: false },
    whatColorsDoYouKnowScore: { type: String, required: false },
    whatDoYouRead: { type: String, required: false },
    whatDoYouReadScore: { type: String, required: false },
    whatIsOutThere: { type: String, required: false },
    whatIsOutThereScore: { type: String, required: false },
    whatIsIntheKitchen: { type: String, required: false },
    whatIsIntheKitchenScore: { type: String, required: false },
    whatAnimalsDoYouKnow: { type: String, required: false },
    whatAnimalsDoYouKnowScore: { type: String, required: false },
    other1Group3: { type: String, required: false },
    other1Group3Score: { type: String, required: false },
    other2Group3: { type: String, required: false },
    other2Group3Score: { type: String, required: false },
    subtotalPointsGroup3: { type: String, required: false },
  },
  simpleQuestionsPartTwo: {
    whoIsYourTeacher: { type: String, required: false },
    whoIsYourTeacherScore: { type: String, required: false },
    whereDoYouWashYourHands: { type: String, required: false },
    whereDoYouWashYourHandsScore: { type: String, required: false },
    whoLivesOnTheFarm: { type: String, required: false },
    whoLivesOnTheFarmScore: { type: String, required: false },
    whereIsTheRefrigerator: { type: String, required: false },
    whereIsTheRefrigeratorScore: { type: String, required: false },
    whoDrivesTheCar: { type: String, required: false },
    whoDrivesTheCarScore: { type: String, required: false },
    whereDoYouTakeABath: { type: String, required: false },
    whereDoYouTakeABathScore: { type: String, required: false },
    howOldAreYou: { type: String, required: false },
    howOldAreYouScore: { type: String, required: false },
    whereAreTheTrees: { type: String, required: false },
    whereAreTheTreesScore: { type: String, required: false },
    whoDoYouSeeOnTV: { type: String, required: false },
    whoDoYouSeeOnTVScore: { type: String, required: false },
    whyDoWeUseBandaid: { type: String, required: false },
    whyDoWeUseBandaidScore: { type: String, required: false },
    other1Group4: { type: String, required: false },
    other1Group4Score: { type: String, required: false },
    other2Group4: { type: String, required: false },
    other2Group4Score: { type: String, required: false },
    subtotalPointsGroup4: { type: String, required: false },
  
  },
  categories: {
    whatIsTheShapeOfTheTire: { type: String, required: false },
    whatIsTheShapeOfTheTireScore: { type: String, required: false },
    whatGrowsInTheGarden: { type: String, required: false },
    whatGrowsInTheGardenScore: { type: String, required: false },
    whatCanBiteYou: { type: String, required: false },
    whatCanBiteYouScore: { type: String, required: false },
    whatDoYouDoWithASpoon: { type: String, required: false },
    whatDoYouDoWithASpoonScore: { type: String, required: false },
    whatCanYouPush: { type: String, required: false },
    whatCanYouPushScore: { type: String, required: false },
    whereDoYouFindWheels: { type: String, required: false },
    whereDoYouFindWheelsScore: { type: String, required: false },
    whatDoYouUseToSmell: { type: String, required: false },
    whatDoYouUseToSmellScore: { type: String, required: false },
    sayTheNameOfSomeClothes: { type: String, required: false },
    sayTheNameOfSomeClothesScore: { type: String, required: false },
    sayTheNameOfSomethingSharp: { type: String, required: false },
    sayTheNameOfSomethingSharpScore: { type: String, required: false },
    whatIsTheColorOfTheTire: { type: String, required: false },
    whatIsTheColorOfTheTireScore: { type: String, required: false },
    other1Group5: { type: String, required: false },
    other1Group5Score: { type: String, required: false },
    other2Group5: { type: String, required: false },
    other2Group5Score: { type: String, required: false },
    subtotalPointsGroup5: { type: String, required: false },
    
  },
  adjectives: {
    whatDoYouWearOnYourHead: { type: String, required: false },
    whatDoYouWearOnYourHeadScore: { type: String, required: false },
    whatDoYouUseToEat: { type: String, required: false },
    whatDoYouUseToEatScore: { type: String, required: false },
    whatAnimalWalksVerySlowly: { type: String, required: false },
    whatAnimalWalksVerySlowlyScore: { type: String, required: false },
    whatIsOnTopOfTheHouse: { type: String, required: false },
    whatIsOnTopOfTheHouseScore: { type: String, required: false },
    whereDoYouWrite: { type: String, required: false },
    whereDoYouWriteScore: { type: String, required: false },
    whatIsInsideTheHouse: { type: String, required: false },
    whatIsInsideTheHouseScore: { type: String, required: false },
    sayTheNameOfThingsThatAreHot: { type: String, required: false },
    sayTheNameOfThingsThatAreHotScore: { type: String, required: false },
    whatGrowsOnYourHead: { type: String, required: false },
    whatGrowsOnYourHeadScore: { type: String, required: false },
    whatIsUnderABoat: { type: String, required: false },
    whatIsUnderABoatScore: { type: String, required: false },
    whereDoYouEat: { type: String, required: false },
    whereDoYouEatScore: { type: String, required: false },
    other1Group6: { type: String, required: false },
    other1Group6Score: { type: String, required: false },
    other2Group6: { type: String, required: false },
    other2Group6Score: { type: String, required: false },
    subtotalPointsGroup6: { type: String, required: false },
    
  },
  multipleQuestionsPartOne: {
    whatMakesYouSad: { type: String, required: false },
    whatMakesYouSadScore: { type: String, required: false },
    whatAnimalHasAVeryLongNeck: { type: String, required: false },
    whatAnimalHasAVeryLongNeckScore: { type: String, required: false },
    sayTheNameOfSomethingThatIsNotForEating: { type: String, required: false },
    sayTheNameOfSomethingThatIsNotForEatingScore: { type: String, required: false },
    whatHelpsAFlowerGrow: { type: String, required: false },
    whatHelpsAFlowerGrowScore: { type: String, required: false },
    whatCanYouNotWear: { type: String, required: false },
    whatCanYouNotWearScore: { type: String, required: false },
    whatDoYouDoWithMoney: { type: String, required: false },
    whatDoYouDoWithMoneyScore: { type: String, required: false },
    whatNumberIsBetween6And8: { type: String, required: false },
    whatNumberIsBetween6And8Score: { type: String, required: false },
    whatIsInsideABalloon: { type: String, required: false },
    whatIsInsideABalloonScore: { type: String, required: false },
    whatIsYourLastName: { type: String, required: false },
    whatIsYourLastNameScore: { type: String, required: false },
    sayTheNameOfSomethingSticky: { type: String, required: false },
    sayTheNameOfSomethingStickyScore: { type: String, required: false },
    other1Group7: { type: String, required: false },
    other1Group7Score: { type: String, required: false },
    other2Group7: { type: String, required: false },
    other2Group7Score: { type: String, required: false },
    subtotalPointsGroup7: { type: String, required: false },
   
  },
  multipleQuestionsPartTwo: {
    whereDoYouPutDirtyClothes: { type: String, required: false },
    whereDoYouPutDirtyClothesScore: { type: String, required: false },
    whatDoYouTakeToABirthday: { type: String, required: false },
    whatDoYouTakeToABirthdayScore: { type: String, required: false },
    whatDayIsToday: { type: String, required: false },
    whatDayIsTodayScore: { type: String, required: false },
    whatDoYouSeeInTheField: { type: String, required: false },
    whatDoYouSeeInTheFieldScore: { type: String, required: false },
    whatDayComesBeforeTuesday: { type: String, required: false },
    whatDayComesBeforeTuesdayScore: { type: String, required: false },
    whyDoPeopleWearGlasses: { type: String, required: false },
    whyDoPeopleWearGlassesScore: { type: String, required: false },
    whenDoYouSetTheTable: { type: String, required: false },
    whenDoYouSetTheTableScore: { type: String, required: false },
    whatDoesTheCarHaveThatIsDifferentFromABicycle: { type: String, required: false },
    whatDoesTheCarHaveThatIsDifferentFromABicycleScore: { type: String, required: false },
    howDoYouKnowIfSomeoneIsSick: { type: String, required: false },
    howDoYouKnowIfSomeoneIsSickScore: { type: String, required: false },
    whatDidYouDoTodayAtSchool: { type: String, required: false },
    whatDidYouDoTodayAtSchoolScore: { type: String, required: false },
    other1Group8: { type: String, required: false },
    other1Group8Score: { type: String, required: false },
    other2Group8: { type: String, required: false },
    other2Group8Score: { type: String, required: false },
    subtotalPointsGroup8: { type: String, required: false },
  },

  totalScore: {type: Number, required: false},
  classification: {type: String, required: false}
});

export interface IIntraverbalAssessmentEntity extends Omit<IIntraverbalAssessment, '_id'>, Document {}
