import { Schema, Document } from 'mongoose';
import { IOta } from 'src/features/occupational-therapy-anamnesis/types/ota';


export const OccupationalTherapyAnamnesisSchema = new Schema({
  _id: { type: Schema.Types.ObjectId, required: true, auto: true },
  dateOfApplication: { type: Date, default: Date.now },
  doctor: { type: String},
  patient: { type: Schema.Types.ObjectId, },
  birthDate: { type: String},
  gender: {type: String, enum: ['M', 'F']},
  age: { type: Number},
  diagnoses: { type: String},
  fatherName: { type: String},
  motherName: { type: String},
  contactPhone: { type: String},
  address: { type: String},
  consultationReason: { type: String},
  mainConcernOfResponsible: { type: String},
  clinicalHistory: {
    pregnancy: {type: String, enum: ['Planejada', 'Não planejada']},
    complicationsDuringPregnancy: { type: String},
    birth: {type: String, enum: ['Normal', 'Cesárea']},
    prematurity: {type: String, enum: ['Sim', 'Não']},
    gestationalWeeks: {type: Number},
    apgarAtBirth: {type: Number},
    neonatalHospitalization: {type: String, enum: ['Sim', 'Não']},
    hospitalizationTime: { type: String},
    pastDiseasesOrHospitalizations: { type: String},
  },
  neuropsychomotorDevelopment: {
    headControlMonths: {type: Number},
    sittingWithoutSupportMonths: {type: Number},
    crawlingMonths: {type: Number},
    walkingMonths: {type: Number},
    firstWordsMonths: {type: Number},
    sphincterControlYears: {type: Number},
    regressionOrLossOfSkills: { type: String},
  },
  activitiesOfDailyLiving: {
    feeding: {type: String, enum: ['Independente', 'Necessita de auxílio' , 'Alimentação por sonda']},
    feedingHelpDetails: { type: String},
    aversionToCertainFoods: {type: String, enum: ['Sim', 'Não']},
    aversionFoodDetails: { type: String},
    acceptsNewFoodsEasily: {type: String, enum: ['Sim', 'Não']},
    needsSpecificStrategiesForFeeding: {type: String, enum: ['Sim', 'Não']},
    feedingStrategies: { type: String},
    prefersSpecificFoodConsistency: { type: String},
    personalHygiene: {type: String, enum: ['Independente' , 'Com auxílio parcial' , 'Necessita de supervisão total']},
    hygieneDetails: { type: String},
    bathing: {type: String, enum: ['Independente' , 'Auxílio para partes específicas (especificar)' , 'Necessita de supervisão completa']},
    bathSpecificDetails: { type: String},
    dressing: {type: String, enum: ['Completa independência' , 'Dificuldade com botões, zíperes, etc' , 'Auxílio completo']},
    dressingDifficultyDetails: { type: String},
    sphincterControl: {type: String, enum: ['Total' , 'Parcial (usa fralda em determinadas situações)', 'Necessita de fralda o tempo todo']},
    specificSituationsForDiaper: { type: String},
    inToiletTraining: {type: String, enum: ['Sim', 'Não']},
    toiletTrainingDuration: { type: String},
    strategiesUsedByCaregiversOrSchool: { type: String},
  },
  signsOfReadiness: {
    signsOfReadiness: {type: String, enum: ['Percepção de xixi/cocô' , 'Desconforto com a fralda' , 'Ser capaz de apontar o que deseja' , 'Ficar seco por 2h ou mais' , 'Seguir comandos' , 'Ficar sentado de 3 a 5 minutos']},
    specificDifficultiesInToiletTraining: { type: String},
  },
  instrumentalActivitiesOfDailyLiving: {
    participatesInSchoolOrHomeTasks: {type: String, enum: ['Sim', 'Não']},
    taskDetails: { type: String},
  },
  schoolAndSocialRoutine: {
    enrolledInSchool: {type: String, enum: ['Sim', 'Não']},
    educationType: {type: String, enum: [ 'Regular' , 'Regular com apoio' , 'Especial']},
  },
  teacherReportedDifficulties: {
    participatesInGroupRecreationalActivities: {type: String, enum: ['Sim', 'Não']},
    interactionWithOtherChildrenAndAdults:  {type: String, enum: [ 'Busca interação' , 'Evita interação' , 'Prefere brincar sozinho']}, 
  },
  sensoryAndBehavioralAspects: {
    sensorySensitivities: {type: String, enum: ['Tátil' , 'Auditiva' , 'Visual' , 'Olfativa' , 'Outras']},
	  taskDetailsSensitivities: { type: String},
    repetitiveOrStereotypedBehaviors: {type: String, enum: ['Sim', 'Não']},
    repetitiveBehaviorsDescription: { type: String},
    responsesToRoutineChanges: {type: String, enum: ['Boa adaptação' ,'Dificuldade significativa']}, 
    behaviorCrises: {type: String, enum: ['Sim', 'Não']},
    crisesDetails: { type: String},
  },
  playAndLeisureAspects: {
    prefersStructuredOrFreePlay: {type: String, enum: ['Estruturadas' , 'Livres']}, 
    favoriteToysOrActivities: { type: String},
    difficultyStartingOrMaintainingPlay: {type: String, enum: ['Sim', 'Não']},
  },
  supportNetworkAndPreviousTreatments: {
    previousTherapies: {type: String, enum: ['Fonoaudiologia' , 'Fisioterapia' , 'Psicologia' , 'Outros']},  
    familyOrCaregiversInTherapies: { type: String},
  },
  responsibleGeneralObservations: {
    essentialObservationsForTreatmentPlanning: {type: String, enum: ['Sim', 'Não']},
    responsibleObservations: { type: String},
  },
});

export interface IOccupationalTherapyAnamnesisEntity extends Omit<IOta, '_id'>, Document {}