import {Schema, Document} from 'mongoose'
import { IPerformanceAssessmente } from "src/features/performance-assessment/types/performanceAssessment";

export const PerformanceAssessmentSchema = new Schema ({
    patient: { type: Schema.Types.ObjectId, ref: 'User' },
    doctor: { type: Schema.Types.ObjectId, ref: 'User' },
    pencilGrip: { type: String, enum: ['Preensão primitiva', ' Preensão palmar supinada', 'Preensão de transição ', ' Preensão madura']},
    writtenHypothesis: { type: String, enum: ['Não se aplica a faixa etária', ' Não realiza', ' Pictográfica', '  Pré silábica', ' Silábica', '  Alfabética']},
    writingWordsAndPhrases: { type: String, enum: ['Não se aplica a faixa etária', 'Não realiza', ' Reconhece letras', ' Reconhece sílabas', 'Autônomo em palavras', ' Autônomo em palavras e frases']},
    reading: { type: String, enum: ['Não se aplica a faixa etária', 'Não realiza', 'Rota lexical', ' Rota fonológica']},
    numbersAndQuantity: { type: String, enum: ['Não se aplica a faixa etária', '  Não realiza', ' Reconhece', 'Nomeia', 'Quantifica']},
    mathematicalOperations: { type: String, 
        enum: [
        'Não se aplica a faixa etária', 
        'Não realiza',
        'Fase sensório motor',
        ' Fase pré-operatório',
        'Fase operatório concreto',
        ' Fase operatório formal'
    ] },
    executiveFunctions: { type: String, enum:[
        'Inibição',
        'Memória de trabalho',
        'Flexibilidade cognitiva',
        'Planejar',
        'Tomar decisões',
        'Estabelecer metas',
        'Antecipar',
        'Organizar',
        'Ter fluidez'
    ] },
    assessment2a4Years: {
        ei02cg01: { type: Boolean },
        ei02cg02: { type: Boolean },
        ei02cg03: { type: Boolean },
        ei02cg04: { type: Boolean },
        ei02cg05: { type: Boolean },
    },
    assessment5a6Years:{
        ei03cg01: { type: Boolean },
        ei03cg02: { type: Boolean },
        ei03cg03: { type: Boolean },
        ei03cg04: { type: Boolean },

    },
    linesSoundsColorsAndShapes2a4Years: {
        ei02ts01: { type: Boolean },
        ei02ts02: { type: Boolean },
        ei02ts03: { type: Boolean },
    },
    linesSoundsColorsAndShapes5a6Years: {
    ei03ts01: { type: Boolean },
    ei03ts02: { type: Boolean },
    ei03ts03: { type: Boolean },
    },
    listeningSpeakingThinkingAndImagining2a4Years: {
        ei02ef01: { type: Boolean },
        ei02ef02: { type: Boolean },
        ei02ef03: { type: Boolean },
        ei02ef04: { type: Boolean },
        ei02ef05: { type: Boolean },
        ei02ef06: { type: Boolean },
        ei02ef07: { type: Boolean },
        ei02ef08: { type: Boolean },
        ei02ef09: { type: Boolean },

    },
    listeningSpeakingThinkingAndImagining5a6Years:{
        ei03ef01: { type: Boolean },
        ei03ef02: { type: Boolean },
        ei03ef03: { type: Boolean },
        ei03ef04: { type: Boolean },
        ei03ef05: { type: Boolean },
        ei03ef06: { type: Boolean },
        ei03ef07: { type: Boolean },
        ei03ef08: { type: Boolean },
        ei03ef09: { type: Boolean },
    },
    spacesTimesQuantitiesRelationsAndTransformations2a4Years: {
        ei02et01: { type: Boolean },
        ei02et02: { type: Boolean },
        ei02et03: { type: Boolean },
        ei02et04: { type: Boolean },
        ei02et05: { type: Boolean },
        ei02et06: { type: Boolean },
        ei02et07: { type: Boolean },
        ei02et08: { type: Boolean },

    },
    spacesTimesQuantitiesRelationsAndTransformations5a6Years: {
        ei03et01: { type: Boolean },
        ei03et02: { type: Boolean },
        ei03et03: { type: Boolean },
        ei03et04: { type: Boolean },
        ei03et05: { type: Boolean },
        ei03et06: { type: Boolean },
        ei03et07: { type: Boolean },
        ei03et08: { type: Boolean },
    },
    theMeTheOtherAndTheUs2a4Years:{
        ei02eo01: { type: Boolean },
        ei02eo02: { type: Boolean },
        ei02eo03: { type: Boolean },
        ei02eo04: { type: Boolean },
        ei02eo05: { type: Boolean },
        ei02eo06: { type: Boolean },
        ei02eo07: { type: Boolean },

    },
    theMeTheOtherAndTheUs5a6Years:{
        ei03eo01: { type: Boolean },
        ei03eo02: { type: Boolean },
        ei03eo03: { type: Boolean },
        ei03eo04: { type: Boolean },
        ei03eo05: { type: Boolean },
        ei03eo06: { type: Boolean },
        ei03eo07: { type: Boolean },
    },
    SummaryOfLearningTheSelfTheOtherAndTheUs: {
        respectemotions: { type: Boolean },
        actingroup: { type: Boolean },
        knowsocialrules: { type: Boolean },
    },
    SummaryOfLearningBodyGesturesAndMovements: {
        careforhealth: { type: Boolean },
        autonomyinhygiene: { type: Boolean },
        usebodyintentionally: { type: Boolean },
        coordinatemanualskills: { type: Boolean },
    },
    SummaryOfLearningLinesSoundsColorsAndShapes: {
        discriminatesounds: { type: Boolean },
        expressvisually: { type: Boolean },
        relatewithother: { type: Boolean },
    },
    SummaryOfLearningListeningSpeakingThinkingAndImagining: {
        expressideas: { type: Boolean },
        argumentandreport: { type: Boolean },
        listenunderstand: { type: Boolean },
        knowdifferenttext: { type: Boolean },
    },
    SummaryOfLearningSpacesTimesQuantitiesRelationsAndTransformations: {
        identifyandcompare: { type: Boolean },
        interactwithenviroment: { type: Boolean },
        usevocabulary: { type: Boolean },
        useunitsofmeasure: { type: Boolean },
        identifyandregister: { type: Boolean },
    },
    PortugueseLanguage1year: {
        ef01lp04: { type: Boolean },
        ef01lp05: { type: Boolean },
        ef01lp11: { type: Boolean },
        ef01lp13: { type: Boolean },
        ef01lp02: { type: Boolean },
        ef01lp01: { type: Boolean },
    },
    math1Year:{
        ef01ma01: { type: Boolean },
        ef01ma02: { type: Boolean },
        ef01ma04: { type: Boolean },
        ef01ma06: { type: Boolean },
        ef01ma15: { type: Boolean },
        ef01ma21: { type: Boolean },
    },
    PortugueseLanguage2years: {
        ef02lp02: { type: Boolean },
        ef02lp04: { type: Boolean },
        ef02lp07: { type: Boolean },
        ef12lp19: { type: Boolean },
        ef12lp01: { type: Boolean },
        ef12lp04: { type: Boolean },
    },
    math2Years:{
        ef02ma01: { type: Boolean },
        ef02ma03: { type: Boolean },
        ef02ma04: { type: Boolean },
        ef02ma05: { type: Boolean },
        ef02ma06: { type: Boolean },
        ef02ma09: { type: Boolean },
    },
    PortugueseLanguage3years: {
        ef03lp02: { type: Boolean },
        ef03lp05: { type: Boolean },
        ef35lp07: { type: Boolean },
        ef35lp12: { type: Boolean },
        ef35lp27: { type: Boolean },
    },
    math3Years:{
        ef03ma01: { type: Boolean },
        ef03ma03: { type: Boolean },
        ef03ma06: { type: Boolean },
        ef03ma07: { type: Boolean },
        ef03ma13: { type: Boolean },
        ef03ma23: { type: Boolean },
    },
    PortugueseLanguage4years: {
        ef04lp01: { type: Boolean },
        ef04lp05: { type: Boolean },
        ef04lp21: { type: Boolean },
        ef35lp12_4: { type: Boolean },
        ef35lp29: { type: Boolean },
    },
    math4Years:{
        ef04ma01: { type: Boolean },
        ef04ma02: { type: Boolean },
        ef04ma03: { type: Boolean },
        ef04ma04: { type: Boolean },
        ef04ma15: { type: Boolean },
        ef04ma22: { type: Boolean },
    },
    PortugueseLanguage5years: {
        ef05lp01: { type: Boolean },
        ef05lp03: { type: Boolean },
        ef05lp04: { type: Boolean },
        ef05lp26: { type: Boolean },
        ef15lp12: { type: Boolean },
        ef35lp12_5: { type: Boolean },
    },
    math5Years:{
        ef05ma01: { type: Boolean },
        ef05ma02: { type: Boolean },
        ef05ma07: { type: Boolean },
        ef05ma08: { type: Boolean },
        ef05ma10: { type: Boolean },
        ef05ma13: { type: Boolean }
    },
    observartions: {type: String},
})


export interface IPerformanceAssessmenteEntity extends Omit<IPerformanceAssessmente, '_id'>, Document {}