import { Schema } from "mongoose"
import { IPgpse } from "src/features/portage-guideto-preschool-education/types/portageGuidetoPreschoolEducation"



export const PortageGuidetoPreschoolEducationSchema = new Schema ({
    _id: { type: Schema.Types.ObjectId, required: true, auto: true },
    //name: { type: Schema.Types.ObjectId, required: true, ref: 'User' },
    //birthDay: { type: String, required: false, ref: 'User' },
    //Date: { type: Date, required: true},
    socialization0To1Year: { 
        observesAPersonMovingInTheirVisualField: { type: Boolean },
        smilesInResponseToAdultAttention: { type: Boolean },
        vocalizesInResponseToAttention: { type: Boolean },
        looksAtOwnHandSmilingOrVocalizing: { type: Boolean },
        respondsToFamilyCircleSmilingVocalizingOrStoppingCrying: { type: Boolean },
        smilesInResponseToOthersFacialExpressions: { type: Boolean },
        smilesAndVocalizesWhenSeeingImageInMirror: { type: Boolean },
        caressesOrTouchesAdultsFacesPullsHairNoseGlassesEtc: { type: Boolean },
        reachesTowardsAnOfferedObject: { type: Boolean },
        reachesArmsTowardsFamilyMembers: { type: Boolean },
        extendsHandAndTouchesOwnReflectedImageInMirror: { type: Boolean },
        holdsAndExaminesGivenObjectFor1Minute: { type: Boolean },
        shakesOrSqueezesAnObjectPlacedInHandProducingInvoluntarySounds: { type: Boolean },
        playsAloneFor10Minutes: { type: Boolean },
        seeksEyeContactWhenSomeonePaysAttentionFor2To3Minutes: { type: Boolean },
        playsAloneWithoutComplainingFor15To20MinutesNearAnAdult: { type: Boolean },
        vocalizesToGetAttention: { type: Boolean },
        imitatesAdultInPeekABooGames: { type: Boolean },
        clapsHandsImitatingAnAdult: { type: Boolean },
        wavesHandImitatingAnAdult: { type: Boolean },
        raisesArmsToExpressBigImitatingAnAdult: { type: Boolean },
        offersSomethingButDoesNotAlwaysDeliver: { type: Boolean },
        hugsCaressesAndKissesFamilyMembers: { type: Boolean },
        respondsToOwnNameLookingOrExtendingArmToBePickedUp: { type: Boolean },
        squeezesOrShakesToyToProduceSoundsInImitation: { type: Boolean },
        manipulatesToyOrObject: { type: Boolean },
        extendsAToyOrObjectToAnAdultAndDeliversIt: { type: Boolean },
        imitatesMovementsOfOtherChildrenWhilePlaying: { type: Boolean }
     },
    socialization1To2Years: { 
        imitatesAnAdultInASimpleTask: { type: Boolean },
        playsNextToAnotherChildEachPerformingDifferentTasks: { type: Boolean },
        takesPartInAPlayWithAnotherChildFor2To5Minutes: { type: Boolean },
        acceptsParentsAbsenceAlthoughMayComplain: { type: Boolean },
        activelyExploresItsEnvironment: { type: Boolean },
        performsManipulativeActivityWithAnotherPerson: { type: Boolean },
        hugsAndCarriesADollOrSoftToy: { type: Boolean },
        repeatsActionsThatProduceLaughterAndAttention: { type: Boolean },
        givesABookForAnAdultToReadOrForBothToShare: { type: Boolean },
        pullsAPersonToShowThemSomething: { type: Boolean },
        withdrawsHandOrSaysNoWhenNearForbiddenObjectAndSomeoneRemindsIt: { type: Boolean },
        whenPlacedInChairOrChangingTableWaitsToBeAttended: { type: Boolean },
        playsWith2Or3ChildrenOfSameAge: { type: Boolean },
        sharesAnObjectOrFoodWithAnotherChild: { type: Boolean },
        greetsPeersOrAdultsWhenReminded: { type: Boolean }
     },
    socialization2To3Years: {
        obeysParentsOrdersAtLeastHalfTheTime: { type: Boolean },
        seeksOrTakesAnObjectOrPersonWhenAsked: { type: Boolean },
        paysAttentionToStoryOrMusicFor5To10Minutes: { type: Boolean },
        saysPleaseOrThankYouWhenReminded: { type: Boolean },
        triesToHelpParentsPerformTasksByDoingPartOfIt: { type: Boolean },
        playsAtWearingAdultsClothes: { type: Boolean },
        makesAChoiceWhenAsked: { type: Boolean },
        demonstratesUnderstandingOfFeelingsExpressingThem: { type: Boolean }
     },
    socialization3To4Years: { 
        singsAndDancesWhenHearingMusic: { type: Boolean },
        followsRulesOfAGameImitatingActionsOfOtherChildren: { type: Boolean },
        greetsFamilyMembersWithoutBeingReminded: { type: Boolean },
        followsRulesInGroupGamesDirectedByAdults: { type: Boolean },
        asksPermissionToPlayWithAToyBeingUsedByAnotherChild: { type: Boolean },
        saysPleaseAndThankYouWithoutBeingRemindedHalfTheTime: { type: Boolean },
        answersThePhoneCallingAnAdultAndSpeakingWithFamilyMembers: { type: Boolean },
        waitsItsTurn: { type: Boolean },
        followsRulesInGamesDirectedByAnOlderChild: { type: Boolean },
        obeysAdultsOrders75PercentOfTheTime: { type: Boolean },
        staysInItsOwnYardOrGarden: { type: Boolean },
        playsNearOtherChildrenTalkingToThemWhileWorkingOnOwnProject30Minutes: { type: Boolean }
    },
    socialization4To5Years: { 
        asksForHelpWhenHavingDifficulties: { type: Boolean },
        contributesToAdultConversation: { type: Boolean },
        repeatsRhymesSongsOrDancesForOthers: { type: Boolean },
        doesATaskAloneFor20To30Minutes: { type: Boolean },
        apologizesWithoutBeingReminded75PercentOfTheTime: { type: Boolean },
        waitsItsTurnInPlayInvolving8To9Children: { type: Boolean },
        playsWith2To3ChildrenFor20MinutesInAnActivityInvolvingCooperation: { type: Boolean },
        whenInPublicPresentsASociallyAcceptableBehavior: { type: Boolean },
        asksPermissionToUseOthersObjects75PercentOfTheTime: { type: Boolean }
    },
    socialization5To6Years: {
        expressesItsFeelings: { type: Boolean },
        playsWith4To5ChildrenInCooperativeActivityFor20MinutesWithoutSupervision: { type: Boolean },
        explainsToOthersTheRulesOfTheGameOrActivity: { type: Boolean },
        imitatesAdultRoles: { type: Boolean },
        collaboratesInConversationDuringMeals: { type: Boolean },
        followsRulesOfAGameInvolvingVerbalReasoning: { type: Boolean },
        comfortsPeersWhenTheyAreSad: { type: Boolean },
        choosesItsOwnFriends: { type: Boolean },
        plansAndBuildsUsingSimpleTools: { type: Boolean },
        setsGoalsForItselfAndPerformsActivityToAchieveThem: { type: Boolean },
        dramatizesExcerptsFromStoriesPlayingARoleOrUsingPuppets: { type: Boolean }
    },
    language0To1Years: {
        repeatsSoundsMadeByOtherPeople: { type: Boolean },
        repeatsSameSyllable2To3Times: { type: Boolean },
        respondsToGesturesWithGestures: { type: Boolean },
        obeysASimpleOrderWhenAccompaniedByIndicativeGestures: { type: Boolean },
        interruptsActivityWhenToldNo75PercentOfTheTime: { type: Boolean },
        respondsToSimpleQuestionsWithNonVerbalAnswers: { type: Boolean },
        combines2DifferentSyllablesWhenTryingToVerbalize: { type: Boolean },
        imitatesIntonationPatternsOfOthersVoice: { type: Boolean },
        usesAWordFunctionallyToIndicateObjectsOrPeople: { type: Boolean },
        vocalizesInResponseToOtherPeoplesSpeech: { type: Boolean }
    },
    language1To2Years: {
        says5DifferentWords: { type: Boolean },
        asksForMore: { type: Boolean },
        saysDone: { type: Boolean },
        obeys3DifferentOrdersThatAreNotAccompaniedByIndicativeGestures: { type: Boolean },
        managesToGiveOrShowWhenAsked: { type: Boolean },
        pointsTo12ObjectsWhenNamed: { type: Boolean },
        pointsTo3To5FiguresInABook: { type: Boolean },
        pointsTo3PartsOfOwnBody: { type: Boolean },
        saysOwnNameOrNicknameWhenAsked: { type: Boolean },
        respondsToTheQuestionWhatIsThis: { type: Boolean },
        combinesWordsAndGesturesToExpressWishes: { type: Boolean },
        names5FamilyMembersIncludingAnimals: { type: Boolean },
        names4Toys: { type: Boolean },
        producesAnimalSoundsOrNamesThemByTheSound: { type: Boolean },
        asksForKnownFoodsByNameWhenShown: { type: Boolean },
        asksQuestionsVaryingIntonationOfVoice: { type: Boolean },
        names3BodyPartsOnADollOrAnotherPerson: { type: Boolean },
        respondsToYesNoQuestions: { type: Boolean }
    },
    language2To3Years: {
        combinesNounsOrAdjectivesAndNounsIn2WordSentences: { type: Boolean },
        combinesNounAndVerbIn2WordSentences: { type: Boolean },
        usesAWordToIndicateThatWantsToGoToTheBathroom: { type: Boolean },
        combinesVerbOrNounWithThereAndHereIn2WordSentences: { type: Boolean },
        combines2WordstoExpressPossession: { type: Boolean },
        usesNoInSpeech: { type: Boolean },
        respondsToTheQuestionWhatIsDoingForHabitualActivity: { type: Boolean },
        respondsToQuestionsLikeWhereIsObject: { type: Boolean },
        namesFamiliarEnvironmentalSounds: { type: Boolean },
        givesMoreThanOneObjectWhenUsingThePluralFormInTheRequest: { type: Boolean },
        whenSpeakingRefersToItselfByName: { type: Boolean },
        pointsToFiguresOfCommonObjectsDescribedByUseUpTo10WhatIsUsedToEatSpoon: { type: Boolean },
        showsAgeByFingers: { type: Boolean },
        saysSexWhenAsked: { type: Boolean },
        obeysTheSequenceOfTwoRelatedOrders: { type: Boolean },
        usesTheVerbFormInTheGerund: { type: Boolean },
        employsRegularPluralForms: { type: Boolean },
        employsSomeIrregularFormsOfVerbsInThePastSystematically: { type: Boolean },
        asksQuestionsLikeWhatIsThis: { type: Boolean },
        controlsVolumeOfVoice90PercentOfTheTime: { type: Boolean },
        usesThisAndThatInSpeech: { type: Boolean },
        employsIsAndIsLocatedInSimpleSentences: { type: Boolean },
        saysIMeMineInsteadOfOwnName: { type: Boolean },
        pointsToObjectsAndSaysTheyAreNotOtherThings: { type: Boolean },
        respondsToTheQuestionWhoGivingAName: { type: Boolean },
        employsPossessiveFormsOfNouns: { type: Boolean },
        usesArticlesWhenSpeaking: { type: Boolean },
        usesNounsThatIndicateAGroupOrCategory: { type: Boolean },
        usesTheVerbsToBeToExistAndToHaveInThePresentWithFewErrors: { type: Boolean },
        saysIfObjectsAreOpenOrClosed: { type: Boolean }
    },
    language3To4Years: {
        expressesDiminutivesAndAugmentativesWhenSpeaking: { type: Boolean },
        paysAttentionFor5MinutesToAReadStory: { type: Boolean },
        obeysSequenceOf2UnrelatedOrders: { type: Boolean },
        saysFullNameWhenAsked: { type: Boolean },
        respondsSimpleQuestionsInvolvingHow: { type: Boolean },
        employsRegularVerbsInThePast: { type: Boolean },
        reportsImmediateExperiences: { type: Boolean },
        saysHowCommonObjectsAreUsed: { type: Boolean },
        expressesFutureActionsUsingVerbsToGoToHaveAndToWant: { type: Boolean },
        usesMasculineAndFeminineAppropriatelyInSpeech: { type: Boolean },
        usesImperativeFormsOfVerbsWhenAskingForFavors: { type: Boolean },
        tells2FactsInOrderOfOccurrence: { type: Boolean }
    },
    language4To5Years: {
        obeysASequenceInvolving3Orders: { type: Boolean },
        demonstratesUnderstandingOfReflexiveVerbsUsingThemOccasionallyExHeGotHurt: { type: Boolean },
        managesToIdentifyObjectsFiguresThatFormAPairUponRequest: { type: Boolean },
        employsFutureWhenSpeaking: { type: Boolean },
        usesSentencesComposedByCoordination: { type: Boolean },
        managesToIdentifyTheTopAndBottomPartOfObjectsWhenRequested: { type: Boolean },
        employsOccasionallyTheConditionalWhenSpeakingCouldWouldCouldWouldMake: { type: Boolean },
        managesToIdentifyAbsurditiesInFigures: { type: Boolean },
        employsTheFollowingWordsBrotherSisterGrandmotherGrandfather: { type: Boolean },
        completesSentencesWithAntonyms: { type: Boolean },
        tellsAKnownStoryWithoutHelpOfFigures: { type: Boolean },
        inAFigureNamesTheObjectThatDoesNotBelongToACertainCategory: { type: Boolean },
        saysIfTwoWordsRhymeOrNot: { type: Boolean },
        usesComplexSentencesComposedBySubordination: { type: Boolean },
        saysIfASoundIsLoudOrSoft: { type: Boolean }
    },
    language5To6Years: {
        managesToIndicateSomeManyAndSeveralElements: { type: Boolean },
        saysOwnAddress: { type: Boolean },
        saysOwnPhoneNumber: { type: Boolean },
        pointsToTheSetThatHasMoreLessOrFewElements: { type: Boolean },
        tellsSimpleJokes: { type: Boolean },
        reportsDailyExperiences: { type: Boolean },
        describesALocationOrMovementThroughOrBetweenAwayFromFromSinceToOverUpTo: { type: Boolean },
        answersTheQuestionWhyWithAnExplanation: { type: Boolean },
        ordersAndTellsAStoryOf2To5episodesInTheCorrectSequence: { type: Boolean },
        definesWords: { type: Boolean },
        respondsAppropriatelyToTheQuestionWhatIsTheOppositeOf: { type: Boolean },
        respondsToTheQuestionWhatHappensIf: { type: Boolean },
        usesYesterdayAndTomorrowCorrectly: { type: Boolean },
        asksTheMeaningOfNewOrKnownQuestions: { type: Boolean }
    },
    cognition0To1Year: {
        removesAClothFromFaceThatObscuresVision: { type: Boolean },
        looksForObjectThatHasBeenRemovedFromItsVisualField: { type: Boolean },
        removesAnObjectFromAReceptacleByPuttingHandInsideIt: { type: Boolean },
        placesAnObjectInAReceptacleImitatingAnAdult: { type: Boolean },
        placesAnObjectInAReceptacleWhenGivenInstructions: { type: Boolean },
        shakesAToyThatProducesSoundHangingFromAString: { type: Boolean },
        placesThreeObjectsInAReceptacleAndEmptiesIt: { type: Boolean },
        transfersAnObjectFromOneHandToAnotherToPickUpAnotherObject: { type: Boolean },
        dropsAndPicksUpAToy: { type: Boolean },
        discoversAnObjectHiddenUnderAReceptacle: { type: Boolean },
        pushes3BlocksAsIfItWereATrain: { type: Boolean },
        removesACircleFromABoardByImitation: { type: Boolean },
        placesARoundPinInAPinBoardWhenRequested: { type: Boolean },
        performsSimpleGesturesWhenRequested: { type: Boolean }
    },
    cognition1To2Years: {
        removes6ObjectsFromAReceptacleOneAtATime: { type: Boolean },
        pointsToAPartOfTheBody: { type: Boolean },
        stacks3BlocksGivenTheOrder: { type: Boolean },
        matchesSimilarObjects: { type: Boolean },
        scribblesOnPaper: { type: Boolean },
        pointsToItselfWhenAskedWhereIsName: { type: Boolean },
        places5RoundPinsGivenTheOrder: { type: Boolean },
        matchesObjectsWithTheFigureOfTheSameName: { type: Boolean },
        pointsToTheNamedFigure: { type: Boolean },
        turnsThePagesOfABook23AtATimeToFindTheNamedFigure: { type: Boolean }
    },
    cognition2To3Years: {
        findsACertainBookWhenRequested: { type: Boolean },
        completesA3PieceJigsawPuzzle: { type: Boolean },
        names4CommonObjectsInFigures: { type: Boolean },
        drawsAVerticalLineImitatingAnAdult: { type: Boolean },
        drawsAHorizontalLineImitatingAnAdult: { type: Boolean },
        copiesACircle: { type: Boolean },
        matchesObjectsWithTheSameTexture: { type: Boolean },
        pointsToSmallAndBigWhenRequested: { type: Boolean },
        drawsAPlusSignImitatingAnAdult: { type: Boolean },
        matches3Colors: { type: Boolean },
        placesObjectsInsideOnTopAndUnderAReceptacleGivenTheOrder: { type: Boolean },
        namesObjectsWhenHearsTheNoiseTheyMake: { type: Boolean },
        mountsA4PieceFittingToy: { type: Boolean },
        namesActionsInFiguresWhatIsDoing: { type: Boolean },
        matchesGeometricShapeWithTheFigureOfTheSame: { type: Boolean },
        stacks5OrMoreRingsOnARodInOrder: { type: Boolean }
    },
    cognition3To4Years: {
        namesObjectsAsBeingBigOrSmall: { type: Boolean },
        pointsTo10PartsOfTheBodyWhenRequested: { type: Boolean },
        pointsToBoyAndGirlGivenTheOrder: { type: Boolean },
        saysIfAnObjectIsHeavyOrLight: { type: Boolean },
        unites2PartsOfAFigureToFormTheWhole: { type: Boolean },
        describes2EventsOrCharactersFromAFamiliarStoryOrTvProgram: { type: Boolean },
        repeatsGamesRhymesOrSongsThatInvolveCoordinatedMovements: { type: Boolean },
        matches3OrMoreObjects: { type: Boolean },
        pointsToLongOrShortObjects: { type: Boolean },
        associatesCorrespondingObjectsExSockShoe: { type: Boolean },
        countsUpTo3ImitatingAnAdult: { type: Boolean },
        groupsObjectsIntoCategories: { type: Boolean },
        tracesAVInImitation: { type: Boolean },
        tracesADiagonalLineGivenTheExample: { type: Boolean },
        countsUpTo10ObjectsImitatingAnAdult: { type: Boolean },
        buildsABridgeWith3BlocksByImitation: { type: Boolean },
        matchesASequenceOrPatternSizeColorOfBlocksOrBeads: { type: Boolean },
        copiesASeriesOfInterconnectedV: { type: Boolean },
        addsALegOrArmToAnIncompleteDrawingOfTheHumanFigure: { type: Boolean },
        completesA6PiecePuzzle: { type: Boolean },
        indicatesIfObjectsAreEqualOrDifferent: { type: Boolean },
        drawsASquareImitatingAnAdult: { type: Boolean },
        names3ColorsBeingRequested: { type: Boolean },
        names3GeometricShapesSquareTriangleAndCircle: { type: Boolean }
    },
    cognition4To5Years: {
        picksUpFrom1To5ObjectsWhenRequested: { type: Boolean },
        names5DifferentTextures: { type: Boolean },
        copiesATriangleWhenRequested: { type: Boolean },
        remembers4ObjectsThatHadBeenSeenInAFigure: { type: Boolean },
        saysTheTimeOfTheDayAssociatedWithEachActivity: { type: Boolean },
        repeatsFamiliarRhymes: { type: Boolean },
        saysIfAnObjectIsHeavierOrLighterObjectsWithADifferenceOf05Kilo: { type: Boolean },
        saysWhatIsMissingWhenAnObjectIsRemovedFromAGroupOf3Objects: { type: Boolean },
        names8Colors: { type: Boolean },
        identifiesTheValueOf3Coins: { type: Boolean },
        matchesSymbolsLettersAndNumbers: { type: Boolean },
        saysTheColorOfNamedObjects: { type: Boolean },
        reports5MainFactsOfAStoryTold3Times: { type: Boolean },
        drawsHumanFigureHeadTorsoAnd4Limbs: { type: Boolean },
        sings5VersesOfASong: { type: Boolean },
        buildsAPyramidOf10BlocksByImitation: { type: Boolean },
        namesObjectsAsBeingLongOrShort: { type: Boolean },
        placesObjectsBehindBesideOrNextToOthers: { type: Boolean },
        makesEqualSetsOf10ObjectsAccordingToModel: { type: Boolean },
        namesOrPointsToTheMissingPartOfTheFigure: { type: Boolean },
        countsFrom1To20: { type: Boolean },
        identifiesTheObjectThatIsPlacedInTheMiddleInFirstAndLastPlace: { type: Boolean }
    },
    cognition5To6Years: {
        countsUpTo20ObjectsAndAnswersAppropriatelyToTheQuestionHowManyDidYouCount: { type: Boolean },
        names10Numerals: { type: Boolean },
        identifiesWhichIsItsLeftAndWhichIsItsRight: { type: Boolean },
        saysTheVowelsInOrder: { type: Boolean },
        writesOwnNameWithBlockLetters: { type: Boolean },
        names5LettersOfTheAlphabet: { type: Boolean },
        ordersObjectsInSequenceOfLengthAndWidth: { type: Boolean },
        namesTheUppercaseLettersOfTheAlphabet: { type: Boolean },
        placesNumeralsFrom1To10InTheCorrectSequence: { type: Boolean },
        identifiesThePositionOfObjectsInFirstSecondAndThirdPlace: { type: Boolean },
        namesTheLowercaseLettersOfTheAlphabet: { type: Boolean },
        matchesUppercaseLettersWithLowercaseOnes: { type: Boolean },
        pointsToNumeralsFrom1To25: { type: Boolean },
        copiesARhombus: { type: Boolean },
        completesASimpleLabyrinth: { type: Boolean },
        saysTheDaysOfTheWeekInOrder: { type: Boolean },
        addsAndSubtractsCombinationsOfUpTo3Elements: { type: Boolean },
        saysTheMonthAndDayOfOwnBirthday: { type: Boolean },
        reads10PrintedWords: { type: Boolean },
        predictsWhatWillOccur: { type: Boolean },
        pointsToWholeAndHalfObjects: { type: Boolean },
        countsFromMemoryFrom1To100AskToStopAt40AndContinueAt80IfNoErrorsUntil40: { type: Boolean }
    },
    selfCare0To1Year: { 
        sucksAndSwallowsLiquids: { type: Boolean },
        eatsPorridgeOrSoup: { type: Boolean },
        extendsHandsTowardsBabyBottleTryingToGrabIt: { type: Boolean },
        eatsPureedFoodsGivenByParents: { type: Boolean },
        holdsBabyBottleWithoutHelpWhileDrinking: { type: Boolean },
        bringsBottleToMouthOrRefusesItPushingItAway: { type: Boolean },
        eatsMashedFoodsGivenByParents: { type: Boolean },
        drinksFromAMugHeldByParents: { type: Boolean },
        eatsSemisolidFoodsGivenByParents: { type: Boolean },
        feedsItselfUsingFingers: { type: Boolean },
        holdsTheMugWithBothHandsAndDrinks: { type: Boolean },
        bringsASpoonFullOfFoodToMouthWithHelp: { type: Boolean },
        stretchesArmsAndLegsWhenBeingDressed: { type: Boolean }
    },
    selfCare1To2Years: {
        eatsWithSpoonIndependently: { type: Boolean },
        holdsMugWithOneHandAndDrinks: { type: Boolean },
        putsHandInWaterAndPatsFaceWithWetHandsImitatingSomeone: { type: Boolean },
        sitsOnAPottyOrChildsToiletFor5Minutes: { type: Boolean },
        putsAHatOnHeadAndRemovesIt: { type: Boolean },
        takesOffSocks: { type: Boolean },
        pushesArmsThroughSleevesAndFeetThroughTrouserLegs: { type: Boolean },
        takesOffShoesWhenLacesAreUntied: { type: Boolean },
        takesOffCoatWhenUnbuttoned: { type: Boolean },
        takesOffTrousersWhenUnbuttoned: { type: Boolean },
        pullsALargeZipperUpAndDown: { type: Boolean },
        usesWordsOrGesturesIndicatingNeedToGoToTheBathroom: { type: Boolean }
    },
    selfCare2To3Years: {
        eatsAloneUsingSpoonOrMugSpillingALittleFoodOrLiquid: { type: Boolean },
        whenGivenATowelDriesHandsAndFaceWithHelp: { type: Boolean },
        sucksLiquidFromTheGlassOrMugUsingAStraw: { type: Boolean },
        takesForkfuls: { type: Boolean },
        chewsAndSwallowsOnlyEdibleSubstances: { type: Boolean },
        driesHandsWithoutHelpWhenGivenATowel: { type: Boolean },
        warnsThatWantsToGoToTheBathroomEvenIfItIsTooLate: { type: Boolean },
        controlsOwnDrool: { type: Boolean },
        urinatesOrDefecatesWhenPlacedInPottyAtLeast3TimesAWeek: { type: Boolean },
        putsOnShoes: { type: Boolean },
        brushesTeethImitatingAnAdult: { type: Boolean },
        removesSimpleClothesThatHaveBeenUnbuttoned: { type: Boolean },
        usesTheBathroomToDefecateFailsOnlyOnceAWeek: { type: Boolean },
        obtainsWaterFromAFaucetWithoutHelp: { type: Boolean },
        washesHandsAndFaceWithSoap: { type: Boolean },
        warnsThatWantsToGoToTheBathroomDuringTheDayInTime: { type: Boolean },
        hangsCoatOnAHookAtItsOwnHeight: { type: Boolean },
        staysDryWhenSleepingDuringTheDay: { type: Boolean },
        avoidsRisksExSharpEdgesOnFurnitureAndStairsWithoutHandrail: { type: Boolean },
        usesANapkinWhenRecommended: { type: Boolean },
        piercesTheForkInTheFoodTakingItToTheMouth: { type: Boolean },
        poursLiquidFromASmallPitcherIntoAGlassWithoutHelp: { type: Boolean },
        unfastensClothesFastenedWithASnapFastener: { type: Boolean },
        washesArmsAndLegsWhenGivenABath: { type: Boolean },
        putsOnSocks: { type: Boolean },
        wearsCoatJacketOrShirt: { type: Boolean },
        identifiesTheFrontPartOfClothes: { type: Boolean }
    },
    selfCare3To4Years: {
        feedsItselfAloneForEntireMeal: { type: Boolean },
        dressesItselfAloneNeedingHelpOnlyWhenThereAreJacketsOrTShirtsWithClosedCollarsOrButtonsAndFasteners: { type: Boolean },
        wipesNoseWhenReminded: { type: Boolean },
        wakesUpDry2MorningsAWeek: { type: Boolean },
        ifBoyUrinatesInTheToiletWhileStanding: { type: Boolean },
        dressesAndUndressesItselfAloneExceptForButtonsAndFasteners75PercentOfTheTime: { type: Boolean },
        fastensClothesWithSnapsOrHooks: { type: Boolean },
        blowsNoseWhenReminded: { type: Boolean },
        avoidsCommonDangersExBrokenGlass: { type: Boolean },
        hangsClothesOnAHangerAndPutsInClosetWhenAsked: { type: Boolean },
        brushesTeethWhenReceivesInstruction: { type: Boolean },
        putsOnGloves: { type: Boolean },
        putsOnBoots: { type: Boolean },
        unbuttonsLargeButtons: { type: Boolean },
        buttonsLargeButtons: { type: Boolean }
    },
    selfCare4To5Years: {
        cleansWhatItSpilledOnOwn: { type : Boolean },
        avoidsPoisonAndAllHarmfulSubstances: { type: Boolean },
        unbuttonsOwnClothes: { type: Boolean },
        buttonsOwnClothes: { type: Boolean },
        removesPlateAndCutleryFromTheTable: { type: Boolean },
        fitsZipperIntoItsTermination: { type: Boolean },
        washesHandsAndFace: { type: Boolean },
        usesAppropriateCutleryToEat: { type: Boolean },
        wakesUpAtNightToGoToTheBathroomOrWakesUpDry: { type: Boolean },
        cleansAndBlowsItsNose75PercentOfTheTimeWithoutBeingReminded: { type: Boolean },
        bathesAloneNeedingHelpOnlyToWashBackNeckAndEars: { type: Boolean },
        usesAKnifeToSpreadButterOnBread: { type: Boolean },
        tightensAndLoosensBeltsOrBuckles: { type: Boolean },
        dressesItselfAloneButDoesNotTieLaces: { type: Boolean },
        servesItselfAtTheTableWhileHoldingTheFoodPlatter: { type: Boolean },
        helpsSetTheTableCorrectlyWhenReceivesInstructions: { type: Boolean },
        brushesTeeth: { type: Boolean },
        goesToTheBathroomInTimeRemovesClothesUsesToiletPaperFlushesAndDressesWithoutHelp: { type: Boolean },
        combsOrBrushesHair: { type: Boolean },
        hangsClothesOnHangers: { type: Boolean },
        walksAroundTheNeighborhoodWithoutConstantSupervision: { type: Boolean },
        threadsLacesIntoShoes: { type: Boolean },
        tiesOrLacesShoelaces: { type: Boolean }
    },
    selfCare5To6Years: {
        isResponsibleForAWeeklyTaskAndPerformsItWhenReminded: { type: Boolean },
        selectsAppropriateClothingForClimateAndOccasion: { type: Boolean },
        stopsOnTheSidewalkLooksBothWaysAndCrossesTheStreetWithoutNeedingToBeReminded: { type: Boolean },
        servesItselfAtTheTableAndPassesThePotOfFoodToOthers: { type: Boolean },
        preparesOwnCupOfCoffeeWithMilk: { type: Boolean },
        isResponsibleForADailyTaskAtHome: { type: Boolean },
        adjustsTheTemperatureOfWaterForBathing: { type: Boolean },
        preparesOwnSnack: { type: Boolean },
        walksAloneUpToADistanceOf2BlocksFromHome: { type: Boolean },
        cutsTenderFoodsWithAKnife: { type: Boolean },
        findsTheBathroomInAPublicPlaceCorrectly: { type: Boolean },
        opensTheMilkPackage: { type: Boolean },
        picksUpATrayWithFoodCarryingItAndPlacingItOnTheTable: { type: Boolean },
        tiesTheLacesOnJacketsWithHood: { type: Boolean },
        fastensTheCarSeatBelt: { type: Boolean }
    },
    motorDevelopment0To1Year: { 
        reachesForAnObjectPlacedInFrontOfIt15To20Cm: { type: Boolean },
        grabsAnObjectPlacedInFrontOfIt8Cm: { type: Boolean },
        extendsArmsTowardAnObjectInFrontOfItAndGrabsIt: { type: Boolean },
        reachesForAPreferredObject: { type: Boolean },
        putsObjectsInMouth: { type: Boolean },
        raisesHeadAndTorsoSupportingSelfOnArmsWhenLyingOnStomach: { type: Boolean },
        raisesHeadAndTorsoSupportingSelfOnOneArm: { type: Boolean },
        touchesAndExploresObjectsWithMouth: { type: Boolean },
        inPronePositionTurnsToTheSideAndMaintainsThisPositionHalfTheTime: { type: Boolean },
        inPronePositionTurnsOnBack: { type: Boolean },
        inPronePositionMovesForwardTheEquivalentOfItsHeight: { type: Boolean },
        inSupinePositionRollsToTheSide: { type: Boolean },
        inSupinePositionTurnsFromStomachToBack: { type: Boolean },
        makesEffortToSitHoldingOntoAdultsFingers: { type: Boolean },
        turnsHeadEasilyWhenTheBodyIsSupported: { type: Boolean },
        sitsFor2Minutes: { type: Boolean },
        releasesAnObjectToGrabAnother: { type: Boolean },
        grabsAndDropsAnObjectPurposefully: { type: Boolean },
        standsWithMaximumSupport: { type: Boolean },
        whileStandingWithSupportJumpsUpAndDown: { type: Boolean },
        crawlsToGrabAnObjectDistantItsHeight: { type: Boolean },
        sitsSupportingSelfAlone: { type: Boolean },
        whileSittingTurnsToCraw: { type: Boolean },
        whileInPronePositionManagesToSit: { type: Boolean },
        sitsWithoutHandSupport: { type: Boolean },
        throwsObjectsAtRandom: { type: Boolean },
        swaysBackAndForthWhenCrawling: { type: Boolean },
        transfersObjectsFromOneHandToAnotherWhenSitting: { type: Boolean },
        retains2CubesOf25CmInOneHand: { type: Boolean },
        getsOnKnees: { type: Boolean },
        standsSupportingSelfOnSomething: { type: Boolean },
        usesPincerGripToPickUpObjects: { type: Boolean },
        crawls: { type: Boolean },
        whileCrawlingExtendsOneHandUpwards: { type: Boolean },
        standsWithMinimumSupport: { type: Boolean },
        licksFoodAroundMouth: { type: Boolean },
        maintainsSelfStandingAloneFor1Minute: { type: Boolean },
        knocksDownAnObjectThatIsInsideAReceptacle: { type: Boolean },
        turnsSeveralPagesOfABookAtTheSameTime: { type: Boolean },
        scoopsWithASpoonOrSpade: { type: Boolean },
        placesSmallObjectsInsideAReceptacle: { type: Boolean },
        whileStandingLowersItselfAndSits: { type: Boolean },
        clapsHands: { type: Boolean },
        walksWithMinimumSupport: { type: Boolean },
        takesAFewStepsWithoutSupport: { type: Boolean }
    },
    motorDevelopment1To2Years: {
        climbsStairsCrawling: { type: Boolean },
        placesItselfStandingWhileSitting: { type: Boolean },
        rollsABallImitatingAnAdult: { type: Boolean },
        climbsOntoAnAdultChairTurnsAndSits: { type: Boolean },
        puts4RingsOnASmallStake: { type: Boolean },
        removes25CmPinsFromABoardOrTray: { type: Boolean },
        fits25CmPinsIntoAFittingBoard: { type: Boolean },
        buildsATowerOf3Blocks: { type: Boolean },
        makesTracesOnPaperWithPencilOrCrayon: { type: Boolean },
        walksAlone: { type: Boolean },
        goesDownStairsSittingPuttingFeetFirst: { type: Boolean },
        sitsInASmallChair: { type: Boolean },
        crouchesAndReturnsToStand: { type: Boolean },
        pushesAndPullsToysWhenWalking: { type: Boolean },
        usesAChairOrRockingHorse: { type: Boolean },
        climbsStairsWithHelp: { type: Boolean },
        bendsTheBodyWithoutFallingToPickUpObjectsOnTheFloor: { type: Boolean },
        imitatesACircularMovement: { type: Boolean }
    },
    motorDevelopment2To3Years: {
        threads4LargeBeadsOnACordIn2Minutes: { type: Boolean },
        turnsLatchesOrDoorknobsOnDoors: { type: Boolean },
        jumpsInTheSamePlaceWithBothFeet: { type: Boolean },
        walksBackwards: { type: Boolean },
        goesDownStairsWithoutHelp: { type: Boolean },
        throwsABallToAnAdultAtA1HalfDistance: { type: Boolean },
        buildsATowerOf5To6Blocks: { type: Boolean },
        turnsPagesOfABookOneAtATime: { type: Boolean },
        unwrapsASmallObject: { type: Boolean },
        foldsAPaperInHalfImitatingAnAdult: { type: Boolean },
        dismantlesAndRebuildsPressureFitToys: { type: Boolean },
        unscrewsToysThatFitWithThreads: { type: Boolean },
        kicksALargeBallThatIsStill: { type: Boolean },
        makesBallsOfClayMudOrPlasticine: { type: Boolean },
        holdsThePencilBetweenTheThumbAndIndexFingerRestingItOnTheMiddleFinger: { type: Boolean },
        doesForwardTumbleWithHelp: { type: Boolean },
        hammersToFit5PinsInTheirHoles: { type: Boolean }
    },
    motorDevelopment3To4Years: {
        makesAPuzzleOf3Pieces: { type: Boolean },
        cutsSomethingIntoPiecesWithScissors: { type: Boolean },
        jumpsFromAHeightOf20Cm: { type: Boolean },
        kicksALargeBallWhenSentToYou: { type: Boolean },
        walksOnTiptoes: { type: Boolean },
        runs10StepsCoordinatingAndAlternatingTheMovementOfArmsAndFeet: { type: Boolean },
        pedalsWithTricycleTheDistanceOf1AndAHalfMeters: { type: Boolean },
        swingsOnASwingWhenItIsInMotion: { type: Boolean },
        climbsOnASlideOf120MTo180MAndSlidesDown: { type: Boolean },
        doesForwardTumbles: { type: Boolean },
        climbsStairsAlternatingFeet: { type: Boolean },
        marchesWalksInARhythmicalWay: { type: Boolean },
        parriesTheBallWithBothHands: { type: Boolean },
        drawsFiguresFollowingOutlinesOrDottedLines: { type: Boolean },
        cutsAlongAStraightLine20CmMovingSlightlyAwayFromTheLine: { type: Boolean }
    },
    motorDevelopment4To5Years: {
        standsOnOneFootWithoutSupportFor4To8Seconds: { type: Boolean },
        changesDirectionWhenRunning: { type: Boolean },
        walksOnABeamOrBoardMaintainingBalance: { type: Boolean },
        jumpsForward10TimesWithoutFalling: { type: Boolean },
        jumpsOverARopeSuspended5CmFromTheGround: { type: Boolean },
        jumpsBackwards6Times: { type: Boolean },
        reboundsAndCatchesALargeBall: { type: Boolean },
        joins2To3PiecesOfPlasticine: { type: Boolean },
        cutsAroundCurvedLines: { type: Boolean },
        fitsScrewObjects: { type: Boolean },
        goesDownStairsAlternatingFeet: { type: Boolean },
        pedalsATricycleMakingTurns: { type: Boolean },
        jumpsOnOneFoot5ConsecutiveTimes: { type: Boolean },
        cutsACircleIn5Cm: { type: Boolean },
        drawsSimpleEasilyIdentifiableFiguresExHouse: { type: Boolean },
        cutsAndPastesSimpleShapes: { type: Boolean }
    },
    motorDevelopment5To6Years: {
        writesUppercaseLettersIsolatedAndLargeAnywhereOnThePaper: { type: Boolean },
        walksOnABoardBackwardsForwardsAndSidewaysMaintainingBalance: { type: Boolean },
        walksWhileHopping: { type: Boolean },
        swingsOnASwingStartingAndMaintainingTheMovement: { type: Boolean },
        stretchesFingersTouchingThumbToEachOfThem: { type: Boolean },
        copiesCapitalLetters: { type: Boolean },
        climbsOnLaddersOrASlideOf3M: { type: Boolean },
        hammersANailWithAHammer: { type: Boolean },
        reboundsTheBallAsItWalksWithDirection: { type: Boolean },
        managesToColorWithoutGoingOutOfTheMargin95PercentOfTheTime: { type: Boolean },
        cutsOutFiguresWithoutLeavingMoreThan6MmFromTheMargin: { type: Boolean },
        usesPencilSharpener: { type: Boolean },
        copiesComplexDrawingsSchoolShip: { type: Boolean },
        tearsSimpleFiguresFromThePaper: { type: Boolean },
        foldsASquarePaper2XDiagonallyByImitation: { type: Boolean },
        catchesALightBallWithOneHand: { type: Boolean },
        jumpsRopeAlone: { type: Boolean },
        strikesABallWithAStickOrPieceOfWood: { type: Boolean },
        catchesAnObjectOnTheFloorWhileRunning: { type: Boolean },
        skatesADistanceOf3MOrUsesASkateboard: { type: Boolean },
        ridesABicycle: { type: Boolean },
        slidesDownAHillOfSandOrEarth: { type: Boolean },
        walksOrPlaysInASwimmingPoolHavingWaterUpToItsWaist: { type: Boolean },
        drivesAScooterGivingImpulseWithOneFootOnly: { type: Boolean },
        jumpsAndTurnsOnOneFoot: { type: Boolean },
        writesOwnNameWithBlockLettersInLinedNotebook: { type: Boolean },
        jumpsFromAHeightOf30CmAndFallsOnTiptoes: { type: Boolean },
        stopsOnOneFootWithoutSupportWithEyesClosedFor10Seconds: { type: Boolean },
        hangsFor10SecondsOnAHorizontalBar: { type: Boolean }
    },

    
}, { timestamps: true})

export interface IPortageGuidetoPreschoolEducationEntity extends Omit<IPgpse, '_id'>, Document {}