import { Schema } from "mongoose"
import { IPgpse } from "src/features/portage-guideto-preschool-education/types/portageGuidetoPreschoolEducation"
import { ResponseBoolean } from "src/features/portage-guideto-preschool-education/dto/create-portage-guideto-preschool-education.dto"
import { format } from "date-fns"




export const PortageGuidetoPreschoolEducationSchema = new Schema({
    _id: { type: Schema.Types.ObjectId, required: true, auto: true },
    patient: { type: Schema.Types.ObjectId, required: true, ref: 'User' },
    birthDay: { type: String, get: (data:Date) => data ? format(data,'dd/MM/yyyy') : undefined  },
    doctor: { type: Schema.Types.ObjectId, required: true, ref: 'User' },
    Date: { type: String, get: (data:Date) => data ? format(data,'dd/MM/yyyy') : undefined  },
    socialization0To1Year: {
        observesAPersonMovingInTheirVisualField: { type: String, ResponseBoolean },
        smilesInResponseToAdultAttention: { type: String, ResponseBoolean },
        vocalizesInResponseToAttention: { type: String, ResponseBoolean },
        looksAtOwnHandSmilingOrVocalizing: { type: String, ResponseBoolean },
        respondsToFamilyCircleSmilingVocalizingOrStoppingCrying: { type: String, ResponseBoolean },
        smilesInResponseToOthersFacialExpressions: { type: String, ResponseBoolean },
        smilesAndVocalizesWhenSeeingImageInMirror: { type: String, ResponseBoolean },
        caressesOrTouchesAdultsFacesPullsHairNoseGlassesEtc: { type: String, ResponseBoolean },
        reachesTowardsAnOfferedObject: { type: String, ResponseBoolean },
        reachesArmsTowardsFamilyMembers: { type: String, ResponseBoolean },
        extendsHandAndTouchesOwnReflectedImageInMirror: { type: String, ResponseBoolean },
        holdsAndExaminesGivenObjectFor1Minute: { type: String, ResponseBoolean },
        shakesOrSqueezesAnObjectPlacedInHandProducingInvoluntarySounds: { type: String, ResponseBoolean },
        playsAloneFor10Minutes: { type: String, ResponseBoolean },
        seeksEyeContactWhenSomeonePaysAttentionFor2To3Minutes: { type: String, ResponseBoolean },
        playsAloneWithoutComplainingFor15To20MinutesNearAnAdult: { type: String, ResponseBoolean },
        vocalizesToGetAttention: { type: String, ResponseBoolean },
        imitatesAdultInPeekABooGames: { type: String, ResponseBoolean },
        clapsHandsImitatingAnAdult: { type: String, ResponseBoolean },
        wavesHandImitatingAnAdult: { type: String, ResponseBoolean },
        raisesArmsToExpressBigImitatingAnAdult: { type: String, ResponseBoolean },
        offersSomethingButDoesNotAlwaysDeliver: { type: String, ResponseBoolean },
        hugsCaressesAndKissesFamilyMembers: { type: String, ResponseBoolean },
        respondsToOwnNameLookingOrExtendingArmToBePickedUp: { type: String, ResponseBoolean },
        squeezesOrShakesToyToProduceSoundsInImitation: { type: String, ResponseBoolean },
        manipulatesToyOrObject: { type: String, ResponseBoolean },
        extendsAToyOrObjectToAnAdultAndDeliversIt: { type: String, ResponseBoolean },
        imitatesMovementsOfOtherChildrenWhilePlaying: { type: String, ResponseBoolean }
    },
    socialization1To2Years: {
        imitatesAnAdultInASimpleTask: { type: String, ResponseBoolean },
        playsNextToAnotherChildEachPerformingDifferentTasks: { type: String, ResponseBoolean },
        takesPartInAPlayWithAnotherChildFor2To5Minutes: { type: String, ResponseBoolean },
        acceptsParentsAbsenceAlthoughMayComplain: { type: String, ResponseBoolean },
        activelyExploresItsEnvironment: { type: String, ResponseBoolean },
        performsManipulativeActivityWithAnotherPerson: { type: String, ResponseBoolean },
        hugsAndCarriesADollOrSoftToy: { type: String, ResponseBoolean },
        repeatsActionsThatProduceLaughterAndAttention: { type: String, ResponseBoolean },
        givesABookForAnAdultToReadOrForBothToShare: { type: String, ResponseBoolean },
        pullsAPersonToShowThemSomething: { type: String, ResponseBoolean },
        withdrawsHandOrSaysNoWhenNearForbiddenObjectAndSomeoneRemindsIt: { type: String, ResponseBoolean },
        whenPlacedInChairOrChangingTableWaitsToBeAttended: { type: String, ResponseBoolean },
        playsWith2Or3ChildrenOfSameAge: { type: String, ResponseBoolean },
        sharesAnObjectOrFoodWithAnotherChild: { type: String, ResponseBoolean },
        greetsPeersOrAdultsWhenReminded: { type: String, ResponseBoolean }
    },
    socialization2To3Years: {
        obeysParentsOrdersAtLeastHalfTheTime: { type: String, ResponseBoolean },
        seeksOrTakesAnObjectOrPersonWhenAsked: { type: String, ResponseBoolean },
        paysAttentionToStoryOrMusicFor5To10Minutes: { type: String, ResponseBoolean },
        saysPleaseOrThankYouWhenReminded: { type: String, ResponseBoolean },
        triesToHelpParentsPerformTasksByDoingPartOfIt: { type: String, ResponseBoolean },
        playsAtWearingAdultsClothes: { type: String, ResponseBoolean },
        makesAChoiceWhenAsked: { type: String, ResponseBoolean },
        demonstratesUnderstandingOfFeelingsExpressingThem: { type: String, ResponseBoolean }
    },
    socialization3To4Years: {
        singsAndDancesWhenHearingMusic: { type: String, ResponseBoolean },
        followsRulesOfAGameImitatingActionsOfOtherChildren: { type: String, ResponseBoolean },
        greetsFamilyMembersWithoutBeingReminded: { type: String, ResponseBoolean },
        followsRulesInGroupGamesDirectedByAdults: { type: String, ResponseBoolean },
        asksPermissionToPlayWithAToyBeingUsedByAnotherChild: { type: String, ResponseBoolean },
        saysPleaseAndThankYouWithoutBeingRemindedHalfTheTime: { type: String, ResponseBoolean },
        answersThePhoneCallingAnAdultAndSpeakingWithFamilyMembers: { type: String, ResponseBoolean },
        waitsItsTurn: { type: String, ResponseBoolean },
        followsRulesInGamesDirectedByAnOlderChild: { type: String, ResponseBoolean },
        obeysAdultsOrders75PercentOfTheTime: { type: String, ResponseBoolean },
        staysInItsOwnYardOrGarden: { type: String, ResponseBoolean },
        playsNearOtherChildrenTalkingToThemWhileWorkingOnOwnProject30Minutes: { type: String, ResponseBoolean }
    },
    socialization4To5Years: {
        asksForHelpWhenHavingDifficulties: { type: String, ResponseBoolean },
        contributesToAdultConversation: { type: String, ResponseBoolean },
        repeatsRhymesSongsOrDancesForOthers: { type: String, ResponseBoolean },
        doesATaskAloneFor20To30Minutes: { type: String, ResponseBoolean },
        apologizesWithoutBeingReminded75PercentOfTheTime: { type: String, ResponseBoolean },
        waitsItsTurnInPlayInvolving8To9Children: { type: String, ResponseBoolean },
        playsWith2To3ChildrenFor20MinutesInAnActivityInvolvingCooperation: { type: String, ResponseBoolean },
        whenInPublicPresentsASociallyAcceptableBehavior: { type: String, ResponseBoolean },
        asksPermissionToUseOthersObjects75PercentOfTheTime: { type: String, ResponseBoolean }
    },
    socialization5To6Years: {
        expressesItsFeelings: { type: String, ResponseBoolean },
        playsWith4To5ChildrenInCooperativeActivityFor20MinutesWithoutSupervision: { type: String, ResponseBoolean },
        explainsToOthersTheRulesOfTheGameOrActivity: { type: String, ResponseBoolean },
        imitatesAdultRoles: { type: String, ResponseBoolean },
        collaboratesInConversationDuringMeals: { type: String, ResponseBoolean },
        followsRulesOfAGameInvolvingVerbalReasoning: { type: String, ResponseBoolean },
        comfortsPeersWhenTheyAreSad: { type: String, ResponseBoolean },
        choosesItsOwnFriends: { type: String, ResponseBoolean },
        plansAndBuildsUsingSimpleTools: { type: String, ResponseBoolean },
        setsGoalsForItselfAndPerformsActivityToAchieveThem: { type: String, ResponseBoolean },
        dramatizesExcerptsFromStoriesPlayingARoleOrUsingPuppets: { type: String, ResponseBoolean }
    },
    language0To1Years: {
        repeatsSoundsMadeByOtherPeople: { type: String, ResponseBoolean },
        repeatsSameSyllable2To3Times: { type: String, ResponseBoolean },
        respondsToGesturesWithGestures: { type: String, ResponseBoolean },
        obeysASimpleOrderWhenAccompaniedByIndicativeGestures: { type: String, ResponseBoolean },
        interruptsActivityWhenToldNo75PercentOfTheTime: { type: String, ResponseBoolean },
        respondsToSimpleQuestionsWithNonVerbalAnswers: { type: String, ResponseBoolean },
        combines2DifferentSyllablesWhenTryingToVerbalize: { type: String, ResponseBoolean },
        imitatesIntonationPatternsOfOthersVoice: { type: String, ResponseBoolean },
        usesAWordFunctionallyToIndicateObjectsOrPeople: { type: String, ResponseBoolean },
        vocalizesInResponseToOtherPeoplesSpeech: { type: String, ResponseBoolean }
    },
    language1To2Years: {
        says5DifferentWords: { type: String, ResponseBoolean },
        asksForMore: { type: String, ResponseBoolean },
        saysDone: { type: String, ResponseBoolean },
        obeys3DifferentOrdersThatAreNotAccompaniedByIndicativeGestures: { type: String, ResponseBoolean },
        managesToGiveOrShowWhenAsked: { type: String, ResponseBoolean },
        pointsTo12ObjectsWhenNamed: { type: String, ResponseBoolean },
        pointsTo3To5FiguresInABook: { type: String, ResponseBoolean },
        pointsTo3PartsOfOwnBody: { type: String, ResponseBoolean },
        saysOwnNameOrNicknameWhenAsked: { type: String, ResponseBoolean },
        respondsToTheQuestionWhatIsThis: { type: String, ResponseBoolean },
        combinesWordsAndGesturesToExpressWishes: { type: String, ResponseBoolean },
        names5FamilyMembersIncludingAnimals: { type: String, ResponseBoolean },
        names4Toys: { type: String, ResponseBoolean },
        producesAnimalSoundsOrNamesThemByTheSound: { type: String, ResponseBoolean },
        asksForKnownFoodsByNameWhenShown: { type: String, ResponseBoolean },
        asksQuestionsVaryingIntonationOfVoice: { type: String, ResponseBoolean },
        names3BodyPartsOnADollOrAnotherPerson: { type: String, ResponseBoolean },
        respondsToYesNoQuestions: { type: String, ResponseBoolean }
    },
    language2To3Years: {
        combinesNounsOrAdjectivesAndNounsIn2WordSentences: { type: String, ResponseBoolean },
        combinesNounAndVerbIn2WordSentences: { type: String, ResponseBoolean },
        usesAWordToIndicateThatWantsToGoToTheBathroom: { type: String, ResponseBoolean },
        combinesVerbOrNounWithThereAndHereIn2WordSentences: { type: String, ResponseBoolean },
        combines2WordstoExpressPossession: { type: String, ResponseBoolean },
        usesNoInSpeech: { type: String, ResponseBoolean },
        respondsToTheQuestionWhatIsDoingForHabitualActivity: { type: String, ResponseBoolean },
        respondsToQuestionsLikeWhereIsObject: { type: String, ResponseBoolean },
        namesFamiliarEnvironmentalSounds: { type: String, ResponseBoolean },
        givesMoreThanOneObjectWhenUsingThePluralFormInTheRequest: { type: String, ResponseBoolean },
        whenSpeakingRefersToItselfByName: { type: String, ResponseBoolean },
        pointsToFiguresOfCommonObjectsDescribedByUseUpTo10WhatIsUsedToEatSpoon: { type: String, ResponseBoolean },
        showsAgeByFingers: { type: String, ResponseBoolean },
        saysSexWhenAsked: { type: String, ResponseBoolean },
        obeysTheSequenceOfTwoRelatedOrders: { type: String, ResponseBoolean },
        usesTheVerbFormInTheGerund: { type: String, ResponseBoolean },
        employsRegularPluralForms: { type: String, ResponseBoolean },
        employsSomeIrregularFormsOfVerbsInThePastSystematically: { type: String, ResponseBoolean },
        asksQuestionsLikeWhatIsThis: { type: String, ResponseBoolean },
        controlsVolumeOfVoice90PercentOfTheTime: { type: String, ResponseBoolean },
        usesThisAndThatInSpeech: { type: String, ResponseBoolean },
        employsIsAndIsLocatedInSimpleSentences: { type: String, ResponseBoolean },
        saysIMeMineInsteadOfOwnName: { type: String, ResponseBoolean },
        pointsToObjectsAndSaysTheyAreNotOtherThings: { type: String, ResponseBoolean },
        respondsToTheQuestionWhoGivingAName: { type: String, ResponseBoolean },
        employsPossessiveFormsOfNouns: { type: String, ResponseBoolean },
        usesArticlesWhenSpeaking: { type: String, ResponseBoolean },
        usesNounsThatIndicateAGroupOrCategory: { type: String, ResponseBoolean },
        usesTheVerbsToBeToExistAndToHaveInThePresentWithFewErrors: { type: String, ResponseBoolean },
        saysIfObjectsAreOpenOrClosed: { type: String, ResponseBoolean }
    },
    language3To4Years: {
        expressesDiminutivesAndAugmentativesWhenSpeaking: { type: String, ResponseBoolean },
        paysAttentionFor5MinutesToAReadStory: { type: String, ResponseBoolean },
        obeysSequenceOf2UnrelatedOrders: { type: String, ResponseBoolean },
        saysFullNameWhenAsked: { type: String, ResponseBoolean },
        respondsSimpleQuestionsInvolvingHow: { type: String, ResponseBoolean },
        employsRegularVerbsInThePast: { type: String, ResponseBoolean },
        reportsImmediateExperiences: { type: String, ResponseBoolean },
        saysHowCommonObjectsAreUsed: { type: String, ResponseBoolean },
        expressesFutureActionsUsingVerbsToGoToHaveAndToWant: { type: String, ResponseBoolean },
        usesMasculineAndFeminineAppropriatelyInSpeech: { type: String, ResponseBoolean },
        usesImperativeFormsOfVerbsWhenAskingForFavors: { type: String, ResponseBoolean },
        tells2FactsInOrderOfOccurrence: { type: String, ResponseBoolean }
    },
    language4To5Years: {
        obeysASequenceInvolving3Orders: { type: String, ResponseBoolean },
        demonstratesUnderstandingOfReflexiveVerbsUsingThemOccasionallyExHeGotHurt: { type: String, ResponseBoolean },
        managesToIdentifyObjectsFiguresThatFormAPairUponRequest: { type: String, ResponseBoolean },
        employsFutureWhenSpeaking: { type: String, ResponseBoolean },
        usesSentencesComposedByCoordination: { type: String, ResponseBoolean },
        managesToIdentifyTheTopAndBottomPartOfObjectsWhenRequested: { type: String, ResponseBoolean },
        employsOccasionallyTheConditionalWhenSpeakingCouldWouldCouldWouldMake: { type: String, ResponseBoolean },
        managesToIdentifyAbsurditiesInFigures: { type: String, ResponseBoolean },
        employsTheFollowingWordsBrotherSisterGrandmotherGrandfather: { type: String, ResponseBoolean },
        completesSentencesWithAntonyms: { type: String, ResponseBoolean },
        tellsAKnownStoryWithoutHelpOfFigures: { type: String, ResponseBoolean },
        inAFigureNamesTheObjectThatDoesNotBelongToACertainCategory: { type: String, ResponseBoolean },
        saysIfTwoWordsRhymeOrNot: { type: String, ResponseBoolean },
        usesComplexSentencesComposedBySubordination: { type: String, ResponseBoolean },
        saysIfASoundIsLoudOrSoft: { type: String, ResponseBoolean }
    },
    language5To6Years: {
        managesToIndicateSomeManyAndSeveralElements: { type: String, ResponseBoolean },
        saysOwnAddress: { type: String, ResponseBoolean },
        saysOwnPhoneNumber: { type: String, ResponseBoolean },
        pointsToTheSetThatHasMoreLessOrFewElements: { type: String, ResponseBoolean },
        tellsSimpleJokes: { type: String, ResponseBoolean },
        reportsDailyExperiences: { type: String, ResponseBoolean },
        describesALocationOrMovementThroughOrBetweenAwayFromFromSinceToOverUpTo: { type: String, ResponseBoolean },
        answersTheQuestionWhyWithAnExplanation: { type: String, ResponseBoolean },
        ordersAndTellsAStoryOf2To5episodesInTheCorrectSequence: { type: String, ResponseBoolean },
        definesWords: { type: String, ResponseBoolean },
        respondsAppropriatelyToTheQuestionWhatIsTheOppositeOf: { type: String, ResponseBoolean },
        respondsToTheQuestionWhatHappensIf: { type: String, ResponseBoolean },
        usesYesterdayAndTomorrowCorrectly: { type: String, ResponseBoolean },
        asksTheMeaningOfNewOrKnownQuestions: { type: String, ResponseBoolean }
    },
    cognition0To1Year: {
        removesAClothFromFaceThatObscuresVision: { type: String, ResponseBoolean },
        looksForObjectThatHasBeenRemovedFromItsVisualField: { type: String, ResponseBoolean },
        removesAnObjectFromAReceptacleByPuttingHandInsideIt: { type: String, ResponseBoolean },
        placesAnObjectInAReceptacleImitatingAnAdult: { type: String, ResponseBoolean },
        placesAnObjectInAReceptacleWhenGivenInstructions: { type: String, ResponseBoolean },
        shakesAToyThatProducesSoundHangingFromAString: { type: String, ResponseBoolean },
        placesThreeObjectsInAReceptacleAndEmptiesIt: { type: String, ResponseBoolean },
        transfersAnObjectFromOneHandToAnotherToPickUpAnotherObject: { type: String, ResponseBoolean },
        dropsAndPicksUpAToy: { type: String, ResponseBoolean },
        discoversAnObjectHiddenUnderAReceptacle: { type: String, ResponseBoolean },
        pushes3BlocksAsIfItWereATrain: { type: String, ResponseBoolean },
        removesACircleFromABoardByImitation: { type: String, ResponseBoolean },
        placesARoundPinInAPinBoardWhenRequested: { type: String, ResponseBoolean },
        performsSimpleGesturesWhenRequested: { type: String, ResponseBoolean }
    },
    cognition1To2Years: {
        removes6ObjectsFromAReceptacleOneAtATime: { type: String, ResponseBoolean },
        pointsToAPartOfTheBody: { type: String, ResponseBoolean },
        stacks3BlocksGivenTheOrder: { type: String, ResponseBoolean },
        matchesSimilarObjects: { type: String, ResponseBoolean },
        scribblesOnPaper: { type: String, ResponseBoolean },
        pointsToItselfWhenAskedWhereIsName: { type: String, ResponseBoolean },
        places5RoundPinsGivenTheOrder: { type: String, ResponseBoolean },
        matchesObjectsWithTheFigureOfTheSameName: { type: String, ResponseBoolean },
        pointsToTheNamedFigure: { type: String, ResponseBoolean },
        turnsThePagesOfABook23AtATimeToFindTheNamedFigure: { type: String, ResponseBoolean }
    },
    cognition2To3Years: {
        findsACertainBookWhenRequested: { type: String, ResponseBoolean },
        completesA3PieceJigsawPuzzle: { type: String, ResponseBoolean },
        names4CommonObjectsInFigures: { type: String, ResponseBoolean },
        drawsAVerticalLineImitatingAnAdult: { type: String, ResponseBoolean },
        drawsAHorizontalLineImitatingAnAdult: { type: String, ResponseBoolean },
        copiesACircle: { type: String, ResponseBoolean },
        matchesObjectsWithTheSameTexture: { type: String, ResponseBoolean },
        pointsToSmallAndBigWhenRequested: { type: String, ResponseBoolean },
        drawsAPlusSignImitatingAnAdult: { type: String, ResponseBoolean },
        matches3Colors: { type: String, ResponseBoolean },
        placesObjectsInsideOnTopAndUnderAReceptacleGivenTheOrder: { type: String, ResponseBoolean },
        namesObjectsWhenHearsTheNoiseTheyMake: { type: String, ResponseBoolean },
        mountsA4PieceFittingToy: { type: String, ResponseBoolean },
        namesActionsInFiguresWhatIsDoing: { type: String, ResponseBoolean },
        matchesGeometricShapeWithTheFigureOfTheSame: { type: String, ResponseBoolean },
        stacks5OrMoreRingsOnARodInOrder: { type: String, ResponseBoolean }
    },
    cognition3To4Years: {
        namesObjectsAsBeingBigOrSmall: { type: String, ResponseBoolean },
        pointsTo10PartsOfTheBodyWhenRequested: { type: String, ResponseBoolean },
        pointsToBoyAndGirlGivenTheOrder: { type: String, ResponseBoolean },
        saysIfAnObjectIsHeavyOrLight: { type: String, ResponseBoolean },
        unites2PartsOfAFigureToFormTheWhole: { type: String, ResponseBoolean },
        describes2EventsOrCharactersFromAFamiliarStoryOrTvProgram: { type: String, ResponseBoolean },
        repeatsGamesRhymesOrSongsThatInvolveCoordinatedMovements: { type: String, ResponseBoolean },
        matches3OrMoreObjects: { type: String, ResponseBoolean },
        pointsToLongOrShortObjects: { type: String, ResponseBoolean },
        associatesCorrespondingObjectsExSockShoe: { type: String, ResponseBoolean },
        countsUpTo3ImitatingAnAdult: { type: String, ResponseBoolean },
        groupsObjectsIntoCategories: { type: String, ResponseBoolean },
        tracesAVInImitation: { type: String, ResponseBoolean },
        tracesADiagonalLineGivenTheExample: { type: String, ResponseBoolean },
        countsUpTo10ObjectsImitatingAnAdult: { type: String, ResponseBoolean },
        buildsABridgeWith3BlocksByImitation: { type: String, ResponseBoolean },
        matchesASequenceOrPatternSizeColorOfBlocksOrBeads: { type: String, ResponseBoolean },
        copiesASeriesOfInterconnectedV: { type: String, ResponseBoolean },
        addsALegOrArmToAnIncompleteDrawingOfTheHumanFigure: { type: String, ResponseBoolean },
        completesA6PiecePuzzle: { type: String, ResponseBoolean },
        indicatesIfObjectsAreEqualOrDifferent: { type: String, ResponseBoolean },
        drawsASquareImitatingAnAdult: { type: String, ResponseBoolean },
        names3ColorsBeingRequested: { type: String, ResponseBoolean },
        names3GeometricShapesSquareTriangleAndCircle: { type: String, ResponseBoolean }
    },
    cognition4To5Years: {
        picksUpFrom1To5ObjectsWhenRequested: { type: String, ResponseBoolean },
        names5DifferentTextures: { type: String, ResponseBoolean },
        copiesATriangleWhenRequested: { type: String, ResponseBoolean },
        remembers4ObjectsThatHadBeenSeenInAFigure: { type: String, ResponseBoolean },
        saysTheTimeOfTheDayAssociatedWithEachActivity: { type: String, ResponseBoolean },
        repeatsFamiliarRhymes: { type: String, ResponseBoolean },
        saysIfAnObjectIsHeavierOrLighterObjectsWithADifferenceOf05Kilo: { type: String, ResponseBoolean },
        saysWhatIsMissingWhenAnObjectIsRemovedFromAGroupOf3Objects: { type: String, ResponseBoolean },
        names8Colors: { type: String, ResponseBoolean },
        identifiesTheValueOf3Coins: { type: String, ResponseBoolean },
        matchesSymbolsLettersAndNumbers: { type: String, ResponseBoolean },
        saysTheColorOfNamedObjects: { type: String, ResponseBoolean },
        reports5MainFactsOfAStoryTold3Times: { type: String, ResponseBoolean },
        drawsHumanFigureHeadTorsoAnd4Limbs: { type: String, ResponseBoolean },
        sings5VersesOfASong: { type: String, ResponseBoolean },
        buildsAPyramidOf10BlocksByImitation: { type: String, ResponseBoolean },
        namesObjectsAsBeingLongOrShort: { type: String, ResponseBoolean },
        placesObjectsBehindBesideOrNextToOthers: { type: String, ResponseBoolean },
        makesEqualSetsOf10ObjectsAccordingToModel: { type: String, ResponseBoolean },
        namesOrPointsToTheMissingPartOfTheFigure: { type: String, ResponseBoolean },
        countsFrom1To20: { type: String, ResponseBoolean },
        identifiesTheObjectThatIsPlacedInTheMiddleInFirstAndLastPlace: { type: String, ResponseBoolean }
    },
    cognition5To6Years: {
        countsUpTo20ObjectsAndAnswersAppropriatelyToTheQuestionHowManyDidYouCount: { type: String, ResponseBoolean },
        names10Numerals: { type: String, ResponseBoolean },
        identifiesWhichIsItsLeftAndWhichIsItsRight: { type: String, ResponseBoolean },
        saysTheVowelsInOrder: { type: String, ResponseBoolean },
        writesOwnNameWithBlockLetters: { type: String, ResponseBoolean },
        names5LettersOfTheAlphabet: { type: String, ResponseBoolean },
        ordersObjectsInSequenceOfLengthAndWidth: { type: String, ResponseBoolean },
        namesTheUppercaseLettersOfTheAlphabet: { type: String, ResponseBoolean },
        placesNumeralsFrom1To10InTheCorrectSequence: { type: String, ResponseBoolean },
        identifiesThePositionOfObjectsInFirstSecondAndThirdPlace: { type: String, ResponseBoolean },
        namesTheLowercaseLettersOfTheAlphabet: { type: String, ResponseBoolean },
        matchesUppercaseLettersWithLowercaseOnes: { type: String, ResponseBoolean },
        pointsToNumeralsFrom1To25: { type: String, ResponseBoolean },
        copiesARhombus: { type: String, ResponseBoolean },
        completesASimpleLabyrinth: { type: String, ResponseBoolean },
        saysTheDaysOfTheWeekInOrder: { type: String, ResponseBoolean },
        addsAndSubtractsCombinationsOfUpTo3Elements: { type: String, ResponseBoolean },
        saysTheMonthAndDayOfOwnBirthday: { type: String, ResponseBoolean },
        reads10PrintedWords: { type: String, ResponseBoolean },
        predictsWhatWillOccur: { type: String, ResponseBoolean },
        pointsToWholeAndHalfObjects: { type: String, ResponseBoolean },
        countsFromMemoryFrom1To100AskToStopAt40AndContinueAt80IfNoErrorsUntil40: { type: String, ResponseBoolean }
    },
    selfCare0To1Year: {
        sucksAndSwallowsLiquids: { type: String, ResponseBoolean },
        eatsPorridgeOrSoup: { type: String, ResponseBoolean },
        extendsHandsTowardsBabyBottleTryingToGrabIt: { type: String, ResponseBoolean },
        eatsPureedFoodsGivenByParents: { type: String, ResponseBoolean },
        holdsBabyBottleWithoutHelpWhileDrinking: { type: String, ResponseBoolean },
        bringsBottleToMouthOrRefusesItPushingItAway: { type: String, ResponseBoolean },
        eatsMashedFoodsGivenByParents: { type: String, ResponseBoolean },
        drinksFromAMugHeldByParents: { type: String, ResponseBoolean },
        eatsSemisolidFoodsGivenByParents: { type: String, ResponseBoolean },
        feedsItselfUsingFingers: { type: String, ResponseBoolean },
        holdsTheMugWithBothHandsAndDrinks: { type: String, ResponseBoolean },
        bringsASpoonFullOfFoodToMouthWithHelp: { type: String, ResponseBoolean },
        stretchesArmsAndLegsWhenBeingDressed: { type: String, ResponseBoolean }
    },
    selfCare1To2Years: {
        eatsWithSpoonIndependently: { type: String, ResponseBoolean },
        holdsMugWithOneHandAndDrinks: { type: String, ResponseBoolean },
        putsHandInWaterAndPatsFaceWithWetHandsImitatingSomeone: { type: String, ResponseBoolean },
        sitsOnAPottyOrChildsToiletFor5Minutes: { type: String, ResponseBoolean },
        putsAHatOnHeadAndRemovesIt: { type: String, ResponseBoolean },
        takesOffSocks: { type: String, ResponseBoolean },
        pushesArmsThroughSleevesAndFeetThroughTrouserLegs: { type: String, ResponseBoolean },
        takesOffShoesWhenLacesAreUntied: { type: String, ResponseBoolean },
        takesOffCoatWhenUnbuttoned: { type: String, ResponseBoolean },
        takesOffTrousersWhenUnbuttoned: { type: String, ResponseBoolean },
        pullsALargeZipperUpAndDown: { type: String, ResponseBoolean },
        usesWordsOrGesturesIndicatingNeedToGoToTheBathroom: { type: String, ResponseBoolean }
    },
    selfCare2To3Years: {
        eatsAloneUsingSpoonOrMugSpillingALittleFoodOrLiquid: { type: String, ResponseBoolean },
        whenGivenATowelDriesHandsAndFaceWithHelp: { type: String, ResponseBoolean },
        sucksLiquidFromTheGlassOrMugUsingAStraw: { type: String, ResponseBoolean },
        takesForkfuls: { type: String, ResponseBoolean },
        chewsAndSwallowsOnlyEdibleSubstances: { type: String, ResponseBoolean },
        driesHandsWithoutHelpWhenGivenATowel: { type: String, ResponseBoolean },
        warnsThatWantsToGoToTheBathroomEvenIfItIsTooLate: { type: String, ResponseBoolean },
        controlsOwnDrool: { type: String, ResponseBoolean },
        urinatesOrDefecatesWhenPlacedInPottyAtLeast3TimesAWeek: { type: String, ResponseBoolean },
        putsOnShoes: { type: String, ResponseBoolean },
        brushesTeethImitatingAnAdult: { type: String, ResponseBoolean },
        removesSimpleClothesThatHaveBeenUnbuttoned: { type: String, ResponseBoolean },
        usesTheBathroomToDefecateFailsOnlyOnceAWeek: { type: String, ResponseBoolean },
        obtainsWaterFromAFaucetWithoutHelp: { type: String, ResponseBoolean },
        washesHandsAndFaceWithSoap: { type: String, ResponseBoolean },
        warnsThatWantsToGoToTheBathroomDuringTheDayInTime: { type: String, ResponseBoolean },
        hangsCoatOnAHookAtItsOwnHeight: { type: String, ResponseBoolean },
        staysDryWhenSleepingDuringTheDay: { type: String, ResponseBoolean },
        avoidsRisksExSharpEdgesOnFurnitureAndStairsWithoutHandrail: { type: String, ResponseBoolean },
        usesANapkinWhenRecommended: { type: String, ResponseBoolean },
        piercesTheForkInTheFoodTakingItToTheMouth: { type: String, ResponseBoolean },
        poursLiquidFromASmallPitcherIntoAGlassWithoutHelp: { type: String, ResponseBoolean },
        unfastensClothesFastenedWithASnapFastener: { type: String, ResponseBoolean },
        washesArmsAndLegsWhenGivenABath: { type: String, ResponseBoolean },
        putsOnSocks: { type: String, ResponseBoolean },
        wearsCoatJacketOrShirt: { type: String, ResponseBoolean },
        identifiesTheFrontPartOfClothes: { type: String, ResponseBoolean }
    },
    selfCare3To4Years: {
        feedsItselfAloneForEntireMeal: { type: String, ResponseBoolean },
        dressesItselfAloneNeedingHelpOnlyWhenThereAreJacketsOrTShirtsWithClosedCollarsOrButtonsAndFasteners: { type: String, ResponseBoolean },
        wipesNoseWhenReminded: { type: String, ResponseBoolean },
        wakesUpDry2MorningsAWeek: { type: String, ResponseBoolean },
        ifBoyUrinatesInTheToiletWhileStanding: { type: String, ResponseBoolean },
        dressesAndUndressesItselfAloneExceptForButtonsAndFasteners75PercentOfTheTime: { type: String, ResponseBoolean },
        fastensClothesWithSnapsOrHooks: { type: String, ResponseBoolean },
        blowsNoseWhenReminded: { type: String, ResponseBoolean },
        avoidsCommonDangersExBrokenGlass: { type: String, ResponseBoolean },
        hangsClothesOnAHangerAndPutsInClosetWhenAsked: { type: String, ResponseBoolean },
        brushesTeethWhenReceivesInstruction: { type: String, ResponseBoolean },
        putsOnGloves: { type: String, ResponseBoolean },
        putsOnBoots: { type: String, ResponseBoolean },
        unbuttonsLargeButtons: { type: String, ResponseBoolean },
        buttonsLargeButtons: { type: String, ResponseBoolean }
    },
    selfCare4To5Years: {
        cleansWhatItSpilledOnOwn: { type: String, ResponseBoolean },
        avoidsPoisonAndAllHarmfulSubstances: { type: String, ResponseBoolean },
        unbuttonsOwnClothes: { type: String, ResponseBoolean },
        buttonsOwnClothes: { type: String, ResponseBoolean },
        removesPlateAndCutleryFromTheTable: { type: String, ResponseBoolean },
        fitsZipperIntoItsTermination: { type: String, ResponseBoolean },
        washesHandsAndFace: { type: String, ResponseBoolean },
        usesAppropriateCutleryToEat: { type: String, ResponseBoolean },
        wakesUpAtNightToGoToTheBathroomOrWakesUpDry: { type: String, ResponseBoolean },
        cleansAndBlowsItsNose75PercentOfTheTimeWithoutBeingReminded: { type: String, ResponseBoolean },
        bathesAloneNeedingHelpOnlyToWashBackNeckAndEars: { type: String, ResponseBoolean },
        usesAKnifeToSpreadButterOnBread: { type: String, ResponseBoolean },
        tightensAndLoosensBeltsOrBuckles: { type: String, ResponseBoolean },
        dressesItselfAloneButDoesNotTieLaces: { type: String, ResponseBoolean },
        servesItselfAtTheTableWhileHoldingTheFoodPlatter: { type: String, ResponseBoolean },
        helpsSetTheTableCorrectlyWhenReceivesInstructions: { type: String, ResponseBoolean },
        brushesTeeth: { type: String, ResponseBoolean },
        goesToTheBathroomInTimeRemovesClothesUsesToiletPaperFlushesAndDressesWithoutHelp: { type: String, ResponseBoolean },
        combsOrBrushesHair: { type: String, ResponseBoolean },
        hangsClothesOnHangers: { type: String, ResponseBoolean },
        walksAroundTheNeighborhoodWithoutConstantSupervision: { type: String, ResponseBoolean },
        threadsLacesIntoShoes: { type: String, ResponseBoolean },
        tiesOrLacesShoelaces: { type: String, ResponseBoolean }
    },
    selfCare5To6Years: {
        isResponsibleForAWeeklyTaskAndPerformsItWhenReminded: { type: String, ResponseBoolean },
        selectsAppropriateClothingForClimateAndOccasion: { type: String, ResponseBoolean },
        stopsOnTheSidewalkLooksBothWaysAndCrossesTheStreetWithoutNeedingToBeReminded: { type: String, ResponseBoolean },
        servesItselfAtTheTableAndPassesThePotOfFoodToothers: { type: String, ResponseBoolean },
        preparesOwnCupOfCoffeeWithMilk: { type: String, ResponseBoolean },
        isResponsibleForADailyTaskAtHome: { type: String, ResponseBoolean },
        adjustsTheTemperatureOfWaterForBathing: { type: String, ResponseBoolean },
        preparesOwnSnack: { type: String, ResponseBoolean },
        walksAloneUpToADistanceOf2BlocksFromHome: { type: String, ResponseBoolean },
        cutsTenderFoodsWithAKnife: { type: String, ResponseBoolean },
        findsTheBathroomInAPublicPlaceCorrectly: { type: String, ResponseBoolean },
        opensTheMilkPackage: { type: String, ResponseBoolean },
        picksUpATrayWithFoodCarryingItAndPlacingItOnTheTable: { type: String, ResponseBoolean },
        tiesTheLacesOnJacketsWithHood: { type: String, ResponseBoolean },
        fastensTheCarSeatBelt: { type: String, ResponseBoolean }
    },
    motorDevelopment0To1Year: {
        reachesForAnObjectPlacedInFrontOfIt15To20Cm: { type: String, ResponseBoolean },
        grabsAnObjectPlacedInFrontOfIt8Cm: { type: String, ResponseBoolean },
        extendsArmsTowardAnObjectInFrontOfItAndGrabsIt: { type: String, ResponseBoolean },
        reachesForAPreferredObject: { type: String, ResponseBoolean },
        putsObjectsInMouth: { type: String, ResponseBoolean },
        raisesHeadAndTorsoSupportingSelfOnArmsWhenLyingOnStomach: { type: String, ResponseBoolean },
        raisesHeadAndTorsoSupportingSelfOnOneArm: { type: String, ResponseBoolean },
        touchesAndExploresObjectsWithMouth: { type: String, ResponseBoolean },
        inPronePositionTurnsToTheSideAndMaintainsThisPositionHalfTheTime: { type: String, ResponseBoolean },
        inPronePositionTurnsOnBack: { type: String, ResponseBoolean },
        inPronePositionMovesForwardTheEquivalentOfItsHeight: { type: String, ResponseBoolean },
        inSupinePositionRollsToTheSide: { type: String, ResponseBoolean },
        inSupinePositionTurnsFromStomachToBack: { type: String, ResponseBoolean },
        makesEffortToSitHoldingOntoAdultsFingers: { type: String, ResponseBoolean },
        turnsHeadEasilyWhenTheBodyIsSupported: { type: String, ResponseBoolean },
        sitsFor2Minutes: { type: String, ResponseBoolean },
        releasesAnObjectToGrabAnother: { type: String, ResponseBoolean },
        grabsAndDropsAnObjectPurposefully: { type: String, ResponseBoolean },
        standsWithMaximumSupport: { type: String, ResponseBoolean },
        whileStandingWithSupportJumpsUpAndDown: { type: String, ResponseBoolean },
        crawlsToGrabAnObjectDistantItsHeight: { type: String, ResponseBoolean },
        sitsSupportingSelfAlone: { type: String, ResponseBoolean },
        whileSittingTurnsToCraw: { type: String, ResponseBoolean },
        whileInPronePositionManagesToSit: { type: String, ResponseBoolean },
        sitsWithoutHandSupport: { type: String, ResponseBoolean },
        throwsObjectsAtRandom: { type: String, ResponseBoolean },
        swaysBackAndForthWhenCrawling: { type: String, ResponseBoolean },
        transfersObjectsFromOneHandToAnotherWhenSitting: { type: String, ResponseBoolean },
        retains2CubesOf25CmInOneHand: { type: String, ResponseBoolean },
        getsOnKnees: { type: String, ResponseBoolean },
        standsSupportingSelfOnSomething: { type: String, ResponseBoolean },
        usesPincerGripToPickUpObjects: { type: String, ResponseBoolean },
        crawls: { type: String, ResponseBoolean },
        whileCrawlingExtendsOneHandUpwards: { type: String, ResponseBoolean },
        standsWithMinimumSupport: { type: String, ResponseBoolean },
        licksFoodAroundMouth: { type: String, ResponseBoolean },
        maintainsSelfStandingAloneFor1Minute: { type: String, ResponseBoolean },
        knocksDownAnObjectThatIsInsideAReceptacle: { type: String, ResponseBoolean },
        turnsSeveralPagesOfABookAtTheSameTime: { type: String, ResponseBoolean },
        scoopsWithASpoonOrSpade: { type: String, ResponseBoolean },
        placesSmallObjectsInsideAReceptacle: { type: String, ResponseBoolean },
        whileStandingLowersItselfAndSits: { type: String, ResponseBoolean },
        clapsHands: { type: String, ResponseBoolean },
        walksWithMinimumSupport: { type: String, ResponseBoolean },
        takesAFewStepsWithoutSupport: { type: String, ResponseBoolean }
    },
    motorDevelopment1To2Years: {
        climbsStairsCrawling: { type: String, ResponseBoolean },
        placesItselfStandingWhileSitting: { type: String, ResponseBoolean },
        rollsABallImitatingAnAdult: { type: String, ResponseBoolean },
        climbsOntoAnAdultChairTurnsAndSits: { type: String, ResponseBoolean },
        puts4RingsOnASmallStake: { type: String, ResponseBoolean },
        removes25CmPinsFromABoardOrTray: { type: String, ResponseBoolean },
        fits25CmPinsIntoAFittingBoard: { type: String, ResponseBoolean },
        buildsATowerOf3Blocks: { type: String, ResponseBoolean },
        makesTracesOnPaperWithPencilOrCrayon: { type: String, ResponseBoolean },
        walksAlone: { type: String, ResponseBoolean },
        goesDownStairsSittingPuttingFeetFirst: { type: String, ResponseBoolean },
        sitsInASmallChair: { type: String, ResponseBoolean },
        crouchesAndReturnsToStand: { type: String, ResponseBoolean },
        pushesAndPullsToysWhenWalking: { type: String, ResponseBoolean },
        usesAChairOrRockingHorse: { type: String, ResponseBoolean },
        climbsStairsWithHelp: { type: String, ResponseBoolean },
        bendsTheBodyWithoutFallingToPickUpObjectsOnTheFloor: { type: String, ResponseBoolean },
        imitatesACircularMovement: { type: String, ResponseBoolean }
    },
    motorDevelopment2To3Years: {
        threads4LargeBeadsOnACordIn2Minutes: { type: String, ResponseBoolean },
        turnsLatchesOrDoorknobsOnDoors: { type: String, ResponseBoolean },
        jumpsInTheSamePlaceWithBothFeet: { type: String, ResponseBoolean },
        walksBackwards: { type: String, ResponseBoolean },
        goesDownStairsWithoutHelp: { type: String, ResponseBoolean },
        throwsABallToAnAdultAtA1HalfDistance: { type: String, ResponseBoolean },
        buildsATowerOf5To6Blocks: { type: String, ResponseBoolean },
        turnsPagesOfABookOneAtATime: { type: String, ResponseBoolean },
        unwrapsASmallObject: { type: String, ResponseBoolean },
        foldsAPaperInHalfImitatingAnAdult: { type: String, ResponseBoolean },
        dismantlesAndRebuildsPressureFitToys: { type: String, ResponseBoolean },
        unscrewsToysThatFitWithThreads: { type: String, ResponseBoolean },
        kicksALargeBallThatIsStill: { type: String, ResponseBoolean },
        makesBallsOfClayMudOrPlasticine: { type: String, ResponseBoolean },
        holdsThePencilBetweenTheThumbAndIndexFingerRestingItOnTheMiddleFinger: { type: String, ResponseBoolean },
        doesForwardTumbleWithHelp: { type: String, ResponseBoolean },
        hammersToFit5PinsInTheirHoles: { type: String, ResponseBoolean }
    },
    motorDevelopment3To4Years: {
        makesAPuzzleOf3Pieces: { type: String, ResponseBoolean },
        cutsSomethingIntoPiecesWithScissors: { type: String, ResponseBoolean },
        jumpsFromAHeightOf20Cm: { type: String, ResponseBoolean },
        kicksALargeBallWhenSentToYou: { type: String, ResponseBoolean },
        walksOnTiptoes: { type: String, ResponseBoolean },
        runs10StepsCoordinatingAndAlternatingTheMovementOfArmsAndFeet: { type: String, ResponseBoolean },
        pedalsWithTricycleTheDistanceOf1AndAHalfMeters: { type: String, ResponseBoolean },
        swingsOnASwingWhenItIsInMotion: { type: String, ResponseBoolean },
        climbsOnASlideOf120MTo180MAndSlidesDown: { type: String, ResponseBoolean },
        doesForwardTumbles: { type: String, ResponseBoolean },
        climbsStairsAlternatingFeet: { type: String, ResponseBoolean },
        marchesWalksInARhythmicalWay: { type: String, ResponseBoolean },
        parriesTheBallWithBothHands: { type: String, ResponseBoolean },
        drawsFiguresFollowingOutlinesOrDottedLines: { type: String, ResponseBoolean },
        cutsAlongAStraightLine20CmMovingSlightlyAwayFromTheLine: { type: String, ResponseBoolean }
    },
    motorDevelopment4To5Years: {
        standsOnOneFootWithoutSupportFor4To8Seconds: { type: String, ResponseBoolean },
        changesDirectionWhenRunning: { type: String, ResponseBoolean },
        walksOnABeamOrBoardMaintainingBalance: { type: String, ResponseBoolean },
        jumpsForward10TimesWithoutFalling: { type: String, ResponseBoolean },
        jumpsOverARopeSuspended5CmFromTheGround: { type: String, ResponseBoolean },
        jumpsBackwards6Times: { type: String, ResponseBoolean },
        reboundsAndCatchesALargeBall: { type: String, ResponseBoolean },
        joins2To3PiecesOfPlasticine: { type: String, ResponseBoolean },
        cutsAroundCurvedLines: { type: String, ResponseBoolean },
        fitsScrewObjects: { type: String, ResponseBoolean },
        goesDownStairsAlternatingFeet: { type: String, ResponseBoolean },
        pedalsATricycleMakingTurns: { type: String, ResponseBoolean },
        jumpsOnOneFoot5ConsecutiveTimes: { type: String, ResponseBoolean },
        cutsACircleIn5Cm: { type: String, ResponseBoolean },
        drawsSimpleEasilyIdentifiableFiguresExHouse: { type: String, ResponseBoolean },
        cutsAndPastesSimpleShapes: { type: String, ResponseBoolean }
    },
    motorDevelopment5To6Years: {
        writesUppercaseLettersIsolatedAndLargeAnywhereOnThePaper: { type: String, ResponseBoolean },
        walksOnABoardBackwardsForwardsAndSidewaysMaintainingBalance: { type: String, ResponseBoolean },
        walksWhileHopping: { type: String, ResponseBoolean },
        swingsOnASwingStartingAndMaintainingTheMovement: { type: String, ResponseBoolean },
        stretchesFingersTouchingThumbToEachOfThem: { type: String, ResponseBoolean },
        copiesCapitalLetters: { type: String, ResponseBoolean },
        climbsOnLaddersOrASlideOf3M: { type: String, ResponseBoolean },
        hammersANailWithAHammer: { type: String, ResponseBoolean },
        reboundsTheBallAsItWalksWithDirection: { type: String, ResponseBoolean },
        managesToColorWithoutGoingOutOfTheMargin95PercentOfTheTime: { type: String, ResponseBoolean },
        cutsOutFiguresWithoutLeavingMoreThan6MmFromTheMargin: { type: String, ResponseBoolean },
        usesPencilSharpener: { type: String, ResponseBoolean },
        copiesComplexDrawingsSchoolShip: { type: String, ResponseBoolean },
        tearsSimpleFiguresFromThePaper: { type: String, ResponseBoolean },
        foldsASquarePaper2XDiagonallyByImitation: { type: String, ResponseBoolean },
        catchesALightBallWithOneHand: { type: String, ResponseBoolean },
        jumpsRopeAlone: { type: String, ResponseBoolean },
        strikesABallWithAStickOrPieceOfWood: { type: String, ResponseBoolean },
        catchesAnObjectOnTheFloorWhileRunning: { type: String, ResponseBoolean },
        skatesADistanceOf3MOrUsesASkateboard: { type: String, ResponseBoolean },
        ridesABicycle: { type: String, ResponseBoolean },
        slidesDownAHillOfSandOrEarth: { type: String, ResponseBoolean },
        walksOrPlaysInASwimmingPoolHavingWaterUpToItsWaist: { type: String, ResponseBoolean },
        drivesAScooterGivingImpulseWithOneFootOnly: { type: String, ResponseBoolean },
        jumpsAndTurnsOnOneFoot: { type: String, ResponseBoolean },
        writesOwnNameWithBlockLettersInLinedNotebook: { type: String, ResponseBoolean },
        jumpsFromAHeightOf30CmAndFallsOnTiptoes: { type: String, ResponseBoolean },
        stopsOnOneFootWithoutSupportWithEyesClosedFor10Seconds: { type: String, ResponseBoolean },
        hangsFor10SecondsOnAHorizontalBar: { type: String, ResponseBoolean }
    },

    socializacao: { type: Number },
    linguagem: { type: Number },
    cognicao: { type: Number },
    autoCuidado: { type: Number },
    motor: { type: Number }

    
}, { timestamps: true})

export interface IPortageGuidetoPreschoolEducationEntity extends Omit<IPgpse, '_id'>, Document {
}