import { Schema, Document } from 'mongoose';
import { Ethnicity } from 'src/features/sensory-processing-measure-school-preschool/types/sensoryProcessingMeasureSchoolPreSchool';
import { ISpmsps } from 'src/features/sensory-processing-measure-school-preschool/types/spmsps';

export const SensoryProcessingMeasureSchoolPreSchoolSchema = new Schema({
  _id: { type: Schema.Types.ObjectId, required: true, auto: true },
  doctor: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  responsable: { type: Schema.Types.ObjectId, required: true, ref: 'User' },
  relationshipWithChild: { type: String, required: false},
  patient: { type: Schema.Types.ObjectId, required: true, ref: 'User' },
  gender: { type: String, required: false, enum: ['M', 'F'] },
  age: { type: Number, required: false},
  bitrhDate: { type: String, required: false},
  ethnicity: { type: String, required: false, enum: Ethnicity },
  date: { type: String, required: true, },
  participationSocialSpmsps: {
    participatesInGamesAndActivitiesSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    waitsForTurnSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    participatesInCircleTimeSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    transitionsEasilyToNewActivitiesSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    joinsGamesWithoutInterruptingSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    followsClassRulesAndRoutinesSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    sharesToysAndMaterialsSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    cooperatesWithPeersForCommonGoalsSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    interactsWithPeersDuringPlaySchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    resolvesConflictsWithPeersIndependentlySchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']}, 
  },
  visionSpmsps: { 
    coversEyesOrComplainsAboutLightingSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    distractedByVisualStimuliSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    difficultyLocatingObjectsSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    difficultyFindingItemsOnDeskOrTableSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    looksAroundDuringTeachersSpeechSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    difficultyPairingItemsByShapeAndColorSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    walksAmongOtherChildrenPlayingSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    staresAtPeopleOrObjectsSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    enjoysWatchingMovingObjectsSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    enjoysLookingAtMovingObjectsWithPeripheralVisionSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
  },
  hearingSpmsps: { 
    discomfortWithLoudSoundsSchoolPreSchool:  { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    discomfortWithSingingOrMusicSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    unawareOfNewVoicesAndSoundsSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    unableToIdentifySoundSourceSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    makesRepetitiveSoundsSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    enjoysRepetitiveNoisesSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    unawareOfCertainSoundsSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    difficultyFocusingInNoisyEnvironmentsSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    unableToFollowVerbalInstructionsSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    disturbedByBackgroundNoiseSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
  },
  touchSpmsps: { 
    avoidsBeingTouchedSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    discomfortWithDirtyHandsOrFaceSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    discomfortWithWashingHandsSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    reactsNegativelyToAccidentalTouchSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    doesNotWipeFaceAfterEatingSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    distressedByCertainTexturesSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    refusesToWearCostumesOrTightClothesSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    hasHighPainToleranceSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    ignoresNeedToUseBathroomSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    avoidsMessyActivitiesSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
  },
  smellAndTasteSpmsps: { 
    chewsNonFoodItemsSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    doesNotNoticeStrongOrUnusualOdorsSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    discomfortWithCertainScentsSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    refusesToTryNewFoodsSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
  },
  bodyAwarenessSpmsps: { 
    enjoysMovingFurnitureSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    breaksObjectsFromExcessiveForceSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    excessivelyJumpsOrClimbsSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    opensOrClosesDoorsWithExcessiveForceSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    usesExcessiveForceWhenPlayingWithObjectsSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    bumpsIntoPeersExcessivelySchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    chewsOnNonFoodItemsSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    strugglesToManipulateFoodContainersSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    knocksOverOthersToysSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    squeezesScissorsExcessivelySchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
  },
  balanceAndMovementSpmsps: { 
    enjoysSpinningInRotatingEquipmentSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    needsSupportWhenStandingSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    fallsFromChairOrTendsToLeanSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    fearfulOfMovementActivitiesSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    excessivelyEnthusiasticAboutSpinningSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    clumsyWhenBendingToPickUpObjectsSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    strugglesToBalanceAndAvoidFallingSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    discomfortWithHeightsSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    poorCoordinationSchoolPreSchool:{ type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    difficultyWithRhythmicBodyMovementsSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
  },
  planningAndIdeationSpmsps: { 
    overlyFocusedOnIndividualActivitiesSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    strugglesToGenerateNewIdeasInPlaySchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    repeatsActivitiesWithoutChangingThemSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    needsRealObjectsToPlaySchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    strugglesToImitateActionsCorrectlySchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    playsWithOwnGamesAvoidingImitationSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    strugglesToCopyAdultsOrPeersInBuildingActivitiesSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    hasDifficultyUsingBothHandsForTasksSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    cannotCompleteMultistepTasksSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    strugglesWithRoutineSequencesSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
  },
});

export interface ISensoryProcessingMeasureSchoolPreSchoolEntity extends Omit<ISpmsps, '_id'>, Document {}