import { Schema, Document } from 'mongoose';
import { ISpmpHome } from 'src/features/sensory-processing-measure-home/types/sensoryProcessingMeasure';

import { Ethnicity } from 'src/features/sensory-processing-measure-school/types/sensoryProcessingMeasureSchool';

export const SensoryProcessingMeasureSchema = new Schema({
  _id: { type: Schema.Types.ObjectId, required: true, auto: true },
  doctor: { type: Schema.Types.ObjectId, ref: 'User', required: true },
<<<<<<< HEAD
  //responsable: { type: Schema.Types.ObjectId, required: true, ref: 'User' },
  //relationshipWithChild: { type: String, required: false},
  patient: { type: Schema.Types.ObjectId, required: true, ref: 'User' },
  //gender: { type: String, required: false, enum: ['M', 'F'] },
  //age: { type: Number, required: false},
  //bitrhDate: { type: String, required: false},
  //ethnicity: { type: String, required: false, enum: Ethnicity },
  date: { type: String, required: true, },
  participationSocial: { 
    playsWithFriends: { type: String, required: false},
    interactsWithParents: { type: String, required: false},
    sharesThings: { type: String, required: false},
    maintainsConversation: { type: String, required: false},
    maintainsEyeContact: { type: String, required: false},
    joinsGames: { type: String, required: false},
    participatesInMeals: { type: String, required: false},
    participatesInFamilyOutings: { type: String, required: false},
    participatesInFamilyGatherings: { type: String, required: false},
    participatesInFriendActivities: { type: String, required: false},
  },

  vision: {
    botheredByLight: { type: String, required: false},
    difficultyFindingObjects: { type: String, required: false},
    closesOneEye:{ type: String, required: false},
    botheredByVisualStimuli: { type: String, required: false},
    difficultyFollowingObjects: { type: String, required: false},
    difficultyIdentifyingObjects: { type: String, required: false},
    enjoysWatchingMovingObjects: { type: String, required: false},
    walksIntoObjects: { type: String, required: false},
    enjoysSwitchingLights: { type: String, required: false},
    dislikesCertainLights: { type: String, required: false},
    usesPeripheralVision: { type: String, required: false},
  },
  hearing: {
    botheredByNormalSounds: { type: String, required: false},
    reactsNegativelyToLoudNoises: { type: String, required: false},
    seemsNotToHearCertainSounds: { type: String, required: false},
    intenseInterestInUnnoticedSounds: { type: String, required: false},
    scaredByUnexpectedSounds: { type: String, required: false},
    distractedByBackgroundNoise: { type: String, required: false},
    enjoysMakingRepetitiveNoises: { type: String, required: false},
    botheredByHighPitchedSounds: { type: String, required: false},
  },
  touch: { 
    withdrawsFromLightTouch: { type: String, required: false},
    doesNotNoticeBeingTouched: { type: String, required: false},
    botheredByNewClothes: { type: String, required: false},
    prefersTouchingOverBeingTouched: { type: String, required: false},
    botheredByNailCutting: { type: String, required: false},
    botheredByFaceTouch: { type: String, required: false},
    avoidsMessyActivities: { type: String, required: false},
    highPainTolerance: { type: String, required: false},
    dislikesToothbrushing: { type: String, required: false},
    enjoysPainfulSensations: { type: String, required: false},
    difficultyFindingThingsByTouch: { type: String, required: false},
  },
  smellAndTaste: {
    triesInedibleItems: { type: String, required: false},
    gagsAtUnlikedFoods: { type: String, required: false},
    enjoysSmellingObjects: { type: String, required: false},
    discomfortWithSmells: { type: String, required: false},
    ignoresStrongOdors: { type: String, required: false},
  },

  bodyAwareness: { 
    gripsObjectsTooTightly: { type: String, required: false},
    seeksPushingAndPulling: { type: String, required: false},
    unsureOfBodyMovements: { type: String, required: false},
    gripsObjectsTooLoosely: { type: String, required: false},
    exertsExcessiveForce: { type: String, required: false},
    jumpsFrequently: { type: String, required: false},
    petsAnimalsTooHard: { type: String, required: false},
    pushesOtherChildren: { type: String, required: false},
    chewsObjects: { type: String, required: false},
    breaksObjectsFromForce: { type: String, required: false},
   },
  balanceAndMovement: { 
    exaggeratedFearOfMovement: { type: String, required: false},
    goodBalance: { type: String, required: false},
    avoidsBalanceActivities: { type: String, required: false},
    fallsFromChair: { type: String, required: false},
    poorBodyControlWhenFalling: { type: String, required: false},
    doesNotGetDizzy: { type: String, required: false},
    spinsBodyFrequently: { type: String, required: false},
    botheredByHeadPositionChanges: { type: String, required: false},
    clumsyMotorCoordination: { type: String, required: false},
    fearOfElevators: { type: String, required: false},
    leansOnObjects: { type: String, required: false},
  },
  planningAndIdeation: {  
    inconsistentDailyTasks: { type: String, required: false},
    difficultyCarryingMultipleObjects: { type: String, required: false},
    confusionOrganizingMaterials: { type: String, required: false},
    troubleSequentialTasks: { type: String, required: false},
    difficultyCompletingMultiStepTasks: { type: String, required: false},
    troubleImitatingActions: { type: String, required: false},
    difficultyCopyingModels:{ type: String, required: false},
    troubleGeneratingActivityIdeas: { type: String, required: false},
    repeatsSameActivities: { type: String, required: false},
  },
});

export interface ISensoryProcessingMeasureEntity extends Omit<ISpmHome, '_id'>, Document {}
=======
  responsable: { type: Schema.Types.ObjectId, required: true, ref: 'User' },
  relationshipWithChild: { type: String, required: false},
  patient: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  gender: { type: String, required: false, enum: ['M', 'F'] },
  age: { type: Number, required: false},
  bitrhDate: { type: String, required: false},
  ethnicity: { type: String, required: false, enum: Ethnicity },
  date: { type: String, required: true, },
    comment: { type: String, required: false },
    participationSocial: {
      playsWithFriends: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      interactsWithParents: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      sharesThings: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      maintainsConversation: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      maintainsEyeContact: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      joinsGames: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      participatesInMeals: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      participatesInFamilyOutings: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      participatesInFamilyGatherings: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      participatesInFriendActivities: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    },
    vision: {
        botheredByLight: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        difficultyFindingObjects: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        closesOneEye: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        botheredByVisualStimuli: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        difficultyFollowingObjects: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        difficultyIdentifyingObjects: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        enjoysWatchingMovingObjects: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        walksIntoObjects: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        enjoysSwitchingLights: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        dislikesCertainLights: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        usesPeripheralVision: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    },
    hearing: {
        botheredByNormalSounds: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        reactsNegativelyToLoudNoises: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        seemsNotToHearCertainSounds: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        intenseInterestInUnnoticedSounds: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        scaredByUnexpectedSounds: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        distractedByBackgroundNoise: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        enjoysMakingRepetitiveNoises: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        botheredByHighPitchedSounds: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    },
    touch: {
        withdrawsFromLightTouch: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        doesNotNoticeBeingTouched: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        botheredByNewClothes: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        prefersTouchingOverBeingTouched: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        botheredByNailCutting: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        botheredByFaceTouch: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        avoidsMessyActivities: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        highPainTolerance: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        dislikesToothbrushing: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        enjoysPainfulSensations: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        difficultyFindingThingsByTouch: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    },
    smellAndTaste: {
        triesInedibleItems: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        gagsAtUnlikedFoods: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        enjoysSmellingObjects: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        discomfortWithSmells: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        ignoresStrongOdors: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    },
    bodyAwareness: {
        gripsObjectsTooTightly: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        seeksPushingAndPulling: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        unsureOfBodyMovements: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        holdsObjectsTooLoosely: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        exertsExcessiveForce: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        jumpsFrequently: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        petsAnimalsTooHard: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        pushesOtherChildren: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        chewsObjects: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
         breaksObjectsFromForce: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    },
    balanceAndMovement: {
        exaggeratedFearOfMovement: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        goodBalance: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        avoidsBalanceActivities: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        fallsFromChair: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        poorBodyControlWhenFalling: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        doesNotGetDizzy: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        spinsBodyFrequently: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        distressedByHeadTilting: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        poorCoordination: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
          fearOfElevators: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        leansOnObjects: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    },
    planningAndIdeation: {
        inconsistentDailyTasks: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        difficultyCarryingMultipleObjects: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
         confusionOrganizingMaterials: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        troubleSequentialTasks: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        difficultyCompletingMultiStepTasks: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
         troubleImitatingActions: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
         difficultyCopyingModels: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
         troubleGeneratingActivityIdeas: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
        repeatsSameActivities: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    },
      scores: {
        SOC: { type: Number, default: 0 },
        VIS: { type: Number, default: 0 },
        HEA: { type: Number, default: 0 },
        TOU: { type: Number, default: 0 },
        ITEMS: { type: Number, default: 0 },
        BOD: { type: Number, default: 0 },
        BAL: { type: Number, default: 0 },
        PLA: { type: Number, default: 0 },
    },
}, { timestamps: true, versionKey: false });

export interface ISensoryProcessingMeasureEntity extends Omit<ISpmpHome, '_id'>, Document {}
>>>>>>> ed6efb2d5cd1d308049d1876943c6bef22acb421
