import { Schema, Document } from 'mongoose';
import { ISpmpHome } from 'src/features/sensory-processing-measure-home/types/sensoryProcessingMeasure';



export const SensoryProcessingMeasureSchema = new Schema({
  _id: { type: Schema.Types.ObjectId, required: true, auto: true },
  doctor: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  responsable: { type: Schema.Types.ObjectId, required: true, ref: 'User' },
  relationshipWithChild: { type: String, required: false},
  patient: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  gender: { type: String, required: false, enum: ['M', 'F'] },
  age: { type: Number, required: false},
  birthDate: { type: String, required: false},
  date: { type: String, required: true, },
  comment: { type: String, required: false },
  participationSocial: {
    playsWithFriends: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    interactsWithParents: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    sharesThings: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    maintainsConversation: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    maintainsEyeContact: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    joinsGames: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    participatesInMeals: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    participatesInFamilyOutings: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    participatesInFamilyGatherings: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    participatesInFriendActivities: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    },
  vision: {
    botheredByLight: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    difficultyFindingObjects: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    closesOneEye: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    botheredByVisualStimuli: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    difficultyFollowingObjects: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    difficultyIdentifyingObjects: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    enjoysWatchingMovingObjects: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    walksIntoObjects: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    enjoysSwitchingLights: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    dislikesCertainLights: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    usesPeripheralVision: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
  },
    hearing: {
      botheredByNormalSounds: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      reactsNegativelyToLoudNoises: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      seemsNotToHearCertainSounds: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      intenseInterestInUnnoticedSounds: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      scaredByUnexpectedSounds: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      distractedByBackgroundNoise: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      enjoysMakingRepetitiveNoises: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      botheredByHighPitchedSounds: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    },
    touch: {
      withdrawsFromLightTouch: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      doesNotNoticeBeingTouched: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      botheredByNewClothes: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      prefersTouchingOverBeingTouched: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      botheredByNailCutting: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      botheredByFaceTouch: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      avoidsMessyActivities: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      highPainTolerance: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      dislikesToothbrushing: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      enjoysPainfulSensations: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      difficultyFindingThingsByTouch: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    },
    smellAndTaste: {
      triesInedibleItems: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      gagsAtUnlikedFoods: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      enjoysSmellingObjects: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      discomfortWithSmells: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      ignoresStrongOdors: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    },
    bodyAwareness: {
      gripsObjectsTooTightly: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      seeksPushingAndPulling: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      unsureOfBodyMovements: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      holdsObjectsTooLoosely: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      exertsExcessiveForce: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      jumpsFrequently: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      petsAnimalsTooHard: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      pushesOtherChildren: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      chewsObjects: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      breaksObjectsFromForce: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    },
    balanceAndMovement: {
      exaggeratedFearOfMovement: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      goodBalance: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      avoidsBalanceActivities: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      fallsFromChair: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      poorBodyControlWhenFalling: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      doesNotGetDizzy: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      spinsBodyFrequently: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      distressedByHeadTilting: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      poorCoordination: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      fearOfElevators: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      leansOnObjects: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    },
    planningAndIdeation: {
      inconsistentDailyTasks: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      difficultyCarryingMultipleObjects: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      confusionOrganizingMaterials: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      troubleSequentialTasks: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      difficultyCompletingMultiStepTasks: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      troubleImitatingActions: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      difficultyCopyingModels: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      troubleGeneratingActivityIdeas: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
      repeatsSameActivities: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    },
      scoresHome: {
        SOC: { type: Number, default: 0 },
        VIS: { type: Number, default: 0 },
        HEA: { type: Number, default: 0 },
        TOU: { type: Number, default: 0 },
        ITEMS: { type: Number, default: 0 },
        BOD: { type: Number, default: 0 },
        BAL: { type: Number, default: 0 },
        PLA: { type: Number, default: 0 },
    },
}, { timestamps: true, versionKey: false });

export interface ISpmHomeEntity extends Omit<ISpmpHome, '_id'>, Document {}