import { Schema, Document } from 'mongoose';
import { ISpmPreSchool } from 'src/features/sensory-processing-measure-school-preschool/types/sensoryProcessingMeasureSchoolPreSchool'; 

export const SensoryProcessingMeasureSchoolPreSchoolSchema = new Schema({
  _id: { type: Schema.Types.ObjectId, required: true, auto: true },
  doctor: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  //responsable: { type: Schema.Types.ObjectId, required: true, ref: 'User' },
  //relationshipWithChild: { type: String, required: false},
  patient: { type: Schema.Types.ObjectId, required: true, ref: 'User' },
  gender: { type: String, required: false, enum: ['M', 'F'] },
  age: { type: Number, required: false},
  bitrhDate: { type: String, required: false},
  date: { type: String, required: true, },
  comment: { type: String, required: false },
  participationSocialSpmsps: {
    participatesInGamesAndActivitiesSchoolPreSchool: { type: String, required: false},
    waitsForTurnSchoolPreSchool: { type: String, required: false},
    participatesInCircleTimeSchoolPreSchool: { type: String, required: false},
    transitionsEasilyToNewActivitiesSchoolPreSchool: { type: String, required: false},
    joinsGamesWithoutInterruptingSchoolPreSchool: { type: String, required: false},
    followsClassRulesAndRoutinesSchoolPreSchool: { type: String, required: false},
    sharesToysAndMaterialsSchoolPreSchool: { type: String, required: false},
    cooperatesWithPeersForCommonGoalsSchoolPreSchool: { type: String, required: false},
    interactsWithPeersDuringPlaySchoolPreSchool: { type: String, required: false},
    resolvesConflictsWithPeersIndependentlySchoolPreSchool: { type: String, required: false}, 
  },
  visionSpmsps: { 
    coversEyesOrComplainsAboutLightingSchoolPreSchool: { type: String, required: false},
    distractedByVisualStimuliSchoolPreSchool: { type: String, required: false},
    difficultyLocatingObjectsSchoolPreSchool: { type: String, required: false},
    difficultyFindingItemsOnDeskOrTableSchoolPreSchool: { type: String, required: false},
    looksAroundDuringTeachersSpeechSchoolPreSchool: { type: String, required: false},
    difficultyPairingItemsByShapeAndColorSchoolPreSchool: { type: String, required: false},
    walksAmongOtherChildrenPlayingSchoolPreSchool: { type: String, required: false},
    staresAtPeopleOrObjectsSchoolPreSchool: { type: String, required: false},
    enjoysWatchingMovingObjectsSchoolPreSchool: { type: String, required: false},
    enjoysLookingAtMovingObjectsWithPeripheralVisionSchoolPreSchool: { type: String, required: false},
  },
  hearingSpmsps: { 
    discomfortWithLoudSoundsSchoolPreSchool:  { type: String, required: false},
    discomfortWithSingingOrMusicSchoolPreSchool: { type: String, required: false},
    unawareOfNewVoicesAndSoundsSchoolPreSchool: { type: String, required: false},
    unableToIdentifySoundSourceSchoolPreSchool: { type: String, required: false},
    makesRepetitiveSoundsSchoolPreSchool: { type: String, required: false},
    enjoysRepetitiveNoisesSchoolPreSchool: { type: String, required: false},
    unawareOfCertainSoundsSchoolPreSchool: { type: String, required: false},
    difficultyFocusingInNoisyEnvironmentsSchoolPreSchool: { type: String, required: false},
    unableToFollowVerbalInstructionsSchoolPreSchool: { type: String, required: false},
    disturbedByBackgroundNoiseSchoolPreSchool: { type: String, required: false},
  },
  touchSpmsps: { 
    avoidsBeingTouchedSchoolPreSchool: { type: String, required: false},
    discomfortWithDirtyHandsOrFaceSchoolPreSchool: { type: String, required: false},
    discomfortWithWashingHandsSchoolPreSchool: { type: String, required: false},
    reactsNegativelyToAccidentalTouchSchoolPreSchool: { type: String, required: false},
    doesNotWipeFaceAfterEatingSchoolPreSchool: { type: String, required: false},
    distressedByCertainTexturesSchoolPreSchool: { type: String, required: false},
    refusesToWearCostumesOrTightClothesSchoolPreSchool: { type: String, required: false},
    hasHighPainToleranceSchoolPreSchool: { type: String, required: false},
    ignoresNeedToUseBathroomSchoolPreSchool: { type: String, required: false},
    avoidsMessyActivitiesSchoolPreSchool: { type: String, required: false},
  },
  smellAndTasteSpmsps: { 
    chewsNonFoodItemsSchoolPreSchool: { type: String, required: false},
    doesNotNoticeStrongOrUnusualOdorsSchoolPreSchool: { type: String, required: false},
    discomfortWithCertainScentsSchoolPreSchool: { type: String, required: false},
    refusesToTryNewFoodsSchoolPreSchool: { type: String, required: false},
  },
  bodyAwarenessSpmsps: { 
    enjoysMovingFurnitureSchoolPreSchool: { type: String, required: false},
    breaksObjectsFromExcessiveForceSchoolPreSchool: { type: String, required: false},
    excessivelyJumpsOrClimbsSchoolPreSchool: { type: String, required: false},
    opensOrClosesDoorsWithExcessiveForceSchoolPreSchool: { type: String, required: false},
    usesExcessiveForceWhenPlayingWithObjectsSchoolPreSchool: { type: String, required: false},
    bumpsIntoPeersExcessivelySchoolPreSchool: { type: String, required: false},
    chewsOnNonFoodItemsSchoolPreSchool: { type: String, required: false},
    strugglesToManipulateFoodContainersSchoolPreSchool: { type: String, required: false},
    knocksOverOthersToysSchoolPreSchool: { type: String, required: false},
    squeezesScissorsExcessivelySchoolPreSchool: { type: String, required: false},
  },
  balanceAndMovementSpmsps: { 
    enjoysSpinningInRotatingEquipmentSchoolPreSchool: { type: String, required: false},
    needsSupportWhenStandingSchoolPreSchool: { type: String, required: false},
    fallsFromChairOrTendsToLeanSchoolPreSchool: { type: String, required: false},
    fearfulOfMovementActivitiesSchoolPreSchool: { type: String, required: false},
    excessivelyEnthusiasticAboutSpinningSchoolPreSchool: { type: String, required: false},
    clumsyWhenBendingToPickUpObjectsSchoolPreSchool: { type: String, required: false},
    strugglesToBalanceAndAvoidFallingSchoolPreSchool: { type: String, required: false},
    discomfortWithHeightsSchoolPreSchool: { type: String, required: false},
    poorCoordinationSchoolPreSchool:{ type: String, required: false},
    difficultyWithRhythmicBodyMovementsSchoolPreSchool: { type: String, required: false},
  },
  planningAndIdeationSpmsps: { 
    overlyFocusedOnIndividualActivitiesSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    strugglesToGenerateNewIdeasInPlaySchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    repeatsActivitiesWithoutChangingThemSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    needsRealObjectsToPlaySchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    strugglesToImitateActionsCorrectlySchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    playsWithOwnGamesAvoidingImitationSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    strugglesToCopyAdultsOrPeersInBuildingActivitiesSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    hasDifficultyUsingBothHandsForTasksSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    cannotCompleteMultistepTasksSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    strugglesWithRoutineSequencesSchoolPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
  },
  scoresSchoolPreSchool: {
    SOC: { type: Number, default: 0 },
    VIS: { type: Number, default: 0 },
    HEA: { type: Number, default: 0 },
    TOU: { type: Number, default: 0 },
    ITEMS: { type: Number, default: 0 },
    BOD: { type: Number, default: 0 },
    BAL: { type: Number, default: 0 },
    PLA: { type: Number, default: 0 },
},
});

export interface ISensoryProcessingMeasureSchoolPreSchoolEntity extends Omit<ISpmPreSchool, '_id'>, Document {}