import { Schema, Document } from 'mongoose';
import { Ethnicity } from 'src/features/sensory-processing-measure-school/types/sensoryProcessingMeasureSchool';
import { ISpmSchool } from 'src/features/sensory-processing-measure-school/types/spmschool';  

export const SensoryProcessingMeasureSchoolSchema = new Schema({
  _id: { type: Schema.Types.ObjectId, required: true, auto: true },
  doctor: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  //responsable: { type: Schema.Types.ObjectId, required: true, ref: 'User' },
  //relationshipWithChild: { type: String, required: false},
  patient: { type: Schema.Types.ObjectId, required: true, ref: 'User' },
  //gender: { type: String, required: false, enum: ['M', 'F'] },
  //age: { type: Number, required: false},
  //bitrhDate: { type: String, required: false},
  //ethnicity: { type: String, required: false, enum: Ethnicity },
  ethnicity: { type: String, required: false, enum: Ethnicity },
  date: { type: String, required: true, },
  participationSocialSchool: { 
    knowsHowToWorkInGroup: { type: String, required: false},
    resolvesConflictsIndependently:{ type: String, required: false},
    handlesFrustrationWithoutAggression: { type: String, required: false},
    participatesSpontaneouslyInGames: { type: String, required: false},
    participatesWithoutInterruptingGames: { type: String, required: false},
    hasFriendsAndChoosesToBeWithThem: { type: String, required: false},
    understandsAndUsesHumorInPlay: { type: String, required: false},
    maintainsAppropriatePersonalSpace: { type: String, required: false},
    maintainsEyeContactAppropriately: { type: String, required: false},
    switchesConversationTopicsAppropriately: { type: String, required: false},
  },
  visionSchool: { 
    botheredByLight: { type: String, required: false},
    distractedByVisualStimuli: { type: String, required: false},
    looksAroundInsteadOfPayingAttention: { type: String, required: false},
    movesObjectsInFrontOfEyes: { type: String, required: false},
    staresAtPeopleOrObjects:{ type: String, required: false},
    botheredByDimLightsInCinema: { type: String, required: false},
   },
   hearingSchool: {
    botheredByLoudSounds: { type: String, required: false},
    botheredByMusicOrInstruments: { type: String, required: false},

    doesntRespondToNewSounds: { type: String, required: false},
    cantDetermineSoundLocation:{ type: String, required: false},
    makesNoiseWhileClassIsSilent: { type: String, required: false},
    talksLoudlyDuringRecess: { type: String, required: false},
    makesUnusualNoisesAlone: { type: String, required: false},
  },
  touchSchool: {
    botheredByMessyHandsOrFace: { type: String, required: false},
    doesntTolerateDirtOnHandsOrClothes: { type: String, required: false},
    discomfortWithCertainTextures: { type: String, required: false},
    botheredByAccidentalTouchesFromFriends: { type: String, required: false},
    doesntRespondToBeingTouched: { type: String, required: false},
    seeksHotOrColdTemperatures: { type: String, required: false},
    touchesPeersInappropriately: { type: String, required: false},
    enjoysPainfulSensationsPre: { type: String, required: false},
    doesntWipeFoodOrSalivaFromFace: { type: String, required: false},
  },
  smellAndTasteSchool: { 
    botheredByTastesOrSmellsOfCertainFoods: { type: String, required: false},
    doesntNoticeStrongOdors: { type: String, required: false},
    cantDistinguishBetweenOdors: { type: String, required: false},
    triesToTasteOrLickNonFoodItems: { type: String, required: false},
  },
  bodyAwarenessSchool: { 
    spillsWhenOpeningContainers: { type: String, required: false},
    chewsOnObjectsOrClothing: { type: String, required: false},
    movesChairAbruptly:{ type: String, required: false},
    holdsObjectsTooLooselyPre: { type: String, required: false},
    runsOrJumpsInsteadOfWalking: { type: String, required: false},
    stompsFeetWhenWalking: { type: String, required: false},
    jumpsHardOnStairs: { type: String, required: false},
    opensOrClosesDoorsWithExcessiveForce: { type: String, required: false},
  },
  balanceAndMovementSchool: { 
    usesWallsForSupportWhenWalking: { type: String, required: false},
    tanglesFeetInChairLegs: { type: String, required: false},
    rocksInChairWhenSeated: { type: String, required: false},
    fidgetsWhenSeated: { type: String, required: false},
    fallsFromChairWhenSeated:{ type: String, required: false},
    leansOnWallsOrFurnitureForSupport: { type: String, required: false},
    needsSupportToGetUpFromFloor: { type: String, required: false},
    slumpsOrLeansOnDeskWhenSeated:{ type: String, required: false},
    poorCoordinationAppearsClumsy: { type: String, required: false},
  },
  planningAndIdeationSchool: { 
    inconsistentInDailyTasks: { type: String, required: false},
    strugglesToSolveProblemsEffectively: { type: String, required: false},
    dropsItemsWhenCarryingMultipleObjects: { type: String, required: false},
    hasDifficultyWithTaskSequencing: { type: String, required: false},
    failsToCompleteMultiStepTasks: { type: String, required: false},
    strugglesToImitateDemonstrations: { type: String, required: false},
    difficultyWithNewIdeasPre: { type: String, required: false},
    hasDifficultyCompletingTasksFromModels: { type: String, required: false},
    limitedImaginationInPlay: { type: String, required: false},
    repeatsSameActivitiesDuringRecess: { type: String, required: false},
    disorganizedMaterialsAtDesk: { type: String, required: false},
  },
});

export interface ISensoryProcessingMeasureSchoolEntity extends Omit<ISpmSchool, '_id'>, Document {}