import { Schema, Document } from 'mongoose';
import { ISpmHome } from 'src/features/sensory-processing-measure-home/types/spm';
import { Ethnicity } from 'src/features/sensory-processing-measure-school/types/sensoryProcessingMeasureSchool';

export const SensoryProcessingMeasureSchema = new Schema({
  _id: { type: Schema.Types.ObjectId, required: true, auto: true },
  doctor: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  //responsable: { type: Schema.Types.ObjectId, required: true, ref: 'User' },
  //relationshipWithChild: { type: String, required: false},
  patient: { type: Schema.Types.ObjectId, required: true, ref: 'User' },
  //gender: { type: String, required: false, enum: ['M', 'F'] },
  //age: { type: Number, required: false},
  //bitrhDate: { type: String, required: false},
  //ethnicity: { type: String, required: false, enum: Ethnicity },
  date: { type: String, required: true, },
  participationSocial: { 
    playsWithFriends: { type: String, required: false},
    interactsWithParents: { type: String, required: false},
    sharesThings: { type: String, required: false},
    maintainsConversation: { type: String, required: false},
    maintainsEyeContact: { type: String, required: false},
    joinsGames: { type: String, required: false},
    participatesInMeals: { type: String, required: false},
    participatesInFamilyOutings: { type: String, required: false},
    participatesInFamilyGatherings: { type: String, required: false},
    participatesInFriendActivities: { type: String, required: false},
  },

  vision: {
    botheredByLight: { type: String, required: false},
    difficultyFindingObjects: { type: String, required: false},
    closesOneEye:{ type: String, required: false},
    botheredByVisualStimuli: { type: String, required: false},
    difficultyFollowingObjects: { type: String, required: false},
    difficultyIdentifyingObjects: { type: String, required: false},
    enjoysWatchingMovingObjects: { type: String, required: false},
    walksIntoObjects: { type: String, required: false},
    enjoysSwitchingLights: { type: String, required: false},
    dislikesCertainLights: { type: String, required: false},
    usesPeripheralVision: { type: String, required: false},
  },
  hearing: {
    botheredByNormalSounds: { type: String, required: false},
    reactsNegativelyToLoudNoises: { type: String, required: false},
    seemsNotToHearCertainSounds: { type: String, required: false},
    intenseInterestInUnnoticedSounds: { type: String, required: false},
    scaredByUnexpectedSounds: { type: String, required: false},
    distractedByBackgroundNoise: { type: String, required: false},
    enjoysMakingRepetitiveNoises: { type: String, required: false},
    botheredByHighPitchedSounds: { type: String, required: false},
  },
  touch: { 
    withdrawsFromLightTouch: { type: String, required: false},
    doesNotNoticeBeingTouched: { type: String, required: false},
    botheredByNewClothes: { type: String, required: false},
    prefersTouchingOverBeingTouched: { type: String, required: false},
    botheredByNailCutting: { type: String, required: false},
    botheredByFaceTouch: { type: String, required: false},
    avoidsMessyActivities: { type: String, required: false},
    highPainTolerance: { type: String, required: false},
    dislikesToothbrushing: { type: String, required: false},
    enjoysPainfulSensations: { type: String, required: false},
    difficultyFindingThingsByTouch: { type: String, required: false},
  },
  smellAndTaste: {
    triesInedibleItems: { type: String, required: false},
    gagsAtUnlikedFoods: { type: String, required: false},
    enjoysSmellingObjects: { type: String, required: false},
    discomfortWithSmells: { type: String, required: false},
    ignoresStrongOdors: { type: String, required: false},
  },

  bodyAwareness: { 
    gripsObjectsTooTightly: { type: String, required: false},
    seeksPushingAndPulling: { type: String, required: false},
    unsureOfBodyMovements: { type: String, required: false},
    gripsObjectsTooLoosely: { type: String, required: false},
    exertsExcessiveForce: { type: String, required: false},
    jumpsFrequently: { type: String, required: false},
    petsAnimalsTooHard: { type: String, required: false},
    pushesOtherChildren: { type: String, required: false},
    chewsObjects: { type: String, required: false},
    breaksObjectsFromForce: { type: String, required: false},
   },
  balanceAndMovement: { 
    exaggeratedFearOfMovement: { type: String, required: false},
    goodBalance: { type: String, required: false},
    avoidsBalanceActivities: { type: String, required: false},
    fallsFromChair: { type: String, required: false},
    poorBodyControlWhenFalling: { type: String, required: false},
    doesNotGetDizzy: { type: String, required: false},
    spinsBodyFrequently: { type: String, required: false},
    botheredByHeadPositionChanges: { type: String, required: false},
    clumsyMotorCoordination: { type: String, required: false},
    fearOfElevators: { type: String, required: false},
    leansOnObjects: { type: String, required: false},
  },
  planningAndIdeation: {  
    inconsistentDailyTasks: { type: String, required: false},
    difficultyCarryingMultipleObjects: { type: String, required: false},
    confusionOrganizingMaterials: { type: String, required: false},
    troubleSequentialTasks: { type: String, required: false},
    difficultyCompletingMultiStepTasks: { type: String, required: false},
    troubleImitatingActions: { type: String, required: false},
    difficultyCopyingModels:{ type: String, required: false},
    troubleGeneratingActivityIdeas: { type: String, required: false},
    repeatsSameActivities: { type: String, required: false},
  },
});

export interface ISensoryProcessingMeasureEntity extends Omit<ISpmHome, '_id'>, Document {}