import { Schema, Document } from 'mongoose';
import { Ethnicity } from 'src/features/sensory-processing-measure-home/types/sensoryProcessingMeasure';
import { ISpmpSchool } from 'src/features/sensory-processing-measure-preschool-Home/types/spmps';

export const SensoryProcessingMeasurePreschoolSchema = new Schema({
  _id: { type: Schema.Types.ObjectId, required: true, auto: true },
  doctor: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  //responsable: { type: Schema.Types.ObjectId, required: true, ref: 'User' },
  //relationshipWithChild: { type: String, required: false},
  patient: { type: Schema.Types.ObjectId, required: true, ref: 'User' },
  //gender: { type: String, required: false, enum: ['M', 'F'] },
  //age: { type: Number, required: false},
  //bitrhDate: { type: String, required: false},
  //ethnicity: { type: String, required: false, enum: Ethnicity },
  date: { type: String, required: true, },
  participationSocialPreSchool: { 
    playsWithFriendsPreSchool: { type: String, required: false},
    sharesThingsPreSchool:{ type: String, required: false},
    participatesInGroupGamesPreSchool: { type: String, required: false},
    participatesAtMealsPreSchool: { type: String, required: false},
    participatesInFamilyOutingsPreSchool: { type: String, required: false},
    participatesInFamilyMeetingsPreSchool: { type: String, required: false},
    participatesWithFriendsPreSchool: { type: String, required: false},
    helpsWithFamilyActivitiesPreSchool: { type: String, required: false},
  },
  visionPreSchool: { 
    botheredByBrightLightsPreSchool: { type: String, required: false},
    difficultyFindingObjectsPreSchool: { type: String, required: false},
    difficultyRecognizingObjectsPreSchool: { type: String, required: false},
    likesWatchingMovingObjectsPreSchool: { type: String, required: false},
    walksThroughObjectsPreSchool:{ type: String, required: false},
    likesSwitchingLightsPreSchool: { type: String, required: false},
    likesLookingAtMovingObjectsPreSchool: { type: String, required: false},
    difficultyPayingAttentionPreSchool: { type: String, required: false},
    botheredByVisualStimuliPreSchool: { type: String, required: false},
    distractedWhileWalkingPreSchool: { type: String, required: false},
    difficultyCompletingTasksPreSchool: { type: String, required: false},
   },
  hearingPreSchool: {
    botheredByNormalSoundsPreSchool: { type: String, required: false},
    reactsNegativelyToLoudNoisesPreSchool: { type: String, required: false},
    seemsNotToHearPreSchool: { type: String, required: false},
    overlySensitiveToSoundsPreSchool:{ type: String, required: false},
    easilyDistractedByNoisesPreSchool: { type: String, required: false},
    likesMakingCertainSoundsPreSchool: { type: String, required: false},
    distressedBySharpNoisesPreSchool: { type: String, required: false},
    distressedInLoudPlacesPreSchool: { type: String, required: false},
    startledByLoudSoundsPreSchool: { type: String, required: false},
  },
  touchPreSchool: {
    avoidsBeingTouchedPreSchool: { type: String, required: false},
    prefersTouchingOthersPreSchool: { type: String, required: false},
    distressedByNailCuttingPreSchool: { type: String, required: false},
    botheredByFaceTouchPreSchool: { type: String, required: false},
    avoidsMessyActivitiesPreSchool: { type: String, required: false},
    highPainTolerancePreSchool: { type: String, required: false},
    dislikesBrushingTeethPreSchool: { type: String, required: false},
    enjoysPainfulSensationsPreSchool: { type: String, required: false},
    dislikesHairCarePreSchool: { type: String, required: false},
    dislikesHaircutsPreSchool: { type: String, required: false},
    avoidsCertainTexturesPreSchool: { type: String, required: false},
    vomitsDueToTexturesPreSchool: { type: String, required: false},
    dislikesFaceCleaningPreSchool: { type: String, required: false},
    droolsExcessivelyPreSchool: { type: String, required: false},
  },
  smellAndTastePreSchool: { 
    eatsNonFoodItemsPreSchool: { type: String, required: false},
    ignoresStrongOdorsPreSchool: { type: String, required: false},
    prefersCertainFlavorsPreSchool: { type: String, required: false},
    refusesToothpastePreSchool: { type: String, required: false},
  },
  bodyAwarenessPreSchool: { 
    holdsObjectsTooTightlyPreSchool: { type: String, required: false},
    seeksPushPullActivitiesPreSchool: { type: String, required: false},
    insecureDuringMovementPreSchool:{ type: String, required: false},
    holdsObjectsTooLooselyPreSchool: { type: String, required: false},
    excessivePressurePreSchool: { type: String, required: false},
    jumpsExcessivelyPreSchool: { type: String, required: false},
    roughWithAnimalsPreSchool: { type: String, required: false},
    pushesOthersPreSchool: { type: String, required: false},
    chewsObjectsPreSchool: { type: String, required: false},
  },
  balanceAndMovementPreSchool: { 
    overlyAfraidOfMovementPreSchool: { type: String, required: false},
    avoidsBalanceActivitiesPreSchool: { type: String, required: false},
    fallsFromChairPreSchool: { type: String, required: false},
    failsToCatchSelfWhenFallingPreSchool: { type: String, required: false},
    doesntGetDizzyPreSchool:{ type: String, required: false},
    spinsExcessivelyPreSchool: { type: String, required: false},
    distressedByHeadTiltingPreSchool: { type: String, required: false},
    poorCoordinationPreSchool:{ type: String, required: false},
    needsSupportToRisePreSchool: { type: String, required: false},
    rocksBodyPreSchool: { type: String, required: false},
    afraidOfStairsPreSchool: { type: String, required: false},
  },
  planningAndIdeationPreSchool: { 
    difficultyCarryingMultipleItemsPreSchool: { type: String, required: false},
    difficultyOrganizingItemsPreSchool: { type: String, required: false},
    confusedByRoutineStepsPreSchool: { type: String, required: false},
    difficultyCompletingMultiStepTasksPreSchool: { type: String, required: false},
    troubleImitatingActionsPreSchool: { type: String, required: false},
    cantCopyOthersPreSchool: { type: String, required: false},
    difficultyWithNewIdeasPreSchool: { type: String, required: false},
    repetitiveInPlayPreSchool: { type: String, required: false},
    troubleExitingCarSeatPreSchool: { type: String, required: false},
  },
});

export interface ISensoryProcessingMeasurePreschoolEntity extends Omit<ISpmpSchool, '_id'>, Document {}