import { Schema, Document } from 'mongoose';
import { Ethnicity } from 'src/features/sensory-processing-measure-school/types/sensoryProcessingMeasureSchool';
import { ISpmSchool } from 'src/features/sensory-processing-measure-school/types/spmschool';  

export const SensoryProcessingMeasureSchoolSchema = new Schema({
  _id: { type: Schema.Types.ObjectId, required: true, auto: true },
  doctor: { type: Schema.Types.ObjectId, ref: 'User', required: true },
  responsable: { type: Schema.Types.ObjectId, required: true, ref: 'User' },
  relationshipWithChild: { type: String, required: false},
  patient: { type: Schema.Types.ObjectId, required: true, ref: 'User' },
  gender: { type: String, required: false, enum: ['M', 'F'] },
  age: { type: Number, required: false},
  bitrhDate: { type: String, required: false},
  ethnicity: { type: String, required: false, enum: Ethnicity },
  date: { type: String, required: true, },
  participationSocialSchool: { 
    knowsHowToWorkInGroupSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    resolvesConflictsIndependentlySchool:{ type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    handlesFrustrationWithoutAggressionSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    participatesSpontaneouslyInGamesSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    participatesWithoutInterruptingGamesSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    hasFriendsAndChoosesToBeWithThemSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    understandsAndUsesHumorInPlaySchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    maintainsAppropriatePersonalSpaceSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    maintainsEyeContactAppropriatelySchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    switchesConversationTopicsAppropriatelySchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
  },
  visionSchool: { 
    botheredByLightSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    distractedByVisualStimuliSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    looksAroundInsteadOfPayingAttentionSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    movesObjectsInFrontOfEyesSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    staresAtPeopleOrObjectsSchool:{ type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    botheredByDimLightsInCinemaSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
   },
   hearingSchool: {
    botheredByLoudSoundsSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    botheredByMusicOrInstrumentsSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},

    doesntRespondToNewSoundsSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    cantDetermineSoundLocationSchool:{ type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    makesNoiseWhileClassIsSilentSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    talksLoudlyDuringRecessSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    makesUnusualNoisesAloneSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
  },
  touchSchool: {
    botheredByMessyHandsOrFaceSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    doesntTolerateDirtOnHandsOrClothesSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    discomfortWithCertainTexturesSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    botheredByAccidentalTouchesFromFriendsSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    doesntRespondToBeingTouchedSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    seeksHotOrColdTemperaturesSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    touchesPeersInappropriatelySchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    enjoysPainfulSensationsPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    doesntWipeFoodOrSalivaFromFaceSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
  },
  smellAndTasteSchool: { 
    botheredByTastesOrSmellsOfCertainFoodsSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    doesntNoticeStrongOdorsSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    cantDistinguishBetweenOdorsSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    triesToTasteOrLickNonFoodItemsSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
  },
  bodyAwarenessSchool: { 
    spillsWhenOpeningContainersSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    chewsOnObjectsOrClothingSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    movesChairAbruptlySchool:{ type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    holdsObjectsTooLooselyPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    runsOrJumpsInsteadOfWalkingSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    stompsFeetWhenWalkingSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    jumpsHardOnStairsSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    opensOrClosesDoorsWithExcessiveForceSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
  },
  balanceAndMovementSchool: { 
    usesWallsForSupportWhenWalkingSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    tanglesFeetInChairLegsSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    rocksInChairWhenSeatedSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    fidgetsWhenSeatedSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    fallsFromChairWhenSeatedSchool:{ type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    leansOnWallsOrFurnitureForSupportSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    needsSupportToGetUpFromFloorSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    slumpsOrLeansOnDeskWhenSeatedSchool:{ type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    poorCoordinationAppearsClumsySchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
  },
  planningAndIdeationSchool: { 
    inconsistentInDailyTasksSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    strugglesToSolveProblemsEffectivelySchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    dropsItemsWhenCarryingMultipleObjectsSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    hasDifficultyWithTaskSequencingSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    failsToCompleteMultiStepTasksSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    strugglesToImitateDemonstrationsSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    difficultyWithNewIdeasPreSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    hasDifficultyCompletingTasksFromModelsSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    limitedImaginationInPlaySchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    repeatsSameActivitiesDuringRecessSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
    disorganizedMaterialsAtDeskSchool: { type: String, required: false, enum: ['N', 'O', 'F', 'S']},
  },
});

export interface ISensoryProcessingMeasureSchoolEntity extends Omit<ISpmSchool, '_id'>, Document {}